### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tracker93** [Icalingua-plus-plus/Icalingua-plus-plus#1]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
之前用过icalingua可以正常使用，icalingua-plus-plus无法登录使用
**To Reproduce / 复现过程**
正常打开登录，必现
**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![1646028012](https://user-images.githubusercontent.com/54573114/155932103-150ff649-38c2-4fb5-b51e-9b037458f70f.jpg)

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 Deepin
 - Version [e.g. 2.1.4]
 20.4

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
你好，你是使用哪個 Release 包啟動出現問題的？另外請提供出現問題時輸出的日誌方便定位問題。

**Comment by tracker93** [comment]
> 你好，你是使用哪個 Release 包啟動出現問題的？另外請提供出現問題時輸出的日誌方便定位問題。

使用的deepin 20.4的操作系统，这个包icalingua_2.5.1_amd64.deb，之前2.5的版本也有这个问题。日志是在哪里生成了文件吗？我只看到控制台的报错，不知道是不是这个影响的
![1646096685(1)](https://user-images.githubusercontent.com/54573114/156085343-47ba1274-edba-49dc-b393-f1ba3546d0f6.jpg)

**Comment by Icalinguaplusplus** [comment]
> > 你好，你是使用哪個 Release 包啟動出現問題的？另外請提供出現問題時輸出的日誌方便定位問題。
> 
> 使用的deepin 20.4的操作系统，这个包icalingua_2.5.1_amd64.deb，之前2.5的版本也有这个问题。日志是在哪里生成了文件吗？我只看到控制台的报错，不知道是不是这个影响的 ![1646096685(1)](https://user-images.githubusercontent.com/54573114/156085343-47ba1274-edba-49dc-b393-f1ba3546d0f6.jpg)

請在終端中啟動Icalingua，會在終端中輸出日誌
另外可以試試 Github Actions CI 編譯的最新版本，看看是否有同樣的問題

**Comment by tracker93** [comment]
> > > 你好，你是使用哪個 Release 包啟動出現問題的？另外請提供出現問題時輸出的日誌方便定位問題。
> > 
> > 
> > 使用的deepin 20.4的操作系统，这个包icalingua_2.5.1_amd64.deb，之前2.5的版本也有这个问题。日志是在哪里生成了文件吗？我只看到控制台的报错，不知道是不是这个影响的 ![1646096685(1)](https://user-images.githubusercontent.com/54573114/156085343-47ba1274-edba-49dc-b393-f1ba3546d0f6.jpg)
> 
> 請在終端中啟動Icalingua，會在終端中輸出日誌 另外可以試試 Github Actions CI 編譯的最新版本，看看是否有同樣的問題

多谢啦，最新版可以的
