### ISSUE TITLE
[BUG]群文件下载时 点击一次下载多个

### ISSUE THREAD

**Issue by coutcin-xw** [Icalingua-plus-plus/Icalingua-plus-plus#100]
**Describe the bug / 描述**
群文件下载时 点击一次下载多个 在第一次下载成功以后 继续点击另外一个文件 无反应 关闭群文件窗口后 再次打开 点击下载 就会出现重复的下载

**To Reproduce / 复现过程**
打开群文件下载 下载一次成功后下载另外的文件
会无反应
再次打开下载会重复下载两次

**Expected behavior / 预期的结果**
无
**Screenshots / 截图**
暂无

**System information / 系统信息**
 - OS:  Arch Linux 
 - kernel: 5.17.7-arch1-1
 - Version 2.6.3

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
原版 Icalingua 的群文件管理系統并未開源，有時間將重寫，重寫后再考慮解決這些問題

**Comment by coutcin-xw** [comment]
好的
