### ISSUE TITLE
[Feature Request]关于群文件的功能建议

### ISSUE THREAD

**Issue by Temsys-Shen** [Icalingua-plus-plus/Icalingua-plus-plus#102]
1. 增加文件/文件夹的**移动** **重命名** 与 **删除**功能
2. 显示正在下载文件的**列表**以及**下载进度**
3. 增加**新建文件夹**功能

**Comment by Icalinguaplusplus** [comment]
原版 Icalingua 的群文件管理系統并未開源，有時間將重寫，重寫后再考慮解決這些問題
