### ISSUE TITLE
无法复制动图

### ISSUE THREAD

**Issue by LaoLittle** [Icalingua-plus-plus/Icalingua-plus-plus#103]
**Describe the bug / 描述**
无法复制动态图片/GIF

**To Reproduce / 复现过程**
复制一个动态图片

**Expected behavior / 预期的结果**
粘贴时还是上一次复制的图片

**System information / 系统信息**
Ubuntu 22.04

**Comment by Icalinguaplusplus** [comment]
受 Electron 限制，要實現複製動圖比較困難

**Comment by LaoLittle** [comment]
> 受 Electron 限制，要實現複製動圖比較困難

我觉得也可以加个报错，不然都不了解情况

**Comment by Icalinguaplusplus** [comment]
已實現
