### ISSUE TITLE
[BUG]状态栏/title bar在Windows上未适配黑暗模式

### ISSUE THREAD

**Issue by yuezhenglingluan** [Icalingua-plus-plus/Icalingua-plus-plus#104]
**Describe the bug / 描述**
状态栏这里的title bar在当前Windows系统开启深色模式后不会自动变成黑色底色

**To Reproduce / 复现过程**
打开软件，看向title bar
**Expected behavior / 预期的结果**
title bar应该是黑底白字的
**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/42693943/169430160-6d095a33-45a3-4949-9702-625bf6ae8787.png)

**System information / 系统信息**
 - OS: Windows 11
 - Version ![image](https://user-images.githubusercontent.com/42693943/169430202-5799e212-9002-45af-833c-deb23f93df33.png)

**Comment by Icalinguaplusplus** [comment]
此問題與 Windows 有關，與本項目并無關聯

**Comment by yuezhenglingluan** [comment]
好像与使用的electron版本也有关系？

**Comment by MemoryShadow** [comment]
其实我的KDE也有同样的问题

* OS: Manjaro 
* Version:

![图片](https://user-images.githubusercontent.com/31596045/175240772-f86a8eb1-290b-4f99-a876-44027e059d14.png)


截图示例:

![图片](https://user-images.githubusercontent.com/31596045/175240987-d8d1bf0b-b667-47eb-8fec-88e2f2df9b0f.png)

**Comment by TimFang4162** [comment]
因为electron直接用的系统的标题栏  
可行的解决办法是直接自己写一个标题栏，比如vscode  
![image](https://user-images.githubusercontent.com/60050973/180372835-b436581e-6d63-448f-b47e-98f460f9bac7.png)

**Comment by yaocccc** [comment]
我提交了一个PR，是关于在托盘图标菜单切换是否显示 标题栏的，如果可以把标题栏隐藏起来，其实展示的效果还不错

**Comment by yaocccc** [comment]
![image](https://user-images.githubusercontent.com/53512609/188546700-f67ccc44-ee2c-4371-b61d-688e7f4ea064.png)

**Comment by Icalinguaplusplus** [comment]
更新 Electron21 已解決
