### ISSUE TITLE
[BUG]除了首次获取历史消息可以一次获取大量直至点击“就要这些”，之后每次点击只能获取20或者19条

### ISSUE THREAD

**Issue by gerfind** [Icalingua-plus-plus/Icalingua-plus-plus#105]
除了首次获取历史消息可以一次获取大量直至点击“就要这些”，之后每次点击只能获取20或者19条历史消息，需要不断进行点击才能获取

System information / 系统信息
 - OS: Windows 10
 - Version 2.6.3

**Comment by Icalinguaplusplus** [comment]
~~這是 oicq 的特性~~

**Comment by clansty** [comment]
你应该右键岔开时间最多（比如说关机重启之后）的那段的下一条消息，然后点获取
