### ISSUE TITLE
无法收到群成员AT自己的消息 [BUG]

### ISSUE THREAD

**Issue by b23r0** [Icalingua-plus-plus/Icalingua-plus-plus#106]
**Describe the bug / 描述**
无法收到群成员AT自己的消息 

**To Reproduce / 复现过程**、
找一个QQ群，并让其他人AT你，你无法收到这条消息。

**System information / 系统信息**
 - OS: Windows11
 - Version 22621

**Comment by Icalinguaplusplus** [comment]
經測試不存在問題，請檢查 QQ 是否被風控或網絡是否異常

**Comment by b23r0** [comment]
我确信我用手机QQ可以收到，但同时在线的Icalingua-plus-plus无法收到。

**Comment by Icalinguaplusplus** [comment]
用的是哪個協議？

**Comment by b23r0** [comment]
版本2.6.1
协议：macos

别人回复引用我的消息并at我无法收到。

**Comment by b23r0** [comment]
好像又好了。
