### ISSUE TITLE
[BUG] 新版图片查看器旋转问题

### ISSUE THREAD

**Issue by ForkKILLET** [Icalingua-plus-plus/Icalingua-plus-plus#108]
**Describe the bug / 描述**
旋转是以左上角为旋转中心，导致旋转后图片离开对话框范围

**To Reproduce / 复现过程**
打开一张图片，旋转

**Expected behavior / 预期的结果**
图片应该保持在对话框内，或许以图片中心为旋转中心来旋转可以做到这一点。

**Screenshots / 截图**
我录制了一张 gif
![ezgif-1-88c8f1ae9c](https://user-images.githubusercontent.com/35412022/169630908-6d0285ec-bc74-43af-b427-deca47520f5b.gif)

**System information / 系统信息**
 - OS: Arch Linux 5.15.41-1-lts
 - Version 2.6.3-1

**Additional context / 附加信息**
无

**Comment by Icalinguaplusplus** [comment]
感謝反饋，已在主綫修復，~~之前在 dev 版本的時候居然沒發現~~
