### ISSUE TITLE
[Feature Request] 添加输入@时弹出类似官方客户端选择成员，并添加被@时消息定位功能

### ISSUE THREAD

**Issue by FirstMelody** [Icalingua-plus-plus/Icalingua-plus-plus#110]
添加输入@时弹出类似官方客户端选择成员，并添加被@时消息定位功能,没有这两个功能，在@人时前提对方先发过消息，较为麻烦，被@消息定位缺失难以快速定位。

**Comment by ForkKILLET** [comment]
也许我可以试着做一下 at 列表的功能

**Comment by Icalinguaplusplus** [comment]
群成員列表裏面已有 at 成員功能

> 也许我可以试着做一下 at 列表的功能

**Comment by ForkKILLET** [comment]
> 群成員列表裏面已有 at 成員功能
> 
> > 也许我可以试着做一下 at 列表的功能

之前没看到，不好意思
