### ISSUE TITLE
[Feature Request]可以添加插件功能嘛

### ISSUE THREAD

**Issue by ABCDCreeper** [Icalingua-plus-plus/Icalingua-plus-plus#114]
可以添加插件功能吗，让用户自行编写插件，如防撤回之类的

**Comment by Icalinguaplusplus** [comment]
防撤回一直都有，在被撤回的消息右鍵即可顯示
後期可能會考慮加入圖形化機器人插件功能

**Comment by MC-luoluo** [comment]
> 防撤回一直都有，在被撤回的消息右鍵即可顯示 後期可能會考慮加入圖形化機器人插件功能

绝，我找了半天防撤回，才知道居然自带
