### ISSUE TITLE
关于 linter

### ISSUE THREAD

**Issue by ForkKILLET** [Icalingua-plus-plus/Icalingua-plus-plus#117]
是否考虑采用一个 linter，如 eslint？目前的代码风格似乎需要改善（甚至有几处 `var`）。
还有一些疑问：

- 那些地方需要/不需要使用 typescript？
- 为什么同时出现了 `require` 和 `import`？
- 目前有哪些重写/重构计划？（防止冲突）

谢谢！

**Comment by Icalinguaplusplus** [comment]
- 除了靜態的和存常量的以外盡量都用 TypeScript 吧，~~畢竟也能兼容~~。
- 同時出現 `require` `import` 指哪些地方？
- 有考慮重寫群文件列表相關的代碼（原版未開源），但是最近比較忙。

**Comment by ForkKILLET** [comment]
> 同時出現 require import 指哪些地方？

<https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/blob/dev/icalingua/src/renderer/components/vac-mod/ChatWindow/Room/Room.vue#L302-L326>

**Comment by ForkKILLET** [comment]
其他知道了，谢谢
