### ISSUE TITLE
[Feature Request]可以看QQ频道吗

### ISSUE THREAD

**Issue by meiruitesi** [Icalingua-plus-plus/Icalingua-plus-plus#122]
希望能看QQ频道，这样基本就不需要官方客户端了（

**Comment by bcegkmqs23** [comment]
上游的协议支持看到了oicq-guild、go-cqhttp，不清楚实现得怎么样了。若能在icalingua用的话肯定是很美妙的事情。

**Comment by bcegkmqs23** [comment]
completed了么，点进去怎么是去年的commit
