### ISSUE TITLE
[Feature Request] 加入群助手功能

### ISSUE THREAD

**Issue by 123Duo3** [Icalingua-plus-plus/Icalingua-plus-plus#124]
群比较多，如果全部堆到消息列表里会比较乱（

**Comment by ToseLogic** [comment]
这应该很难做到，不要抱太大希望

**Comment by ForkKILLET** [comment]
我考完期末试着写一下（

**Comment by aimerneige** [comment]
可以考虑做一个类似 telegram 归档的功能

没必要一定要读取 QQ 的群助手信息

**Comment by 123Duo3** [comment]
> 可以考虑做一个类似 telegram 归档的功能
> 
> 没必要一定要读取 QQ 的群助手信息

确实，这样也可以
