### ISSUE TITLE
[BUG]无法显示邀请加群

### ISSUE THREAD

**Issue by meiruitesi** [Icalingua-plus-plus/Icalingua-plus-plus#126]
**Describe the bug / 描述**
他人邀请加群时，加群邀请在Icalingua++中显示为“[XML]”

**Screenshots / 截图**
![QQ_Image_1653882569559](https://user-images.githubusercontent.com/84609642/170913862-0ac7d8f4-5dd4-4529-9218-e54df93911ed.jpg)

![QQ_Image_1653882517227](https://user-images.githubusercontent.com/84609642/170913796-eebcfb81-6395-4481-a4d5-64d836950162.jpg)

**System information / 系统信息**
![image](https://user-images.githubusercontent.com/84609642/170913718-56b53d19-f894-44d8-ad6e-be3fc5408133.png)

**Comment by Icalinguaplusplus** [comment]
暫未支持此類消息解析，好友邀請請在`主菜單 - Icalingua++ - 验证消息`中查看
