### ISSUE TITLE
[BUG]Windows版在任务管理器的默认优先级为“低”，最小化到托盘后收不到消息

### ISSUE THREAD

**Issue by Doddddd** [Icalingua-plus-plus/Icalingua-plus-plus#127]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
Windows版在任务管理器的默认优先级为“低”，最小化到托盘后收不到消息

**To Reproduce / 复现过程**
运行在Windows 11

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![{C69B6F1B-5574-42CA-BE1F-1B5AB18619B9}.png](https://user-images.githubusercontent.com/88972478/171021103-ce3466ab-9417-41ec-beb3-397130f1a286.png)
**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]
Windows 11
2.6.3
**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
并無任何問題，優先級低的是渲染程式，在後臺不需要進行前端渲染。負責消息管理的是主程式。
如果無法接收消息請檢查賬號是否被風控。
