### ISSUE TITLE
[BUG] 无法向好友或向群里发送文件

### ISSUE THREAD

**Issue by boywuxu** [Icalingua-plus-plus/Icalingua-plus-plus#13]
2.5.4版本，Manjaro Linux

发送文件时提示如下：
![深度截图_选择区域_20220307203153](https://user-images.githubusercontent.com/60966176/157035778-181497e6-a619-4cdd-b504-9528150c6c59.png)

**Comment by Icalinguaplusplus** [comment]
上遊協議庫 oicq 暫不支持向好友發送文件。
經測試群文件可以註冊發送不存在問題，如果無法發送可能是賬號被風控。

**Comment by Icalinguaplusplus** [comment]
上遊協議庫 oicq 暫不支持向好友發送文件。
經測試群文件可以正常發送不存在問題，如果無法發送可能是賬號被風控。

**Comment by boywuxu** [comment]
好的，明白了
