### ISSUE TITLE
不能同步信息？

### ISSUE THREAD

**Issue by 1human** [Icalingua-plus-plus/Icalingua-plus-plus#130]
本来以为不能接收群成员临时会话
手机端来了消息，lcalingua++不显示
lcalingua++  2.6.3
Win11 x64

结果貌似是不能同步信息。。。
关闭状态下收到的信息是不同步的

**Comment by Icalinguaplusplus** [comment]
如需在關閉 Icalingua++ 時接收消息，請自行搭建並使用 bridge

**Comment by Puqns67** [comment]
我觉得可以变换一下思维，增加一个在 Icalingua++ 启动时自动同步消息的功能

**Comment by Lew1s777** [comment]
在选项中启用切换回话窗口时自动获取历史消息看看是否能大豆您的目标效果？

**Comment by 1human** [comment]
非常感谢。。。才看到
