### ISSUE TITLE
被禁言，可以发言后消息框仍未恢复

### ISSUE THREAD

**Issue by LaoLittle** [Icalingua-plus-plus/Icalingua-plus-plus#131]
**Describe the bug / 描述**
被禁言，可以发言后消息框仍未恢复
清除缓存也还是不变

**To Reproduce / 复现过程**
被禁言

**System information / 系统信息**
 - OS: Windows11
 - Version 2.6.3

**Comment by Icalinguaplusplus** [comment]
這個 bug 很早已被修復，經測試本地版不存在此 bug，是否使用了bridge？
