### ISSUE TITLE
[Feature Request] Need armv7l support.

### ISSUE THREAD

**Issue by BlueSky01st** [Icalingua-plus-plus/Icalingua-plus-plus#136]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
offer me a armv7l package.

**Describe alternatives you've considered**
compile by myself, but failed

**Additional context**

**Comment by Icalinguaplusplus** [comment]
60fb2db7312bcc1f6b1ee85ef2ed0509109546fc

**Comment by Icalinguaplusplus** [comment]
如果英語不會用 `please` 可以全部用中文交流，畢竟這邊都是中國人。
希望以後提 issue 的時候能用請求的語氣，項目維護者并沒有義務給你提供這樣的支持，這邊給你面子加上了，別的地方可不一定。

**Comment by BlueSky01st** [comment]
谢谢，打扰您了。
