### ISSUE TITLE
[BUG] 在Windows出现的一系列问题

### ISSUE THREAD

**Issue by Fuwaki** [Icalingua-plus-plus/Icalingua-plus-plus#139]
**Describe the bug / 描述**
1.超长语音造成短时间无响应
2.滑动卡顿(特殊)
3.内存占用大

**To Reproduce / 复现过程**
1.发送了个4:30秒的录音，窗口10秒内无响应，随后恢复正常，但录音不会显示
手机对应聊天:
![Screenshot_20220608_121631](https://user-images.githubusercontent.com/52279718/172530663-b6d89453-eb72-48cf-9e1e-0f3e0abd0fa5.jpg)
icallingua:
![a](https://user-images.githubusercontent.com/52279718/172530603-f6a0d386-28dc-44f8-af4e-ad1319a98986.png)

2.选中文字后，切换群聊，出现卡顿，未响应
(个人猜测可能和bug1有联动)
![video](https://user-images.githubusercontent.com/52279718/172537876-b22af55c-fa37-41d8-97cc-c813f1da3b72.mp4)

3. 暂时不太清楚如何复现，之后注意到会补充，附图如下
![s](https://user-images.githubusercontent.com/52279718/172538350-ad14de53-2939-4984-b39e-476da2ba3d9f.png)

**System information / 系统信息**
 - OS: Windows 11
 - Version [2.6.3]

**Comment by Icalinguaplusplus** [comment]
三個問題本質上是同一個（
轉換的語音以 base64 的形式存儲，而 base64 會體積膨脹，長語音可能導致卡頓，而切換群的卡頓恰好是讀取到了存儲的長語音

**Comment by Fuwaki** [comment]
但是似乎windows的内存比linux大了不少，linux端内存普遍在160mb左右，这内存是明显不对劲的(

**Comment by Icalinguaplusplus** [comment]
> 但是似乎windows的内存比linux大了不少，linux端内存普遍在160mb左右，这内存是明显不对劲的(

同樣的語音在 LInux 下無問題？

**Comment by Fuwaki** [comment]
在linux下没有看到语音显示，第一个bug的材料来自于我的linux截图，而2,3出自windows

**Comment by Icalinguaplusplus** [comment]
可以看下聊天記錄數據庫大小嗎？

**Comment by Fuwaki** [comment]
怎么看

**Comment by Icalinguaplusplus** [comment]
> 怎么看

`%appdata%\icalingua\databases\eqq*****.db`

**Comment by Fuwaki** [comment]
windows:460mb
