### ISSUE TITLE
[BUG] 长时间挂机后导致大量的性能占用

### ISSUE THREAD

**Issue by just-a-pony** [Icalingua-plus-plus/Icalingua-plus-plus#14]
**Describe the bug / 描述**
在长时间挂机（挂一天或几天的机）时会导致大量的cpu占用，应用也极其卡顿

**Screenshots / 截图**
![Screenshot_20220307_230936](https://user-images.githubusercontent.com/51501756/157063558-4eb02bc4-d51e-4778-a4c0-8d8b050d101a.jpg)

![Screenshot_20220307_231304](https://user-images.githubusercontent.com/51501756/157063567-cdce6fa0-d9ad-45d5-ae2f-af84fdef69f7.jpg)

**System information / 系统信息**
archlinux
截至icalingua-plus-plus的2.5.3版本，仍存在这个问题，至于目前的最新版本（即2.5.5），由于在长时间挂机，则没测试

**Additional context / 附加信息**
这个是一直以来都有的问题，重启应用后即正常

**Comment by Icalinguaplusplus** [comment]
掛機請關閉主窗口。沒關閉的情況下收到消息會一直渲染消息，掛機後收到大量消息會造成卡頓。

**Comment by bcegkmqs23** [comment]
大消息数量窗口的性能问题确实应该改进一下。如果不行的话，至少要么多支持一些消息管理功能，允许在不加载旧消息到屏幕上的情况下从云端获取指定范围的历史聊天记录。或者支持页面跳转。

**Comment by mochaaP** [comment]
> 掛機請關閉主窗口。沒關閉的情況下收到消息會一直渲染消息，掛機後收到大量消息會造成卡頓。

是否考慮實現 DOM recycling:
<https://github.com/hilongjw/vue-recyclerview>

**Comment by Neubulae** [comment]
我是关闭了主窗口的，然而一样卡

**Comment by aimerneige** [comment]
可能是 electron 的锅？这个问题早在 icalingua 时就已经有人提了。

**Comment by Icalinguaplusplus** [comment]
大量占用 cpu 似乎是 Lottie 動畫造成的，主綫上已經解決了 Lottie 動畫的問題。

**Comment by bcegkmqs23** [comment]
> 是否考慮實現 DOM recycling: https://github.com/hilongjw/vue-recyclerview

 翻历史消息也会导致卡起来，我都是手动用开发者工具删掉旧消息，只留最上面那条，然后继续加载更旧的消息。在改进性能问题之前，能不能先提供个删旧消息节点的菜单指令作为权宜之计呢，手动编辑HTML还是烦了点。

再理想一点的方案可能是有一个开关，打开后会在加载消息后自动删除与加载方向相反的冗余消息。

**Comment by NatsumiXD** [comment]
还没修吗

**Comment by Neubulae** [comment]
还没修吗（

**Comment by Ecalose** [comment]
目前2.7.3待机时间过长仍存在cpu满载问题

**Comment by Neubulae** [comment]
症状缓解，但仍然存在，挂机一晚上以后仍然卡顿，但不至于不能用就是

**Comment by Icalinguaplusplus** [comment]
最新的 development 也有問題？

-------- 原始郵件 --------

**Comment by Neubulae** [comment]
有，但缓解了很多，一晚上过去以后只有非常轻微的卡顿，可以继续使用

**Comment by Icalinguaplusplus** [comment]
最新 development 也有問題？

**Comment by Neubulae** [comment]
> 最新 development 也有問題？

嗯，还是有问题，并且偶尔有点开聊天窗口后会卡在聊天窗口无限加载的问题

**Comment by Neubulae** [comment]
大概就是，点开某些聊天窗口，聊天窗口会在那边无限转圈，你无法切换到其它窗口，任何方式都不行。Infinite-loading和滚动加载都有这个问题。
不优化就没问题，但不优化就会照常一晚上就卡死。
使用oicq-bridge

**Comment by Neubulae** [comment]
2.7.5仍然有上述问题

**Comment by Neubulae** [comment]
2.7.7仍然有上述问题

**Comment by kdly1995** [comment]
ubuntu 22.04 使用最新版的2.8.6，切换聊天对象的时候，单个cpu直接拉满，切换时间需要5-10秒

**Comment by hehellooedas** [comment]
2.8.10版本在挂机icalingua++一段时间后也会出现高占用CPU的情况，大概持续2～3分钟左右就正常了。
