### ISSUE TITLE
[BUG] Windows on ARM 下语音转换失败

### ISSUE THREAD

**Issue by qwqVictor** [Icalingua-plus-plus/Icalingua-plus-plus#142]
**Describe the bug / 描述**
Windows on ARM 下接收语音时语音无法完成转换，疑似未能正常调用 ffmpeg。

**To Reproduce / 复现过程**
接收语音。
**Expected behavior / 预期的结果**
正常转换出现语音播放。
**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/21100901/173184316-e0d86ee2-d773-4ee0-8c32-ad9f805a059b.png)

**System information / 系统信息**
 - OS: Microsoft Windows 11 on ARM64
 - Version 21H2 22000.708

**Additional context / 附加信息**
log 内容：
```json
{"message":{"errname":"Error","errMsg":"child process exited","e":"Error: child process exited"},"level":"error","service":"eqq-service"}
```
经检查，ffmpeg.dll 已为 ARM64 构建。

**Comment by Icalinguaplusplus** [comment]
需要自行下載 ffmpeg 並將目錄加入環境變數，Electron 自帶的無法使用。

**Comment by Icalinguaplusplus** [comment]
是否嘗試過安裝 arm 版的 ffmpeg.exe？

**Comment by qwqVictor** [comment]
> 是否嘗試過安裝 arm 版的 ffmpeg.exe？

这个是测试过的，我安装的正是 ARM 版。ffmpeg 在 PATH 中仍会导致失败，我近期忙完了深入排查一下。

**Comment by Icalinguaplusplus** [comment]
似乎是 silk-sdk 沒有正確交叉編譯造成的？
