### ISSUE TITLE
[Feature Request] 群聊中聊天at的选择

### ISSUE THREAD

**Issue by xiaoyv404** [Icalingua-plus-plus/Icalingua-plus-plus#145]
在输入框输入@的时候，输入框上方显示群聊成员，进行选择

**Comment by bcegkmqs23** [comment]
实际上我不喜欢这个，因为导致我写代码或者别的东西的时候变麻烦。Ctrl+M除了距离左手太远以外已经很好了，相比之下表情的Ctrl+E就非常方便。

另：at还好说，千万别把腾讯的那个斜杠触发表情的学来，恶心的很。

**Comment by ForkKILLET** [comment]
> 实际上我不喜欢这个，因为导致我写代码或者别的东西的时候变麻烦。Ctrl+M除了距离左手太远以外已经很好了，相比之下表情的Ctrl+E就非常方便。
> 
> 另：at还好说，千万别把腾讯的那个斜杠触发表情的学来，恶心的很。

是这样的，要多按一次 <kbd>Esc</kbd>，等设置页面做好了这个功能应该会默认关闭吧
