### ISSUE TITLE
[Feature Request] Image viewer UX imorovements when viewing extra long images

### ISSUE THREAD

**Issue by mark9804** [Icalingua-plus-plus/Icalingua-plus-plus#146]
**Is your feature request related to a problem? Please describe.**
I used to be using a native Mac QQ, and its image viewer eventListener behaves differently. For example, on receiving a long image, a native image viewer would behave as follows:

1. Resize itself to fit the width of the image;
2. Interpret "scroll" events as scrolling through the image, pinch in/out, <kbd>command</kbd> + <kbd>+/-</kbd> or zoom button to zoom image.

<details>
<summary>MacOS Native QQ Example</summary>

<img width="800" alt="image" src="https://user-images.githubusercontent.com/9006264/173195923-d8804152-d34b-4edb-9154-349509a4b94b.png">
</details>

On Icalingua++, the image viewer behaves a little differently.
1. The window size is fixed.
2. Image will be zoomed to fit in the image viewer window, users will have to zoom in/out to a proper magnification percentage, and use drag-on gestures to scroll through the image.

<details>
<summary>Icalingua++ Example</summary>

<img width="800" alt="image" src="https://user-images.githubusercontent.com/9006264/173195676-43ff5367-81f2-4443-8b7a-082be08c4458.png">
</details>

As is shown in the comparison above, the way that native Mac QQ handles extra long images is better.

**Describe the solution you'd like**
When viewing an image:
1. Resize the image viewer window according to image width (a max-width restriction should be considered).
2. Change the default scroll action from zooming in/out to scrolling, since the picture has already been zoomed.

**Describe alternatives you've considered**

**Additional context**
Screenshots:

<details>
<summary>MacOS Native QQ Example</summary>

<img width="800" alt="image" src="https://user-images.githubusercontent.com/9006264/173195923-d8804152-d34b-4edb-9154-349509a4b94b.png">
</details>

<details>
<summary>Icalingua++ Example</summary>

<img width="800" alt="image" src="https://user-images.githubusercontent.com/9006264/173195676-43ff5367-81f2-4443-8b7a-082be08c4458.png">
</details>

**Comment by Icalinguaplusplus** [comment]
Not everyone used to scroll the wheel to scroll the image, because in PCQQ, the wheel event is handled as zoom, and most people are used to PCQQ.
