### ISSUE TITLE
[BUG]无法上传文件 上传文件导致Icalingua++卡死

### ISSUE THREAD

**Issue by wukibaka** [Icalingua-plus-plus/Icalingua-plus-plus#155]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
无法上传文件 上传文件导致Icalingua++未响应
**To Reproduce / 复现过程**
随意上传一个群文件
**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: win10 LTSB2015
 - Version 2.6.5

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
不知如何搞到logs

**Comment by wukibaka** [comment]
上传图片倒没问题

**Comment by Icalinguaplusplus** [comment]
上傳是啥樣的文件？

**Comment by wukibaka** [comment]
> 上傳是啥樣的文件？

18mb的zip文件

**Comment by Icalinguaplusplus** [comment]
> > 上傳是啥樣的文件？
> 
> 18mb的zip文件

進測試無異常，請檢測硬碟或防毒軟件的問題

**Comment by wukibaka** [comment]
> > > 上傳是啥樣的文件？
> > 
> > 
> > 18mb的zip文件
> 
> 進測試無異常，請檢測硬碟或防毒軟件的問題

没装杀毒软件 defender都没开

**Comment by mark9804** [comment]
我测试上传一个 90MB 的 exe 文件卡死 （macOS 12.4 21F79， M1 Pro），不过没研究过 oicq 对于非图片文件处理的部分，如果也是像图片一样转换成 base64 上传的话似乎确实有可能因为文件太大而导致假死现象

**Comment by Icalinguaplusplus** [comment]
> 我测试上传一个 90MB 的 exe 文件卡死 （macOS 12.4 21F79， M1 Pro），不过没研究过 oicq 对于非图片文件处理的部分，如果也是像图片一样转换成 base64 上传的话似乎确实有可能因为文件太大而导致假死现象

可以提供去敏后的復現視頻嗎

**Comment by mark9804** [comment]
> 可以提供去敏后的復現視頻嗎

刚才尝试了一下，没有成功复现，我会继续留意

**Comment by wukibaka** [comment]
复现视频
[2022-07-29 12-35-25.zip](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/files/9216102/2022-07-29.12-35-25.zip)

**Comment by Icalinguaplusplus** [comment]
一直沒有復現找到具體原因，估計和上傳的文件有關係
