### ISSUE TITLE
[BUG]上传文件名超长的文件时布局异常

### ISSUE THREAD

**Issue by mark9804** [Icalingua-plus-plus/Icalingua-plus-plus#163]
**Describe the bug / 描述**
上传一个文件名超长的文件时布局异常

**To Reproduce / 复现过程**
上传一个文件名超长的文件

**Expected behavior / 预期的结果**
聊天输入框应该有一个 `max-width`，不应该直接把其他按钮给挤掉
我八月中旬之后有空，到时候可以重写一个基于 grid 的布局，应该可以一劳永逸解决这个问题 ~~如果这个问题会咕这么久的话~~

**Screenshots / 截图**
<img width="945" alt="image" src="https://user-images.githubusercontent.com/9006264/174488696-5f1c2ff9-5737-4cd8-a21b-dce4b02111bc.png">

**System information / 系统信息**
 - OS: macOS
 - Version 12.4 (21F79)

**Comment by xiaoyv404** [comment]
在[新版本](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/7ffaa1c0091f23492cc1a80b0f62b4f1b11e6c94)已经修复了哦，可以close了
