### ISSUE TITLE
[BUG]在Gnome(Wayland)下面运行一段时间后会突然消失

### ISSUE THREAD

**Issue by a15355447898a** [Icalingua-plus-plus/Icalingua-plus-plus#165]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

在Gnome(Wayland)下面运行一段时间后会突然消失(前台和托盘都没有了)

**To Reproduce / 复现过程**

在Gnome(Wayland)下面运行一段时间

**Expected behavior / 预期的结果**

不该消失啊?

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: openSUSE 15.4
 - Version 2.6.5

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by xiaozhangup** [comment]
我也遇到过，但我是在挂起&锁定后再登陆后消失
几乎是100%触发

**Comment by Icalinguaplusplus** [comment]
有日志嗎

> 我也遇到过，但我是在挂起&锁定后再登陆后消失 几乎是100%触发

**Comment by xiaozhangup** [comment]
> 有日志嗎
> 
> > 我也遇到过，但我是在挂起&锁定后再登陆后消失 几乎是100%触发

日志文件在？

**Comment by Icalinguaplusplus** [comment]
> > 有日志嗎
> > > 我也遇到过，但我是在挂起&锁定后再登陆后消失 几乎是100%触发
> 
> 日志文件在？

~/.config/icalingua/Crashpad
