### ISSUE TITLE
[BUG] 使用较长一段时间后打开表情面板时突然无响应

### ISSUE THREAD

**Issue by WhiredPlanck** [Icalingua-plus-plus/Icalingua-plus-plus#167]
**Describe the bug / 描述**
Icalingua++ 保持放在前台一段时间后，会在打开表情面板时突然无响应。明显的表现是鼠标在箭头（指针）和点击（手形）状态之间来回闪烁，点击任何按钮没反应。

**To Reproduce / 复现过程**
正常使用软件一段时间（20 分钟左右起），然后打开表情面板。能较稳定复现。
偶尔即使不打开面板，也会在点击一两下后陷入无响应状态。

**Expected behavior / 预期的结果**
一切正常

**Screenshots / 截图**
N/A

**System information / 系统信息**
 - OS: AOSC OS
 - Version 2.6.3 (AppImage)

**Additional context / 附加信息**
N/A（不知道如何提供有效日志）

**Comment by ForkKILLET** [comment]
我这也能稳定复现，症状为鼠标在手形和指针两种形态间反复切换，并卡死。

**Comment by Icalinguaplusplus** [comment]
加載 Stickers 時會受硬盤限制導致卡頓

**Comment by Icalinguaplusplus** [comment]
加載 Stickers 時有可能會受 I/O 限制而加載卡頓
