### ISSUE TITLE
[Feature Request] 希望Windows版本能自定义数据目录

### ISSUE THREAD

**Issue by Doddddd** [Icalingua-plus-plus/Icalingua-plus-plus#169]

**Comment by TimFang4162** [comment]
自定义安装目录可以，直接解压exe的安装包即可
![image](https://user-images.githubusercontent.com/60050973/180375706-da80d7c0-461f-44c9-b7b8-ccac7265af3e.png)

**Comment by xiaoyv404** [comment]
自定义安装目录 已经可以了

**Comment by Icalinguaplusplus** [comment]
啓動時增加 `--user-data-dir="$PATH_YOU_WANT"`
`$PATH_YOU_WANT` 為指定的數據目錄
