### ISSUE TITLE
[BUG] Windows not showing up on Sway native Wayland

### ISSUE THREAD

**Issue by glyh** [Icalingua-plus-plus/Icalingua-plus-plus#17]
**Describe the bug / 描述**
Windows not showing up on Sway.

**To Reproduce / 复现过程**
1. Install Sway on Arch Linux
2. Install `icalingua++-git` from AUR
3. Fire up icalingua with `icalingua --enable-features=UseOzonePlatform --ozone-platform=wayland`

**Expected behavior / 预期的结果**
Opened on native Wayland. But actually it just showed up in the tray and won't open.

**System information / 系统信息**
 - OS: `Linux arch 5.16.12-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 02 Mar 2022 12:22:53 +0000 x86_64 GNU/Linux`
 - Version: `Client 2.5.6, Electron 13.6.9, Node 14.16.0, Chromium 91.0.4472.164`

**Additional context / 附加信息**

Seems like icalingua is ignoring electron-flags, is this intended?

Error log:
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Cannot find an external image viewer
icalingua> (node:729438) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `icalingua --trace-warnings ...` to show where the warning was created)
Aria2 RPC connected
icalingua> 检查更新失败
{"message":{"errname":"Error","errMsg":"Request failed with status code 403","e":"Error: Request failed with status code 403"},"level":"error","service":"eqq-service"}
(node:729438) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at e.exports (/opt/icalingua/resources/app.asar/dist/electron/main.js:5:145569)
    at e.exports (/opt/icalingua/resources/app.asar/dist/electron/main.js:5:240402)
    at IncomingMessage.<anonymous> (/opt/icalingua/resources/app.asar/dist/electron/main.js:296:169016)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:729438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:729438) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
icalingua> 
```

**Comment by glyh** [comment]
BTW, it's working with XWayland.

**Comment by Icalinguaplusplus** [comment]
Will the same problem occur if using a .deb or tar package from Releases?

**Comment by BenderBlog** [comment]
@glyh 
I am using the latest version of the software. Fired up with the 'icalingua --enable-features=UseOzonePlatform --ozone-platform=wayland' command, it works well on kde-wayland.
Maybe developers will be appreciate if you could use the latest version, since 2.5.3 is too old:-P

**Comment by glyh** [comment]
@BenderBlog Well, I'm using Sway, not KDE. Also, I've updated `icalingua++-git` AUR package. I've updated the output of versions of icalingua though.

**Comment by BenderBlog** [comment]
@glyh

Well, I do notice this line, which is related to a driver problem.

>libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

Here is a reference to this, which is pretty similar to the problem you encounter:
https://github.com/hashicorp/boundary-ui/issues/885

Hope it helps.
