### ISSUE TITLE
希望添加编辑功能

### ISSUE THREAD

**Issue by Icecoke-ops** [Icalingua-plus-plus/Icalingua-plus-plus#171]
希望添加像 telegram 一样的连天记录右键的编辑功能，总是手动的复制消息，撤回，粘贴，编辑，发送太麻烦了
虽然QQ支持的撤回时间只有两分钟，但是还是觉得有用
谢谢，开发人员辛苦了。

**Comment by xyf007** [comment]
按 ↑ 键可以编辑（

**Comment by Icecoke-ops** [comment]
> 按 ↑ 键可以编辑（

好的，谢谢
