### ISSUE TITLE
[BUG] 当使用新分支的新版本，更新提示会错误的提示我有更新版

### ISSUE THREAD

**Issue by xiaoyv404** [Icalingua-plus-plus/Icalingua-plus-plus#172]
目前分支deps-update-electron19 版本 2.6.5-27-gc044117 ，情况如图
![image](https://user-images.githubusercontent.com/63290381/177062440-af4f8411-3ba6-44c4-a7aa-4fe9cc757fe3.png)
![image](https://user-images.githubusercontent.com/63290381/177062457-c3956080-2bf6-4e9c-96a5-a364291ad1e7.png)

**Comment by Icalinguaplusplus** [comment]
檢查更新獲取的為 dev 分支的最新版本

**Comment by xiaoyv404** [comment]
> 檢查更新獲取的為 dev 分支的最新版本

懂了
