### ISSUE TITLE
[BUG] 不应当出现的at全体成员

### ISSUE THREAD

**Issue by xiaoyv404** [Icalingua-plus-plus/Icalingua-plus-plus#176]
当不是管理时，依然出现at全体成员

**Comment by aimerneige** [comment]
没有记错的话，使用 oicq，普通用户也是**可以发送** at 全体成员的消息的。

我的意见是既然可以通过 oicq 实现，没有必要自废手脚。

**Comment by aimerneige** [comment]
没有记错的话，使用oicq，普通用户也是可以发送at全体成员的消息的。没有必要自废手脚。

**Comment by xiaoyv404** [comment]
> 没有记错的话，使用 oicq，普通用户也是**可以发送** at 全体成员的消息的。
> 
> 我的意见是既然可以通过 oicq 实现，没有必要自废手脚。

我尝试过发送，结果就是这个
![image](https://user-images.githubusercontent.com/63290381/177253078-2a0d35f8-488c-4bb4-b242-fd7b9e5d35f9.png)

**Comment by aimerneige** [comment]
> > 没有记错的话，使用 oicq，普通用户也是**可以发送** at 全体成员的消息的。
> > 我的意见是既然可以通过 oicq 实现，没有必要自废手脚。
> 
> 我尝试过发送，结果就是这个 ![image](https://user-images.githubusercontent.com/63290381/177253078-2a0d35f8-488c-4bb4-b242-fd7b9e5d35f9.png)

这就不清楚了，我之前写的 bot 出 bug 了，是可以发送 at 全体成员的信息的

**Comment by xiaoyv404** [comment]
> 这就不清楚了，我之前写的 bot 出 bug 了，是可以发送 at 全体成员的信息的

唔，那就奇怪了，等开发者看看怎么办吧

**Comment by xiaoyv404** [comment]
我一直用的mirai，so

**Comment by aimerneige** [comment]
> > > 没有记错的话，使用 oicq，普通用户也是**可以发送** at 全体成员的消息的。
> > > 我的意见是既然可以通过 oicq 实现，没有必要自废手脚。
> > 
> > 
> > 我尝试过发送，结果就是这个 ![image](https://user-images.githubusercontent.com/63290381/177253078-2a0d35f8-488c-4bb4-b242-fd7b9e5d35f9.png)
> 
> 这就不清楚了，我之前写的 bot 出 bug 了，是可以发送 at 全体成员的信息的

对 bug 的说明：

原本想要实现一个在群内 at 某群员的功能，但是群员 id 的变量值被置 0 而没有正确赋值，导致 at 了 0，结果就是 at 全体成员，而不是预期群员。

bot 没有管理员，但是消息确实有发出而且群员都收到了提醒。（群友不堪其扰

**Comment by xiaoyv404** [comment]
草
