### ISSUE TITLE
[BUG] 群消息发送两遍

### ISSUE THREAD

**Issue by xyf007** [Icalingua-plus-plus/Icalingua-plus-plus#179]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
在一些群中发送信息用时很长并返回错误窗口「群消息可能发送失败，请检查消息内容」，但是重新获取消息后，发现该消息被发送两次。

**To Reproduce / 复现过程**
在一些群中发送信息。

**Expected behavior / 预期的结果**
消息正常发送。

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: Ubuntu 20.04
 - Version 2.6.6

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
在其他平台和 Linux 官方客户端上无此现象，不知道是否与帐号有关。

**Comment by Icalinguaplusplus** [comment]
賬號被風控或發送内容有特殊内容導致無回執
