### ISSUE TITLE
[Feature Request] 希望添加自动更新功能

### ISSUE THREAD

**Issue by LeSnow-Ye** [Icalingua-plus-plus/Icalingua-plus-plus#180]
**Is your feature request related to a problem? Please describe.**
每次更新都得重新下载安装整个 Icalingua++ ，实在不大方便

**Describe the solution you'd like**
自动更新。通过软件本身逻辑更新，或者干脆丢给 choco 之类的包管理器也要方便一点

**Additional context**
大大辛苦了
![QQ_Image_1657195895998](https://user-images.githubusercontent.com/40481418/177770170-15b35306-6e6e-4a73-843b-f88b4f839f5f.jpg)

**Comment by aimerneige** [comment]
https://gist.github.com/aimerneige/a7917a2fc15b17374093aab57ec5e099

**Comment by aimerneige** [comment]
> https://gist.github.com/aimerneige/a7917a2fc15b17374093aab57ec5e099

对不起，刚发现我 gist 没开 public 太尴尬了
