### ISSUE TITLE
[BUG]在开启自动刷新历史消息后，该群消息已是最新，还是有获取消息的提示

### ISSUE THREAD

**Issue by kukume** [Icalingua-plus-plus/Icalingua-plus-plus#184]
**To Reproduce / 复现过程**
在开启自动刷新历史消息后，该群消息已是最新，还是有获取消息的提示
**Expected behavior / 预期的结果**
消息已是最新，不应该有这个提示

**Screenshots / 截图**
<img width="300" alt="image" src="https://user-images.githubusercontent.com/45278810/177975627-44e371fb-da92-407a-80ef-c6e58b19034d.png">

**System information / 系统信息**
 - OS: windows
 - Version 2.6.6

**Comment by Icalinguaplusplus** [comment]
~~不影響正常使用，算特性~~
