### ISSUE TITLE
[BUG]发送消息后，消息已发送成功，但是不在页面显示已发送的消息

### ISSUE THREAD

**Issue by kukume** [Icalingua-plus-plus/Icalingua-plus-plus#185]
**Describe the bug / 描述**
发送消息后，消息已发送成功，但是不在页面显示已发送的消息，得重新刷新消息才会显示已发送的消息

**To Reproduce / 复现过程**
不明，偶尔出现
**Expected behavior / 预期的结果**
在页面显示已发送的消息

**System information / 系统信息**
 - OS: windows
 - Version 2.6.6

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
可能是賬號風控導致未收到消息
