### ISSUE TITLE
[BUG] 历史记录中的视频需要刷新视频地址才能播放

### ISSUE THREAD

**Issue by telecomadm1145** [Icalingua-plus-plus/Icalingua-plus-plus#187]
**Describe the bug / 描述**
历史记录中的视频需要刷新视频地址才能播放

**To Reproduce / 复现过程**
让其他人在群里发送一条视频消息，切换到另一个群聊再切换回原群聊，向上翻历史记录到视频消息（转圈加载后无法播放，如图1）

**Expected behavior / 预期的结果**
视频不需要刷新视频地址正常播放

**Screenshots / 截图**
历史记录中的视频消息
![image1](https://user-images.githubusercontent.com/47657299/178107983-83a1bd2a-5081-4007-a8f4-22f7528121b1.png)
刷新视频地址后
![image2](https://user-images.githubusercontent.com/47657299/178108016-f7e31092-4fe1-4540-bf91-98df14c99bf7.png)

**System information / 系统信息**
 - OS: Windows
 - Version 2.6.6

**Additional context / 附加信息**
无

**Comment by clansty** [comment]
不是 bug，这个地址是会过期的
