### ISSUE TITLE
[BUG] Windows 通知显示应用名错误的显示为 electron.app.Icalingua++

### ISSUE THREAD

**Issue by telecomadm1145** [Icalingua-plus-plus/Icalingua-plus-plus#189]
**Describe the bug / 描述**
Windows 通知/气泡显示应用名错误的显示为 electron.app.Icalingua++

**To Reproduce / 复现过程**
使 Icalingua++ 产生一个 Windows 通知/气泡

**Expected behavior / 预期的结果**
显示为 Icalingua++

**Screenshots / 截图**
Icalingua++
![image](https://user-images.githubusercontent.com/47657299/178114507-ea9ad815-7d30-4d33-a190-c321ab2f5f33.png)
其他应用
![image](https://user-images.githubusercontent.com/47657299/178114915-49547111-a12b-45de-a015-8a899373d79e.png)

**System information / 系统信息**
 - OS: Windows
 - Version 2.6.6

**Additional context / 附加信息**
同时 Icalingua++ 通知的应用图标也为空（如图）

**Comment by xiaoyv404** [comment]
那你认为应该显示什么呢，就直接显示Icalingua++吗，还是按照消息类型

**Comment by KagaJiankui** [comment]
尽量按消息类型（私聊消息，群消息，置顶消息）或者设定的消息优先级显示
