### ISSUE TITLE
[BUG]Windows端时而无法显示图片

### ISSUE THREAD

**Issue by LS-KR** [Icalingua-plus-plus/Icalingua-plus-plus#19]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
![图片](https://user-images.githubusercontent.com/64070144/158042516-a11662d5-97ba-44cb-83da-01a6798deab6.png)
如图所示，当打开发出的图片时，新窗口显示的不是图片内容，而是纯白窗口
**To Reproduce / 复现过程**
发出一张图片，然后打开，可能会像截图所示不显示图片内容
**Expected behavior / 预期的结果**
应当正常显示图片内容并正常进行操作
**Screenshots / 截图**
![图片](https://user-images.githubusercontent.com/64070144/158042614-3b808845-f211-4ef4-91e3-8b3fd5d3853e.png)
![图片](https://user-images.githubusercontent.com/64070144/158042641-1c20c8cd-acf0-4e55-82e9-d79a07822af4.png)

**System information / 系统信息**
 - OS: Windows 11 21H2 22000.556
 - Version 2.5.5

**Additional context / 附加信息**
无

**Comment by LS-KR** [comment]
2.5.6版本仍存在此问题

**Comment by Icalinguaplusplus** [comment]
已在 dev 分支修復，請在下個版本查看具體情況
另外，由於原數據已存儲，只有新發送的圖片不會出現此問題

**Comment by Icalinguaplusplus** [comment]
已在 2.5.7 修復

**Comment by LS-KR** [comment]
谢谢，2.5.7版本已经解决了

**Comment by sSkieri** [comment]
windows版本2.6.6 仍然点击图片后无法显示
![image](https://user-images.githubusercontent.com/81229545/180604158-640cfe9c-0e64-4100-b1bf-be6b8fc9d420.png)

**Comment by sSkieri** [comment]
![image](https://user-images.githubusercontent.com/81229545/180604425-ab0fd479-360b-4fa8-8863-461b74cb91f2.png)
群公告，文件 帮助等也是同样的问题

**Comment by sSkieri** [comment]
windows 2.6.6版本在退出软件重新登陆(其中登陆了正常版本的TIM)以后又会出现这个问题 包括群文件 帮助等 全部白屏 重新启动电脑后的首次运行本程序才会再次恢复图片显示

**Comment by sSkieri** [comment]
![image](https://user-images.githubusercontent.com/81229545/180608686-9e838dfa-3c0d-44d8-b5d6-80a5b43b60b7.png)
tu'sh图中三个窗口分别为公告 查看头像和群文件
![image](https://user-images.githubusercontent.com/81229545/180608726-e843efce-9aaf-44b5-a16b-68271199bcec.png)
本张为帮助界面

**Comment by sSkieri** [comment]
版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎12/‎21
操作系统版本	22000.795
体验	Windows 功能体验包 1000.22000.795.0
打开软件后软件占用任务管理器一秒后瞬间消失 无法运行 管理员身份下可以运行但是会导致以上全部白屏的问题
