### ISSUE TITLE
[BUG] 获取历史记录，有未捕获的异常

### ISSUE THREAD

**Issue by zzxzzk115** [Icalingua-plus-plus/Icalingua-plus-plus#191]
**Describe the bug / 描述**
当获取历史记录时，存在未捕获的异常，Error弹窗

**To Reproduce / 复现过程**
选项中设置:
![image](https://user-images.githubusercontent.com/33739170/178144259-d52f6d60-67d5-4265-a192-057a52f31f93.png)

**Expected behavior / 预期的结果**
添加对异常的处理，不弹窗

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/33739170/178144223-e0befcb8-8f49-483b-9a77-c730ec81dae6.png)

**System information / 系统信息**
 - OS: Manjaro i3-wm社区版 
 - Version 21.3.2 Ruah
![image](https://user-images.githubusercontent.com/33739170/178144343-0b0a540c-d0bf-4804-a446-450f21306971.png)

**Additional context / 附加信息**
无

**Comment by Icalinguaplusplus** [comment]
現在是否還有這個問題？
