### ISSUE TITLE
[BUG]无法接收联系人消息，但能接收群消息

### ISSUE THREAD

**Issue by FrozenArcher** [Icalingua-plus-plus/Icalingua-plus-plus#194]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
如题，能看到自己在本软件上发出的消息，也能看到在手机上发出的消息（正常同步），但不能收到联系人发来的消息（手机可以收到）。群聊收发正常。
要是能同步历史消息就好了。

**System information / 系统信息**
 - OS: Arch linux
 - Version 5.18.10

**Comment by FrozenArcher** [comment]
尝试过换数据库（内置和postgresql），没区别。

**Comment by Icalinguaplusplus** [comment]
賬號可能被風控
