### ISSUE TITLE
希望可以有群里屏蔽某人的选项

### ISSUE THREAD

**Issue by kukume** [Icalingua-plus-plus/Icalingua-plus-plus#195]
我在官方客户端屏蔽了群内一个人，但是在`Icalingua-plus-plus`还是会显示这个人的群消息

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/82edf851254e863a59d220f3fd6888259e69ba2c#diff-509a9bb209eb5e63f28a07d9b77e0064ed057ac73fabfed3e5e8bf9f94539c41R1484
