### ISSUE TITLE
[Feature Request] 多开账户的功能

### ISSUE THREAD

**Issue by xiaoyv404** [Icalingua-plus-plus/Icalingua-plus-plus#198]
- 就像qq一样可以多开客户端啦~ #197 就是为这个功能准备的
- 或者说更上一层楼，在侧边栏显示多个账户，这样的话就没有多个图标碍眼啦

**Comment by Icalinguaplusplus** [comment]
使用 `-c` 指定配置文件即可多開（不過 Electron 多開可能有小 BUG）
