### ISSUE TITLE
[BUG]接收到长语音会崩溃并且所有语音都下载失败

### ISSUE THREAD

**Issue by ArsiIksait** [Icalingua-plus-plus/Icalingua-plus-plus#202]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

我在手机上发送了一段3分钟的语音后Icalingua++就无响应崩溃了(

**To Reproduce / 复现过程**

手机和Icalingua++在同一群内时，用手机发送长语音时长超过1分30秒后会卡一会，然后超过这个时长就会需要等待更长的时间，就会导致崩溃。

还有平时接收到语音后也会下载失败。

**Expected behavior / 预期的结果**

无响应崩溃

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

![image](https://user-images.githubusercontent.com/63351011/179782735-54d7f099-fe61-4f11-b16c-28dace7a3f6a.png)

![image](https://user-images.githubusercontent.com/63351011/179780779-3ac0c108-4139-4632-a5e9-e72e74be9ce1.png)

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]

![image](https://user-images.githubusercontent.com/63351011/179779304-54e1fb30-b72e-40e0-8fde-4e26466850b9.png)

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
無響應崩潰是因爲使用的版本過舊，新版本已解決
每次都顯示下載失敗是因爲系統中未安裝 ffmpeg

**Comment by ArsiIksait** [comment]
ok，谢谢！
