### ISSUE TITLE
[Feature Request]批量转发聊天记录如果还包含批量转发聊天记录无法正常显示

### ISSUE THREAD

**Issue by Andy-Lorre** [Icalingua-plus-plus/Icalingua-plus-plus#203]
现在不支持查看批量转发聊天记录里的批量转发聊天记录。
![Snipaste_2022-07-20_17-26-48](https://user-images.githubusercontent.com/18457757/179948039-9633421c-b97e-4e92-a1f7-a1c1ae25ed1d.png)

**Comment by Icalinguaplusplus** [comment]
5e94917
