### ISSUE TITLE
[win x64 BUG]获取历史信息时图片下方显示多余的[image]

### ISSUE THREAD

**Issue by tjw123hh** [Icalingua-plus-plus/Icalingua-plus-plus#205]
如标题所述
![image](https://user-images.githubusercontent.com/56749271/180173745-5393ccb7-f854-4003-8903-9182806d9c36.png)

**Comment by amtoaer** [comment]
使用最新的 2.6.6 版本，在 linux 有相同问题
![image](https://user-images.githubusercontent.com/32017007/184538679-eee114ed-aaa5-45d5-87fa-7e4226a2e40b.png)

**Comment by tjw123hh** [comment]
> 使用最新的 2.6.6 版本，在 linux 有相同问题
> ![image](https://user-images.githubusercontent.com/32017007/184538679-eee114ed-aaa5-45d5-87fa-7e4226a2e40b.png)
> 

我考虑重新发一个issue（忘记加bug tag了

**Comment by tjw123hh** [comment]
> 使用最新的 2.6.6 版本，在 linux 有相同问题
> ![image](https://user-images.githubusercontent.com/32017007/184538679-eee114ed-aaa5-45d5-87fa-7e4226a2e40b.png)
> 

新议题#242
