### ISSUE TITLE
[Feature Request]增加下载进度提示

### ISSUE THREAD

**Issue by KagaJiankui** [Icalingua-plus-plus/Icalingua-plus-plus#207]
下载群文件和聊天文件时没有下载进度提示，任务栏只能显示单个文件的下载进度，使用aria2下载时完全没有进度显示

希望增加一个类似VSCode悬浮通知的下载进度提示框，每个文件显示一个进度条，下载完成后关闭该提示

**Describe alternatives you've considered**
也可以在软件中直接嵌入一个ariaNg web页面，在web页面中管理所有下载

**Comment by guixin233** [comment]
下载的文件存在那里呢，之前下载完找不到
