### ISSUE TITLE
[BUG] 无法再次查看转发的消息

### ISSUE THREAD

**Issue by TimFang4162** [Icalingua-plus-plus/Icalingua-plus-plus#209]
**Describe the bug / 描述**

在Icalingua中
显示为`[Forward multiple messages]`
![image](https://user-images.githubusercontent.com/60050973/180373724-37ca4906-d7f8-4579-a743-684924d65796.png)
在qq官方客户端中（正常显示）
![image](https://user-images.githubusercontent.com/60050973/180373808-d04d3a9f-3905-4fa1-8425-8265745554d4.png)

**To Reproduce / 复现过程**

我不是很清楚我是如何触发的，大概是退出并重新打开Icalingua几次后转发的消息就会显示为这样

**System information / 系统信息**
 - OS: Windows10
 - Version 2.6.6

**Additional context / 附加信息**
如果大家有类似的情况，这里有一个临时的解决办法
右键无法查看的消息，复制代码，
![image](https://user-images.githubusercontent.com/60050973/180374730-e3281511-088e-46c8-ac10-576a2956e0fe.png)
在复制的内容中找到`m_resid`字段，复制值
![image](https://user-images.githubusercontent.com/60050973/180374456-5836cd2e-e0db-4962-a60c-02a0dc74d704.png)
然后打开`查看合并转发消息`，填入m_resid的值，就可以查看了
![image](https://user-images.githubusercontent.com/60050973/180374289-4babf0e7-c6cb-4472-97ce-452e39b5ad3e.png)

~~不过最简单的解决办法是用官方客户端看~~

**Comment by Icalinguaplusplus** [comment]
97a1679
