### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wangyijin209** [Icalingua-plus-plus/Icalingua-plus-plus#212]
**Describe the bug / 描述**
QQ突然登录不了，出现验证码提示框，完成验证后退出运行

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/85976497/180604784-ae77498f-bc4b-4fe2-9a90-657538cf1a09.png)

**System information / 系统信息**
 - OS: [manjaro]
![image](https://user-images.githubusercontent.com/85976497/180604814-6bfd8a69-8736-42a1-bd8b-744a7f6a7aa7.png)

**Additional context / 附加信息**
希望可以添加一个扫码登录

**Comment by Icalinguaplusplus** [comment]
不輸入密碼即為掃碼登錄
