### ISSUE TITLE
[Feature Request] Add new Face called "嗑到了"

### ISSUE THREAD

**Issue by ksharperd** [Icalingua-plus-plus/Icalingua-plus-plus#217]
![image](https://user-images.githubusercontent.com/45651732/181681687-a8eed5c3-3b52-47ce-927a-17a92761baec.png)

**Comment by Icalinguaplusplus** [comment]
似乎沒有新表情，能否在 Android 版 QQ 查看？

**Comment by ksharperd** [comment]
> 似乎沒有新表情，能否在 Android 版 QQ 查看？

可以,我附上截图
![Screenshot_20220729-121541_QQ.png](https://user-images.githubusercontent.com/45651732/181876838-a8b42307-ad7b-46fc-ab7e-4b39dd63ee8c.png)
