### ISSUE TITLE
[BUG] 登录存在风险时，无法登录

### ISSUE THREAD

**Issue by NobodyHere-rrr** [Icalingua-plus-plus/Icalingua-plus-plus#218]
**Describe the bug / 描述**
如果QQ号存在风险，则无法登录，并且不会触发手机端提示

**To Reproduce / 复现过程**
使用有风险的QQ号登录
**Expected behavior / 预期的结果**
点击“Login”按钮后，弹出验证码，完成后，手机弹出确认提示，在确认后即可登录
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
<img width="562" alt="截屏2022-07-31 10 45 22" src="https://user-images.githubusercontent.com/62543054/182007670-d904627e-0272-4b9f-a22c-488723fdcf3a.png">

**System information / 系统信息**
 - OS: macOS
 - Version: 12.4 Beta (21F5058e)

**Additional context / 附加信息**
顺带一提，我的密码长度为12，点击“Login”按钮后，密码长度变成了32（详见图，下图为点击前，截图一栏中是点击后）
<img width="562" alt="截屏2022-07-31 10 50 29" src="https://user-images.githubusercontent.com/62543054/182007742-4ef39a98-a0dc-41a7-a059-a8b6fb3dc946.png">

**Comment by aimerneige** [comment]
> 顺带一提，我的密码长度为12，点击“Login”按钮后，密码长度变成了32

没有记错这个是正常的。

**Comment by Vanilla-Yukirin** [comment]
我也遇到了。win10 v=2.6.5
<img width="341" alt="image" src="https://user-images.githubusercontent.com/51521470/182023697-4270f529-8672-4a1b-8fad-5b73467a7805.png">
但是奇怪的是，在ubuntu上我并没有遇到这样的情况.v<2.6.5（没有更新）

**Comment by HoratioShaw** [comment]
QQ风控啊，很玄学（

**Comment by heeler-deer** [comment]
不妨看看这个
[bug261](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/261#issuecomment-1225786207)

**Comment by Icalinguaplusplus** [comment]
MacOS 協議已暫時無法使用，建議先更換其他協議
