### ISSUE TITLE
消息发送失败能否不要清除输入框的内容, 或者提供重发的选项?

### ISSUE THREAD

**Issue by touchmii** [Icalingua-plus-plus/Icalingua-plus-plus#22]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
2.5.8 已更新
