### ISSUE TITLE
[Feature Request] 希望可以添加设置群精华消息功能

### ISSUE THREAD

**Issue by ESEAbsolute** [Icalingua-plus-plus/Icalingua-plus-plus#221]
**Is your feature request related to a problem? Please describe.**
Icalingua++ 无法设置群精华消息，无论是群主、管理员还是可以设置精华消息的群员。所以希望添加一个这个功能。

**Describe the solution you'd like**
若拥有设置精华消息的权限，则在右键菜单里显示一个设置精华消息的选项，若设置成功则提示设置成功。

**Additional context**
![WCX1MU)1 4AX{%BW0SVGG71](https://user-images.githubusercontent.com/56300237/182056014-3c161f62-44cd-4c8e-88e6-f5bc821f4845.png)
![image](https://user-images.githubusercontent.com/56300237/182056069-fe618d14-4187-4949-88a2-d0288f7aea0a.png)

**Comment by aimerneige** [comment]
oicq 协议没有支持吧

**Comment by ESEAbsolute** [comment]
> oicq 协议没有支持吧

我看到 QQ 有这个 API 啊（）到底可以实现吗）

https://bot.q.qq.com/wiki/develop/nodesdk/pins_message/put_pins_message.html

**Comment by aimerneige** [comment]
本项目是调用的 oicq 作为后端接口。

**Comment by ForkKILLET** [comment]
> 本项目是调用的 oicq 作为后端接口。

也有用到 webapi 啊

**Comment by aimerneige** [comment]
Yes, you are right. Pull request is welcome.

**Comment by xiaoyv404** [comment]
> > 本项目是调用的 oicq 作为后端接口。
> 
> 也有用到 webapi 啊

但是这个API需要：
![image](https://user-images.githubusercontent.com/63290381/187016112-b894fedc-b233-4e4f-83f6-30098fb6a159.png)
啊（

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/7e709a7c9e84bb893454470e15b9f97565298e34
