### ISSUE TITLE
[BUG] 修改系统时间后会影响消息显示

### ISSUE THREAD

**Issue by aimerneige** [Icalingua-plus-plus/Icalingua-plus-plus#222]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

修改系统时间到未来后发送消息，消息会一直显示在最下面

**To Reproduce / 复现过程**

修改系统时间到未来，在任意对话中发送消息

**Expected behavior / 预期的结果**

历史消息不会因为修改系统时间而影响

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

![image](https://user-images.githubusercontent.com/51701792/182317503-06f8f4b1-6350-4d99-bdbe-e4eb99d36799.png)

**System information / 系统信息**
 - OS: [Fedora 36 x86_64]
 - Version [2.6.6]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

也不能全算 bug 吧，毕竟这个行为太奇怪了，如果有好的办法记录准确时间会很好。

**Comment by Icalinguaplusplus** [comment]
本地時間差太多應該也沒有什麽辦法（

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/c4333046a9500633430ad88c64f6a5944862df45
