### ISSUE TITLE
[BUG]正常登陆的账号提示登陆滑块验证，成功后不能正常进入应用

### ISSUE THREAD

**Issue by FreeDivers** [Icalingua-plus-plus/Icalingua-plus-plus#224]
如题

**Comment by woshishabii** [comment]
出现同样问题，2.6.5升级至2.6.6后仍出现问题

**Comment by sheepbox8646** [comment]
我用着用着也变成这样了

**Comment by freeze-dolphin** [comment]
同，然后我把 `~/.config/icalligua` 目录备份后删掉 (ical 的配置文件) 再启动 ical
此时登录也会提示滑块，但是我登录成功了

ps 我试了两次才登录成功

**Comment by FreeDivers** [comment]
谢谢，我去试试看

**Comment by sheepbox8646** [comment]
> 同，然后我把 `~/.config/icalligua` 目录备份后删掉 (ical 的配置文件) 再启动 ical 此时登录也会提示滑块，但是我登录成功了
> 
> ps 我试了两次才登录成功

补充：删除的时候别删里面的data和database文件夹可以保留聊天记录
