### ISSUE TITLE
[Feature Request]请求增加多账号功能

### ISSUE THREAD

**Issue by tiger-forest** [Icalingua-plus-plus/Icalingua-plus-plus#228]
**Is your feature request related to a problem? Please describe.**
经常需要同时登录两个账号，希望增加多账号支持
**Describe the solution you'd like**
可以添加侧边栏、在头像地方设置选择不同账号的二级菜单或者设置两个独立的托盘菜单与窗口

**Comment by aimerneige** [comment]
duplicate #197
