### ISSUE TITLE
[BUG]语音显示为Audio

### ISSUE THREAD

**Issue by gqcdm** [Icalingua-plus-plus/Icalingua-plus-plus#23]
**Describe the bug / 描述**
如果未在icalingua++中第一时间接收到语音

**To Reproduce / 复现过程**
如果未在icalingua++中第一时间接收到语音

**Expected behavior / 预期的结果**
显示语音播放器

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/78142321/158802332-b0337ffc-30a5-47ef-a8bd-1b30745cf9c7.png)
**System information / 系统信息**
![image](https://user-images.githubusercontent.com/78142321/158802421-1bcfc55e-1453-43b7-a30b-f556ed19afd2.png)

**Additional context / 附加信息**

**Comment by Icalinguaplusplus** [comment]
感謝反饋，由於私聊消息 id 不受QQ服務器管理，oicq 獲取私聊消息歷史消息返回的 audio 無URL，無法進行轉換，暫時無法修復。

**Comment by Icalinguaplusplus** [comment]
如果希望可以一直接收消息，建議在服務器上搭建使用 bridge。（部分功能相較本地版會有減少）
