### ISSUE TITLE
经常闪退（可能是自身原因，应该不是bug）

### ISSUE THREAD

**Issue by dying084** [Icalingua-plus-plus/Icalingua-plus-plus#233]
系统：ubuntu22.04 gnome42.2
CPU：i9-12900H
GPU：NVIDIA 3070
在安装显卡驱动，gnome更新至42.2后出现闪退，具体为约3分钟闪退一次（gnome42.1表现正常）
希望有大佬解决

**Comment by Icalinguaplusplus** [comment]
禁用硬件加速 `icalingua --dha`
