### ISSUE TITLE
[BUG]有被盗风险 ， 一登陆就弹掉 ， 让改密码

### ISSUE THREAD

**Issue by Mr54233** [Icalingua-plus-plus/Icalingua-plus-plus#234]
**Describe the bug / 描述**
一在这边登陆手机上就掉登录 ， 弹出有被盗风险要改密码 ， 然后就只能改密码

**To Reproduce / 复现过程**
登录即可

**Expected behavior / 预期的结果**
成功登录

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]
win10 

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
只能先用官方qq了 ， 希望是我账号的问题

**Comment by aimerneige** [comment]
这个主要原因是腾讯的风控，可以尝试电脑使用与手机相同的网络（比如相同的 wifi），这样比较容易过认证。

**Comment by Mr54233** [comment]
我才发现我的qq请求了十多次登录 ，怪不得会报风控 ， 希望能加一个尝试次数 ， 过多应该也会造成风控

**Comment by Mr54233** [comment]
过了风控就可以登录了
