### ISSUE TITLE
[BUG] 验证后自动关闭

### ISSUE THREAD

**Issue by HydroGest** [Icalingua-plus-plus/Icalingua-plus-plus#236]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
验证后自动结束进程。
```
[25834:0812/082314.635520:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
```
**To Reproduce / 复现过程**
登录即可
**Expected behavior / 预期的结果**
登陆QQ
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: Ubuntu
 - Version 22.04 LTS

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by PackageInstaller** [comment]
我也有这个问题，滑动验证后没反应，看了下进程，自动结束了
