### ISSUE TITLE
[Feature Request]更换图标

### ISSUE THREAD

**Issue by Zpcin** [Icalingua-plus-plus/Icalingua-plus-plus#237]
**Is your feature request related to a problem? Please describe.**
图标显示效果不佳
**Describe the solution you'd like**
使用此图标替换![512x512](https://user-images.githubusercontent.com/62590508/184273709-e97f229f-85eb-4939-9d83-a44fa82b1aa1.png)
**Describe alternatives you've considered**
![QQ_Image_1660268230728](https://user-images.githubusercontent.com/62590508/184270437-f78a81d9-3cd0-4b58-a200-a24939eeec6e.jpg)还考虑过这个

**Comment by Icalinguaplusplus** [comment]
抱歉根據[投票結果](https://t.me/Icalinguapp/1026)暫時不更換圖標，感謝為圖標所做的設計工作
