### ISSUE TITLE
[BUG] 屏蔽群消息没有解除屏蔽的设置

### ISSUE THREAD

**Issue by Polyisoprene** [Icalingua-plus-plus/Icalingua-plus-plus#239]
**Describe the bug / 描述**

在某个群上面右击，选择屏蔽消息，之后就接收不到这个群的消息了，而且没有解除屏蔽的选项，
只能手动的选择获取历史消息来更新消息

**To Reproduce / 复现过程**

在某个群上右键单击，选择屏蔽消息

**Expected behavior / 预期的结果**

希望有一个解除屏蔽的按钮或者选项

**System information / 系统信息**
 - OS: [Ubuntu Linux]
 - Version [22.04]

**Comment by dmlgzs** [comment]
选项菜单里面就有管理屏蔽会话吧
