### ISSUE TITLE
[Feature Request]能否指定某些群或者个人的获取历史消息优先级更高

### ISSUE THREAD

**Issue by Mr54233** [Icalingua-plus-plus/Icalingua-plus-plus#240]
**Is your feature request related to a problem? Please describe.**
#234  之后 , 用了几天官方版本之后就又可以登陆了 , 然而发现就几天短短时间没同步的消息就很多了 , 启动之后自动同步消息的功能有点卡顿了, 有的时候甚至会卡死整个软件.

**Describe the solution you'd like**
能否指定某些群或者联系人拉取消息的优先级更高 , 可以优先同步消息 , 并且指定这些群或者个人可以拉取所有信息 , 其他不怎么看的群就拉取80条或者由用户自己设置拉取条数.

**Comment by xiaozhangup** [comment]
确实，现在的icalingua的聊天room切换速度会随着消息越多越来越慢。
我现在差不多点一下十几秒后才会完成切换（但软件不会卡,圆圈一直转罢了）

**Comment by Icalinguaplusplus** [comment]
> 确实，现在的icalingua的聊天room切换速度会随着消息越多越来越慢。 我现在差不多点一下十几秒后才会完成切换（但软件不会卡,圆圈一直转罢了）

切換時數據庫掃全表導致的卡頓的問題已解決
