### ISSUE TITLE
有没有机会见到icalingua++使用oicq2[Feature Request]

### ISSUE THREAD

**Issue by xiaozhangup** [Icalingua-plus-plus/Icalingua-plus-plus#241]
2有很多的好用功能，并且可以填充1的协议不足
升级到2吧，求求了

**Comment by aimerneige** [comment]
pr welcome (雾

**Comment by xiaozhangup** [comment]
> pr welcome (雾

我不会icalingua的编写语言 (苦

**Comment by BeiyanYunyi** [comment]
会有的，等这轮重构完成以后。预期目标：前端改 Vue3、后端换 oicq2

**Comment by xiaozhangup** [comment]
> 会有的，等这轮重构完成以后。预期目标：前端改 Vue3、后端换 oicq2

好家伙，这轮重构
