### ISSUE TITLE
[BUG]消息排序错误（Ver 2.4.5）

### ISSUE THREAD

**Issue by bcegkmqs23** [Icalingua-plus-plus/Icalingua-plus-plus#25]
**Describe the bug / 描述**
若非常快地回复对方的消息，之后回过头来看消息的时候，会发现双方的消息顺序反了。

**System information / 系统信息**
 - OS: 5.15.11-gentoo
 - Version 2.4.5

**Comment by Icalinguaplusplus** [comment]
請給出同網絡環境下 Icalingua++、PCQQ、手機 QQ 對比的截圖，謝謝
出現這種情況很大概率是網絡問題，一般與軟件無關

**Comment by bcegkmqs23** [comment]
> 請給出同網絡環境下 Icalingua++、PCQQ、手機 QQ 對比的截圖，謝謝

![1](https://user-images.githubusercontent.com/54806479/158997014-c7e029f3-28e1-451b-ba21-3f5cad4a4980.jpg)
![Screenshot_20220318_113412](https://user-images.githubusercontent.com/54806479/158996271-3db93338-4c53-4c7e-a037-179f307fcb48.png)

不是孤例，至少有三次，但由于有部分消息手机上没有收到（聊天的时候没开手机QQ），所以对比不了了。

> 出現這種情況很大概率是網絡問題，一般與軟件無關

我聊天的时候，我的新回复是正确显示在对方发言的下方的，但如果之后回来看顺序就不对了。网络问题为什么会影响消息的排序？可能是渲染正确，但数据库存取错误。

**Comment by Icalinguaplusplus** [comment]
剛才看了下，取出消息時排序是按照時間戳順序的，應該是兩個消息時間戳相同，導致取出消息時順序不可控，以現在的數據庫的屎山代碼，短時間無法解決。
請右鍵復製 ID，在 `~/.config/icalingua/database/eqqxxx.db` 中的數據庫裏搜索兩個消息的 ID，查看 time 字段是否一致。

**Comment by Icalinguaplusplus** [comment]
請右鍵復製 ID，在 `~/.config/icalingua/database/eqqxxx.db` 中的數據庫裏搜索兩個消息的 ID，查看 time 字段是否一致。

**Comment by bcegkmqs23** [comment]
> 剛才看了下，取出消息時排序是按照時間戳順序的，應該是兩個消息時間戳相同，導致取出消息時順序不可控，以現在的數據庫的屎山代碼，短時間無法解決。 請右鍵復製 ID，在 `~/.config/icalingua/database/eqqxxx.db` 中的數據庫裏搜索兩個消息的 ID，查看 time 字段是否一致。
```
{"怎么样了", 1647345192000}
{"我基本没考虑", 1647345191622}
```

**Comment by bcegkmqs23** [comment]
可以看到时间戳就是反的。

**Comment by Icalinguaplusplus** [comment]
收到的私聊消息使用的是服務器的時間戳，而發出的私聊消息使用的是本地的時間戳，時間戳不正確的原因是你本地時間的問題，請校準本地時間

**Comment by bcegkmqs23** [comment]
> 收到的私聊消息使用的是服務器的時間戳，而發出的私聊消息使用的是本地的時間戳，時間戳不正確的原因是你本地時間的問題，請校準本地時間

这一点可能性我倒是有想到，不过程序一致地采用服务器时间的难度大么

**Comment by Icalinguaplusplus** [comment]
> > 收到的私聊消息使用的是服務器的時間戳，而發出的私聊消息使用的是本地的時間戳，時間戳不正確的原因是你本地時間的問題，請校準本地時間
> 
> 这一点可能性我倒是有想到，不过程序一致地采用服务器时间的难度大么

~~現在用上了~~

**Comment by bcegkmqs23** [comment]
那就好，这下我有更新的理由了。
之前无论我怎么校准时间，都无法消除那个问题，现在试试。
