### ISSUE TITLE
查看嵌套的转发多条消息

### ISSUE THREAD

**Issue by heptarri** [Icalingua-plus-plus/Icalingua-plus-plus#250]
**Is your feature request related to a problem? Please describe.**

当对方合并转发多条消息时，其转发消息中的“转发多条消息”无法显示。

**Describe the solution you'd like**
类似递归的形式，实现同第一层转发中的 "View Forwarded Messaeges" 效果。

**Describe alternatives you've considered**

**Additional context**

**Comment by Icalinguaplusplus** [comment]
5e94917
