### ISSUE TITLE
通过群号添加群功能

### ISSUE THREAD

**Issue by heptarri** [Icalingua-plus-plus/Icalingua-plus-plus#251]
**Is your feature request related to a problem? Please describe.**
不可以通过Icalingua++搜索群号并加群或搜索qq号添加好友。
**Describe the solution you'd like**
在左上角搜索框中添加相关功能，实现通过群号加入群和通过搜索qq号添加好友。
**Describe alternatives you've considered**

**Additional context**

**Comment by aimerneige** [comment]
主动添加好友的功能会被恶意利用，相关协议 oicq 拒绝实现，详见：

https://github.com/takayama-lily/oicq/issues/365

**Comment by bcegkmqs23** [comment]
虽然遗憾，倒是意料之中。
