### ISSUE TITLE
KDE下主题不随系统改变而改变

### ISSUE THREAD

**Issue by heptarri** [Icalingua-plus-plus/Icalingua-plus-plus#252]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
当KDE切换主题时且Icalingua++开启“跟随系统”时，icalingua++的亮暗不随KDE主题的变换而变换

**To Reproduce / 复现过程**
1. Icalingua++选择“主题->跟随系统”  
2. 在KDE“外观”中切换暗色模式
**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: Arch Linux
 - Version 2.1.4

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
嘗試新版本 Electron 或許可以解決
