### ISSUE TITLE
[BUG]闪照功能失效不能保护隐私

### ISSUE THREAD

**Issue by A-moment096** [Icalingua-plus-plus/Icalingua-plus-plus#254]
**Describe the bug / 描述**

用户自己发出的闪照和他人发出的闪照没有原QQ客户端的效果，和普通图片一样可以浏览和下载，没有浏览时长限制
登录使用的Protocol是Android Pad，没有尝试过其他的登录，Icalingua++版本是2.6.6
**To Reproduce / 复现过程**
尝试和好友之间和在群聊中通过用手机发送闪照，在Icalingua++中打开后和普通图片除不能一眼看到图片内容外没有区别，在点开图片之后仍然可以进行下载和浏览等操作
**Expected behavior / 预期的结果**
希望能实现和手机看闪照一样的效果或者直接禁用闪照
**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/65579757/185753603-8ce3b329-665c-40ec-a080-84980081a746.png)
上面是没有点开的时候
![image](https://user-images.githubusercontent.com/65579757/185753650-4c9daa07-a1e9-42dc-b1b1-e3dffffd13e7.png)
上面是点开之后，和普通图片没有区别，可以下载且没有时长限制
群聊和私聊都是这样的效果，别人发和自己发都一样
**System information / 系统信息**
 - OS: Windows 10 Pro
 - Version 21H2

**Comment by aimerneige** [comment]
你可以不用啊

**Comment by DesolateYH** [comment]
有没有一种可能，这不是bug，是特性

**Comment by vegetabledog-x86** [comment]
QQ的闪照本来就很拉胯，发送闪照的时候把文件和密钥一起发送出去，形同虚设，用QAuxiliary模块破解闪照也和这种效果是一样的，与其指望客户端实现销毁不如自己发信息之前谨慎，信息都是从自己手里泄露出去的

**Comment by bcegkmqs23** [comment]
唯一保护信息的方式就是不要发出去。
