### ISSUE TITLE
[BUG]扫码验证没有二维码出现

### ISSUE THREAD

**Issue by a15355447898a** [Icalingua-plus-plus/Icalingua-plus-plus#256]
**Describe the bug / 描述**
扫码验证的时候没有二维码出现

**To Reproduce / 复现过程**
qq号设备异常登陆?

**Expected behavior / 预期的结果**
有个二维码出现让我扫码

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/62456287/186041535-b608ea93-19e2-4eb3-900a-f805ee4f2b66.png)

**System information / 系统信息**
 - OS: opensuse 15.4
 - Version 2.6.6

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by mrcaidev** [comment]
同样问题。

- OS: Arch
- Version 2.6.7

**Comment by cui8** [comment]
今天刚用这个，用着很好。刚开始我用qq号与密码登录，也是这个问题，试了好多次，然后提示存在风险，让手机号或扫码登陆，最后我扫码登陆成功了

**Comment by mrcaidev** [comment]
> 同样问题。
> 
> * OS: Arch
> * Version 2.6.7

解决了，删掉配置文件，重装，协议选择apad

**Comment by cui8** [comment]
> 

配置文件在哪

**Comment by a15355447898a** [comment]
> > 
> 
> 配置文件在哪

~/.config下面

**Comment by cui8** [comment]
> > > 
> > 
> > 
> > 配置文件在哪
> 
> ~/.config下面

[![wa1yr.png](https://s1.328888.xyz/2022/08/24/wa1yr.png)](https://imgloc.com/i/wa1yr)
是这个位置吗，怎么没有

**Comment by a15355447898a** [comment]
> > > > 
> > > 
> > > 
> > > 配置文件在哪
> > 
> > 
> > ~/.config下面
> 
> [![wa1yr.png](https://camo.githubusercontent.com/752bdd835ffdb39a53804c43b6ed47ffa9203b2aa33a8383ffd9815387cb2dd7/68747470733a2f2f73312e3332383838382e78797a2f323032322f30382f32342f77613179722e706e67)](https://imgloc.com/i/wa1yr) 是这个位置吗，怎么没有

我不知道windows怎么放的,请教下别人吧
或者用everything找一下`icalingua`文件夹

**Comment by cui8** [comment]
> 

[![watAp.png](https://s1.328888.xyz/2022/08/24/wa8vn.png)](https://imgloc.com/i/watAp)
[![watAp.png](https://s1.328888.xyz/2022/08/24/watAp.png)](https://imgloc.com/i/watAp)

是这个吗？

**Comment by a15355447898a** [comment]
> > 
> 
> [![watAp.png](https://camo.githubusercontent.com/dab8d3e174e77fc7b25aa1135f423bf8c8629a5419315c3e8a5c6e2df8525b33/68747470733a2f2f73312e3332383838382e78797a2f323032322f30382f32342f776138766e2e706e67)](https://imgloc.com/i/watAp) [![watAp.png](https://camo.githubusercontent.com/4b60a8acd6e2b6c6040a5e100ca5165ab1e44fce3b66b98c943c20f04a21978c/68747470733a2f2f73312e3332383838382e78797a2f323032322f30382f32342f77617441702e706e67)](https://imgloc.com/i/watAp)
> 
> 是这个吗？

你试试整个文件夹全删了？

**Comment by cui8** [comment]
> > > 
> > 
> > 
> > [![watAp.png](https://camo.githubusercontent.com/dab8d3e174e77fc7b25aa1135f423bf8c8629a5419315c3e8a5c6e2df8525b33/68747470733a2f2f73312e3332383838382e78797a2f323032322f30382f32342f776138766e2e706e67)](https://imgloc.com/i/watAp) [![watAp.png](https://camo.githubusercontent.com/4b60a8acd6e2b6c6040a5e100ca5165ab1e44fce3b66b98c943c20f04a21978c/68747470733a2f2f73312e3332383838382e78797a2f323032322f30382f32342f77617441702e706e67)](https://imgloc.com/i/watAp)
> > 是这个吗？
> 
> 你试试整个文件夹全删了？

[![watAp.png](https://s1.328888.xyz/2022/08/24/watAp.png)](https://imgloc.com/i/watAp)[![w1LuF.png](https://s1.328888.xyz/2022/08/24/w1LuF.png)](https://imgloc.com/i/w1LuF)
删除后，重新打开软件，还是这样

**Comment by 1human** [comment]
> 
> 你试试整个文件夹全删了？

感谢。。。我这边删了之后MacOS还是报错，apad和ipad可以

**Comment by Mr54233** [comment]
我也是这个报错 , 点开来没得选 , config文件找不到啊

**Comment by Mr54233** [comment]
C:\Users\用户名\AppData\Roaming\icalingua
win在这个地方有个config.yaml文件 , 删掉重新登录也登不上啊qwq

**Comment by zzttzzmyswy** [comment]
我也发生这个问题了

应用程序安装源 AUR
应用程序版本(AUR) 2.7.1-1

这里有一个解决办法：在手机qq里面的设置下的账号安全下的登陆设备管理中关闭陌生设备登陆保护即可，不过这个不是一个很好的解决办法

------------------
新增后续：可以在关闭陌生设备登陆保护后成功登陆后再此开启陌生设备登陆保护，这样之前登陆的设备仍然可以登陆，不需要扫码验证

**Comment by FramHerel** [comment]
我也是这个问题

**Comment by hardtokeepmind** [comment]
OS：Ubuntu
Version:22.04.1 LTS
Solution:在手机qq关闭登陆验证等一系列安全检测 使用apad协议 用手机开热点给电脑共享，然后登陆

**Comment by Icalinguaplusplus** [comment]
已增加短信驗證
