### ISSUE TITLE
_x64.exe在win10上是否可以修改css

### ISSUE THREAD

**Issue by LuoTianHua** [Icalingua-plus-plus/Icalingua-plus-plus#259]
之前closed问题中提到了 linux和mac 上都可以修改css，但是windows上没有找到可以修改的文件，似乎被打包到app.asar文件中了？

**Comment by 204065248** [comment]
希望可以自己做主题啊

**Comment by LuoTianHua** [comment]
> 之前closed问题中提到了 linux和mac 上都可以修改css，但是windows上没有找到可以修改的文件，似乎被打包到app.asar文件中了？

尝试解包后 修改css  无效

**Comment by MoXuanSun** [comment]
windows下在users/你的用户名/AppData/Roaming/icalingua/下创建一个style.css文件，在里面写之后保存再重新加载即可
