### ISSUE TITLE
[BUG]当前版本qq过低

### ISSUE THREAD

**Issue by heeler-deer** [Icalingua-plus-plus/Icalingua-plus-plus#261]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
打开icalingua,显示当前版本qq过低，请下载

**To Reproduce / 复现过程**
打开icalingua即可
**Expected behavior / 预期的结果**
自动登陆
**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/74958018/186435402-578b2ebc-4989-4bd4-8912-25af4c3c1a8f.png)

If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [e.g. Arch Linux]  ubuntu22.04 LTS
 - Version [e.g. 2.1.4]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

下午正常使用，晚上突然不能。猜测tx作了防护

**Comment by AFLeartLey** [comment]
windows10 20H2 遇到同样问题

**Comment by DesolateYH** [comment]
Debian 遇到同样问题

**Comment by heeler-deer** [comment]
OK我知道了，大概是macos使用密码登陆时遇到问题，可以参考：
[bug247](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/247)
以及
[bug256](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/256)


我的解决办法：
linux下，找到对应的config,由于我在一般用户模式下使用，因此我找到~/.config/icalingua文件夹删去即可。
由于文件夹内可能仍有数据，我使用

```
sudo rm -rf ~/.config/icalingua   
```


 删去文件夹后即可以令icalingua的启动页面未默认填充上次的登陆选项，如帐号，密码，登陆设备等，

之后重新安装icalingua,如果仍然希望使用macos登陆，则需要通过扫码登陆。
其余登陆方式未尝试。


我将关闭该issue

**Comment by Xicrosoft** [comment]
macOS Ventura 13.0 β
Windows 11 企业版
两个系统同时出现本问题

**Comment by heeler-deer** [comment]
我认为选择macos作为登陆设备同时使用密码登陆时容易出现问题，参考之前的登陆issue
