### ISSUE TITLE
登录提示“QQ版本号过低”[BUG]

### ISSUE THREAD

**Issue by yeeyuechen** [Icalingua-plus-plus/Icalingua-plus-plus#263]
**Describe the bug**
在我使用icalingua登录QQ时，在登录界面的下方出现了“[温馨提示]当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面“的红色字样
**A clear and concise description of what the bug is.**
无法登录自己的账户

**To Reproduce**
当我打开软件登录时，账户和密码没有任何问题，但是当我按下Enter键时，页面的下方出现了红字，提示版本过低，无法登录

**Expected behavior**
成功登陆并正常聊天

**Screenshots**
![PHOTO](https://cn-img.owoser.cn/images/2022/08/25/de6a77ff7d8aa1a3f303995f4fb0d1d5.png)

**System information**
 - OS: [Ubuntu Linux]
 - Version [LTS 22.04]

**Additional context**
none

**Comment by yeeyuechen** [comment]
**更正**
在“System information”中，OS与Version填写错误了，应该是：

- OS:[Ubuntu Linux LTS 22.04]
- Version:[icalingua v2.6.7_amd64]

**Comment by yishuiwang** [comment]
参考历史[issue](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/247)
