### ISSUE TITLE
[BUG] 打字卡顿

### ISSUE THREAD

**Issue by barryblueice** [Icalingua-plus-plus/Icalingua-plus-plus#264]
系统xubuntu 22.04，输入法ibus拼音，打字要响应很久，好几台电脑都是这样

**Comment by UlyssesZh** [comment]
我也发现了这个现象, 一般发生在浏览历史消息的时候. 跳转到聊天记录底部后能正常打字.
Ubuntu 20.04, 输入法为 ibus-rime.
