### ISSUE TITLE
[BUG] 2.6.8 源码无缓存构建失败

### ISSUE THREAD

**Issue by arenekosreal** [Icalingua-plus-plus/Icalingua-plus-plus#266]
**Describe the bug / 描述**
使用最新 [2.6.8](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/tree/v2.6.8) 源码无缓存构建失败

**To Reproduce / 复现过程**
使用 AUR 的 [icalingua++-git](https://aur.archlinux.org/packages/icalingua++-git) 软件包尝试从源代码完成构建

**Expected behavior / 预期的结果**
成功完成构建

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/17194552/186588031-5e628f38-6c20-4537-b240-eed29e0ce4c7.png)

**System information / 系统信息**
 - OS: Arch Linux
 - Version 2.6.8

**Additional context / 附加信息**
无

**Comment by arenekosreal** [comment]
在 `package.json` 将 icalingua 的依赖从 2.6.7 改为 2.6.8 并同步 `pnpm-lock.yaml` 即可修正

**Comment by Icalinguaplusplus** [comment]
已改
