### ISSUE TITLE
[BUG] 使用了错误的显示服务器

### ISSUE THREAD

**Issue by FHU-yezi** [Icalingua-plus-plus/Icalingua-plus-plus#269]
**Describe the bug / 描述**
在某种情况下，该程序会尝试使用 Wayland 显示服务器，但当前图形环境为 X11,因此导致启动失败，现象为尝试启动后无任何反应。

**To Reproduce / 复现过程**
在 AUR 上下载最新的安装包（2.6.8-1），安装后尝试启动程序。

**Expected behavior / 预期的结果**
程序正常启动并展示登录界面。

**Error behavior / 错误表现**
尝试启动程序无任何反应，htop 中可观察到程序相关进程创建后销毁，在命令行中有如下输出：

```
➜  ~ icalingua
[41391:0825/201132.496714:ERROR:wayland_connection.cc(214)] Failed to connect to Wayland display
[41391:0825/201132.496755:ERROR:ozone_platform_wayland.cc(227)] Failed to initialize Wayland platform
[41391:0825/201132.496758:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
/usr/bin/icalingua：行 2: 41391 已放弃               （核心已转储）electron /usr/lib/icalingua/icalingua.asar "$@"
```

手动下载 GitHub 上的最新版本软件包（2.6.8-2）并安装，无此故障出现，已自行删除软件创建的配置文件与缓存，排除因文件残留可能导致的问题。

安装 GitHub 上的软件包后，使用 `yay -Syyu` 更新全部软件包时会收到如下警告，证实 GitHub 上的版本比 AUR 更新：

```
➜  ~ yay -Syyu
[sudo] yezi 的密码：
:: 正在同步软件包数据库...
 core                            165.3 KiB  53.3 KiB/s 00:03 [################################] 100%
 extra                          1849.1 KiB   236 KiB/s 00:08 [################################] 100%
 community                         7.1 MiB   708 KiB/s 00:10 [################################] 100%
 multilib                        180.5 KiB  50.8 KiB/s 00:04 [################################] 100%
:: 正在进行全面系统更新...
 今日无事可做
:: 搜索数据库以获取更新...
:: 搜索 AUR 以获取更新...
 -> icalingua++: 本地 (2.6.8-2) 比 AUR (2.6.8-1) 更新
```

**System information / 系统信息**
 - OS: Manjaro with KDE desktop enviroment
 - Version: All packages is up to date (stable branch)
 - Display Server: X11
 - An Intel integrated graphics card and a NVIDIA graphics card

**Additional context / 附加信息**

Update the package on AUR should fix this problem.

**Comment by FHU-yezi** [comment]
Just installed the AUR package update, and got the same error.

Maybe there are something wrong in the build file.

**Comment by Icalinguaplusplus** [comment]
這個應該和 Electron 有關
Release 中使用 Electron 17，AUR 的則使用最新版

**Comment by FHU-yezi** [comment]
> 這個應該和 Electron 有關
> Release 中使用 Electron 17，AUR 的則使用最新版

有办法让软件把参数传递给 Election 吗？如果有的话可以通过参数强制 Election 使用 X11。

**Comment by FHU-yezi** [comment]
I messed the electron flags up. I try to use the Wayland Display Server before, and created a file called `electron-flags.txt` with some args to force electron apps to use Wayland.

If someone ran into the same problem, try to search `electron-flags.txt` in `~/.config` dir.
