### ISSUE TITLE
[上游 oicq bug] macOS 协议无法登陆

### ISSUE THREAD

**Issue by chiyuki0325** [Icalingua-plus-plus/Icalingua-plus-plus#270]
不知道该反馈到这里，还是原 oicq 仓库 ...
![图片](https://user-images.githubusercontent.com/73830635/186818927-ad10f188-cda6-4388-b8cc-bd664f2ddf58.png)
版本: 2.6.8

**Comment by dongdigua** [comment]
+1

**Comment by fansuregrin** [comment]
I also have the same issue.

**Comment by dingiso** [comment]
好像不只是 macos ，我的只要是用密码登录都是返回这个信息

**Comment by fansuregrin** [comment]
> 好像不只是 macos ，我的只要是用密码登录都是返回这个信息

I changed to iPad protocol, it works well.

**Comment by goodspeed34** [comment]
duplicate #247
