### ISSUE TITLE
[Feature Request] Switch to Tauri?

### ISSUE THREAD

**Issue by WhiredPlanck** [Icalingua-plus-plus/Icalingua-plus-plus#273]
**Is your feature request related to a problem? Please describe.**
No. But as we all know, Electron is just like a proprietary web browser for an application, it's a heavy solution. So ... 

**Describe the solution you'd like**
Switch Icalingua to Tauri.

**Comment by aimerneige** [comment]
tauri 与 electron 是完全不同的俩个框架，如果真要写的话可以新开一个仓库了。

**Comment by WhiredPlanck** [comment]
> tauri 与 electron 是完全不同的俩个框架，如果真要写的话可以新开一个仓库了。

差别这么大的吗 :joy:  …… 我还不是很了解这两个技术的细节

**Comment by aimerneige** [comment]
electron 使用 JavaScript 或 TypeScript 而 Tauri 使用 Rust

WhiredPlanck ***@***.***> 于 2022年8月28日周日 下午12:53写道：

**Comment by so1ve** [comment]
没有什么必要……就怕到时候webview在不同平台上出问题
