### ISSUE TITLE
[BUG][语音下载失败]undefined

### ISSUE THREAD

**Issue by HoratioShaw** [Icalingua-plus-plus/Icalingua-plus-plus#278]
**Describe the bug / 描述**
[语音下载失败]undefined

**To Reproduce / 复现过程**
已安装ffmpeg
**Expected behavior / 预期的结果**
正常使用
**Screenshots / 截图**
![图片](https://user-images.githubusercontent.com/72498396/187352043-151f6f4a-7290-416e-ae71-3f2bd81324b6.png)
![图片](https://user-images.githubusercontent.com/72498396/187352066-75cd8d17-4f53-4e0b-af96-82c61d2e288f.png)

**System information / 系统信息**
版本	Windows 11 专业版
版本	22H2
操作系统版本	22622.586

**Comment by Icalinguaplusplus** [comment]
自己賬號其他設備發送的私聊語音 oicq 是無法接收的
