### ISSUE TITLE
[BUG]撤回消息的一些bug

### ISSUE THREAD

**Issue by tjw123hh** [Icalingua-plus-plus/Icalingua-plus-plus#279]
**Describe the bug / 描述**
①撤回的消息显示后右键菜单中仍有“撤回”项且撤回后出现“Failed to delete message”提示
②删除群成员消息时的确认提示框没有适配深色模式
③“Failed to delete message”提示没有汉化且未适配深色模式

**To Reproduce / 复现过程**
撤回成员消息
尝试撤回显示后的已撤回消息

**Expected behavior / 预期的结果**
修复所有bug

**Screenshots / 截图**
![49693d17d8e460ed.png](https://user-images.githubusercontent.com/56749271/187623471-6307bc08-405d-41ea-a91f-9fee9456e673.png)
![62bc3827c0b5a736.png](https://user-images.githubusercontent.com/56749271/187623506-46ced6f2-f751-418b-a5dc-12c69bfc1315.png)

**System information / 系统信息**
 - OS: Kubuntu 22.04
 - Version 2.7.1

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/b2583a3d3a72f81ce9f2bf4fff1beeaa00c8c8a2
