### ISSUE TITLE
[Feature Request] 降低 release 频率

### ISSUE THREAD

**Issue by chiyuki0325** [Icalingua-plus-plus/Icalingua-plus-plus#28]
目前项目的 release 频率过高，基本每次 commit 就发布 release，对于 ArchLinux 之类滚动更新的发行版很不友好，建议降低 release 频率为一月一次，或有大更新的时候一次，想尝鲜的用户可以使用 Actions 内的开发版本。

**Comment by Icalinguaplusplus** [comment]
之後會降低頻率，感謝反饋
