### ISSUE TITLE
[Feature Request]通过qq号添加好友与通过群号加入群聊

### ISSUE THREAD

**Issue by tjw123hh** [Icalingua-plus-plus/Icalingua-plus-plus#281]
**Describe the solution you'd like**
在联系人界面新增“+”号按钮，点击搜索qq号添加好友或搜索群号添加群聊

**Additional context**
QQ的加好友验证可能很难做到

**Comment by aimerneige** [comment]
本功能已被标记为 `not planned`

详见 #251
