### ISSUE TITLE
[BUG]2.7.1在Windows10下无法使用

### ISSUE THREAD

**Issue by FrydenSoul** [Icalingua-plus-plus/Icalingua-plus-plus#284]
**Describe the bug / 描述**
Windows 2.7.1版本启动为白屏，除Dev Tools外均无内容显示

**To Reproduce / 复现过程**
启动

**Expected behavior / 预期的结果**

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/106534917/188252947-74ea87b8-8a0b-4a3b-8af1-1cdda6bb4dd7.png)

**System information / 系统信息**
 - OS: Windows
 - Version: Windows 10 LTSC 21H2

**Additional context / 附加信息**

**Comment by onexiaolaji** [comment]
同上+1

**Comment by weaksloth** [comment]
哈，windows还是投向老马的怀抱用官方的吧

**Comment by Icalinguaplusplus** [comment]
`Icalingua++.exe --dha`

**Comment by FrydenSoul** [comment]
> 哈，windows还是投向老马的怀抱用官方的吧

LinuxQQ做的就是一坨，当然用icalingua++
windows这次尝试一下
