### ISSUE TITLE
[BUG]登陆显示图片验证码，无法登陆使用

### ISSUE THREAD

**Issue by sseaan** [Icalingua-plus-plus/Icalingua-plus-plus#285]
**Describe the bug / 描述**
打开后显示图片验证码，验证完成后直接退出

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/77724796/188259993-d88c94f3-ad71-4c80-a7a7-ee7a75c3d41e.png)

**System information / 系统信息**
 - OS: Ubuntu Desktop arm64
 - Version 2.7.1

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Hentioe** [comment]
点编辑给这个 issue 添加上标题，否则他人从列表里不知道你想反馈什么。目前我这边在弹出验证码后被连续封号两次了，所以我建议当前不要使用 Icalingua++。腾讯不只是封杀软件，连用户的号都封，马化腾亲妈原地爆炸。

**Comment by onexiaolaji** [comment]
> 
+1

**Comment by Icalinguaplusplus** [comment]
請測試 development 是否存在同樣問題？
