### ISSUE TITLE
32位版本在缺少SSE3指令集的设备上无法运行

### ISSUE THREAD

**Issue by CaptinTi** [Icalingua-plus-plus/Icalingua-plus-plus#290]
平台：intel PM770
运行后提示“非法指令”，gdb显示引用了未知的指令集（推测引用了SSE3）。

希望能够完善32位支持，32位平台只有第三方一条路可以选了，但支持SSE3指令集的32位CPU实属罕见，希望大佬能给retro的旧平台一个机会。

**Comment by Neubulae** [comment]
这……建议是自己下载过来编译呀……源代码都是在的

**Comment by Icalinguaplusplus** [comment]
~~這個感覺應該要去問 Electron 團隊~~

**Comment by CaptinTi** [comment]
> 这……建议是自己下载过来编译呀……源代码都是在的



> ~這個感覺應該要去問 Electron 團隊~

目前咱们这个项目32位依赖的electron版本太高了，如果改成8.0及以下的版本，在缺少SSE3指令集的情况下是不会出问题的。

**Comment by CaptinTi** [comment]
> 这……建议是自己下载过来编译呀……源代码都是在的

尝试过自己编译，依然不成功，依旧提示非法指令。electron依赖的版本太高，本就不支持缺少SSE3指令集的平台。
但支持SS3指令集的32位平台只有英特尔酷睿2代的极少数的那几款，所以，目前在过高electron版本依赖的情况下，对iia32平台提供支持意义十分有限。

**Comment by dmlgzs** [comment]
估计你这也没办法了吧，32位都多早的东西了，已经被强制淘汰了
最新版 Electron 甚至已经不再支持32位系统了(

**Comment by dmlgzs** [comment]
另外 Electron 8.x 的 node.js 版本过低不支持 oicq，应该只能自行编译 Electron 和 node.js 试试了(
