### ISSUE TITLE
[BUG] 获取历史信息时自己发送的消息出现两次

### ISSUE THREAD

**Issue by HRiver2** [Icalingua-plus-plus/Icalingua-plus-plus#294]
**Describe the bug / 描述**

获取历史信息时自己发送的消息出现两次

**To Reproduce / 复现过程**

找一个聊天获取历史记录就基本会复现。

**Expected behavior / 预期的结果**

希望可以修复，应该是 2.7.2 更新后出的问题，可能是这次修获取历史的时候把这个改挂了，具体我不清楚（

**Screenshots / 截图**
![](https://pic.imgdb.cn/item/6319471916f2c2beb1bbbfd5.jpg)

**System information / 系统信息**
 - OS: Windows 11 22H2 Windows Feature Experience Pack 1000.22634.1000.0
 - Version: 2.7.2

**Additional context / 附加信息**
None.

**Comment by WAAutoMaton** [comment]
我在 2.7.2 以前的版本也会出现，感觉一直以来都有这个问题

**Comment by HRiver2** [comment]
> 我在 2.7.2 以前的版本也会出现，感觉一直以来都有这个问题

那就可能是历史问题了

**Comment by HRiver2** [comment]
> 我在 2.7.2 以前的版本也会出现，感觉一直以来都有这个问题

那就可能是历史问题了

**Comment by kands-code** [comment]
确实，我现在也偶尔会遇到这个问题

**Comment by vstar37** [comment]
这个问题在最新的版本上依旧存在

**Comment by Naitang1207** [comment]
现在10.22

**Comment by Naitang1207** [comment]
现在在2.7.5的Mac OS Monterey 12.6上bug依旧稳定复现
只要来回切换聊天窗口就会这样
