### ISSUE TITLE
[BUG]群内不接收某人消息相关问题

### ISSUE THREAD

**Issue by HoratioShaw** [Icalingua-plus-plus/Icalingua-plus-plus#296]
**Describe the bug / 描述**
在手机QQ设置群内不接受某人消息后，ica++处于登录状态时确实不会收到他的消息，但获取历史记录后会出现
**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**
获取历史记录后不出现

**System information / 系统信息**
版本	Windows 11 专业版
操作系统版本	22622.590
体验	Windows Feature Experience Pack 1000.22634.1000.0

**Comment by Icalinguaplusplus** [comment]
暫時無法獲取手機 QQ 設置的屏蔽列表，可使用 Icalingua++ 自帶屏蔽
