### ISSUE TITLE
[BUG]更新包名等信息

### ISSUE THREAD

**Issue by Hibanaw** [Icalingua-plus-plus/Icalingua-plus-plus#3]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
deb 包 control 文件仍为原版信息，且维护者邮箱指向原开发者
![图片](https://user-images.githubusercontent.com/61813396/156390072-af7088a2-c87b-4fd7-85d8-5e86fa6fa036.png)

软件名称/窗口标题仍为“icalingua”
![图片](https://user-images.githubusercontent.com/61813396/156390637-046f4c41-2607-4956-8104-4e36297c5df3.png)

**Expected behavior / 预期的结果**
将名称更新为“icalingua++”

**Comment by Icalinguaplusplus** [comment]
感謝建議，已在 dev 分支和2.5.3版本修改了應用程式名稱與作者信息，如果出現 BUG 歡迎繼續反饋。另外，為了保證對原版的兼容性，暫時不考慮修改包名。

**Comment by Hibanaw** [comment]
> 另外，為了保證對原版的兼容性，暫時不考慮修改包名。

deb 和 pkgbuild 可以设置 Conflicts 和 Replaces 项为 icalingua，其余的打包方式应该也有类似的条目
