### ISSUE TITLE
[BUG] 图片详情不能显示

### ISSUE THREAD

**Issue by ForkKILLET** [Icalingua-plus-plus/Icalingua-plus-plus#30]
**复现 / Reproduction**

从 AUR 升级到最新版本（icalingua-plus-plus 2.5.8-1），然后点开任意一张图片。

**截图 / Screenshot**

标题为疑似 base64 产生的乱码，内容全黑，底下一排按钮只剩下 `[1:1]`

![](https://user-images.githubusercontent.com/35412022/159102162-d35ddfaf-9ba0-4288-9a1f-8747fb64e97d.png)

**System information / 系统信息**
 - OS: Arch Linux
 - Version 5.15.29-1-lts

**Additional context / 附加信息**

和前 icalingua 最后一个版本表现类似。

**Comment by Icalinguaplusplus** [comment]
請提供日誌，謝謝

**Comment by fevrax** [comment]
重启后就可以看图片了

**Comment by ForkKILLET** [comment]
> 重启后就可以看图片了

啊，确实，谢谢
