### ISSUE TITLE
[BUG]群文件打开后只能下载点击的第一个文件

### ISSUE THREAD

**Issue by MALossov** [Icalingua-plus-plus/Icalingua-plus-plus#303]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
在打开群文件窗口之后，只能下载打开窗口后点击的第一个文件。
无论是否开启aria2下载都是这种状况。

**To Reproduce / 复现过程**
随便点开一个群之后点群文件下载，
发现点击列表多个文件后仅能下载一个。

**Expected behavior / 预期的结果**
能够下载点击后需要下载的所有文件。

**System information / 系统信息**
 - OS: Ubuntu
 - Version: 22.04.1

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
也许是我自己系统配置的问题？

**Comment by MALossov** [comment]
可以通过重复打开窗口下载多个文件。但是感觉没啥用。

**Comment by MALossov** [comment]
可以通过多次开启群文件窗口进行多文件下载。但是感觉略麻烦。

**Comment by xiaoyv404** [comment]
我也存在这个问题

**Comment by Seidko** [comment]
群文件网页前端的代码随着il存储库的删除一起寄了，要修也只能重写了 ~~（就作者这更新频率来看概率不大）~~，所以就这样吧  ~~（又不是不能用）~~

**Comment by Icalinguaplusplus** [comment]
fixed in development
