### ISSUE TITLE
随时遇到 “自定义插件出错”，但是不影响正常使用 [BUG]

### ISSUE THREAD

**Issue by jyi2ya** [Icalingua-plus-plus/Icalingua-plus-plus#305]
**Describe the bug / 描述**
页面上出现 “自定义插件出错” 的提示。但是我没有做过任何有关插件的设置。

**To Reproduce / 复现过程**
启动程序后随机地出现，在切换聊天窗口后出现概率似乎会增加。

**Expected behavior / 预期的结果**
页面上没有 “自定义插件出错” 的提示。

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://user-images.githubusercontent.com/86813521/190846316-675cb6dc-1dc9-40a6-b593-dea0d8d2769c.png)

**System information / 系统信息**
 - OS: Debian bookworm/sid 
 - Uname: Linux Syameimaru-Aya 5.19.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.6-1 (2022-09-01) x86_64 GNU/Linux
 - Version: 2.7.2

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

上一个使用的 icalingua 版本是 2.6.6，在那个版本里面没有出现类似的问题。

**Comment by dmlgzs** [comment]
这是自己开启了选项里的“启用插件”了吧

**Comment by jyi2ya** [comment]
> 这是自己开启了选项里的“启用插件”了吧

刚刚检查了一下发现是这样的，也许是之前打开但是后来忘掉了。:( 很抱歉打扰您了。
