### ISSUE TITLE
[BUG] 当消息换行符是 \r 时，无法正确显示换行

### ISSUE THREAD

**Issue by WAAutoMaton** [Icalingua-plus-plus/Icalingua-plus-plus#308]
**Describe the bug / 描述**
QQ 有些消息的换行符是 \n，有些是 \r （我不知道是怎么决定使用哪种换行符的），当换行符为\n时可以正确显示换行，而为\r时显示效果就没有了换行

**To Reproduce / 复现过程**

翻消息记录可以找到一些换行符为 \r 的消息

**Expected behavior / 预期的结果**

正确显示换行

**Screenshots / 截图**

![image](https://user-images.githubusercontent.com/24771667/191420530-a57710ff-ab53-40a6-8a1a-0666325681f4.png)
终端显示的消息内容
![image](https://user-images.githubusercontent.com/24771667/191420644-e691ba4e-a8a0-4a13-8f6c-51362079db23.png)
ilpp前端显示效果（没有显示换行）
![image](https://user-images.githubusercontent.com/24771667/191420963-6bc1ca79-8143-4080-ab8e-778910e00add.png)
QQ Android 客户端显示效果（正确显示换行）

**System information / 系统信息**
 - OS:  Arch Linux
 - Version 2.7.2

**Additional context / 附加信息**

可以考虑显示时做个 \r -> \n 的替换？

**Comment by Icalinguaplusplus** [comment]
昨天就已經轉換了 https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/85b6531b46c3bfd333db5eff2b8a7958d2a5ad1b

--------原始邮件--------
2022年9月21日 下午1:25，WAAutoMaton 来信：

**Comment by Icalinguaplusplus** [comment]
development 中已進行轉換 https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/85b6531b46c3bfd333db5eff2b8a7958d2a5ad1b
