### ISSUE TITLE
[BUG]对于聊天记录中套聊天记录的处理不够完全

### ISSUE THREAD

**Issue by a15355447898a** [Icalingua-plus-plus/Icalingua-plus-plus#31]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
对于这种情况
![image](https://user-images.githubusercontent.com/62456287/159126794-4e6ca242-0503-4a98-bf41-d9636c405c4b.png)
只显示出了其中一条转发的聊天记录(总共六条,只显示了第四条的内容)
**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**
可以显示出其中有几条转发的聊天记录,然后可以继续点进去
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: openSUSE Tumbleweed
 - Version:Icalingua++-2.5.8.AppImage

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by a15355447898a** [comment]
这问题有点怪,好像有时可以有时不行
比如这个就可以:![image](https://user-images.githubusercontent.com/62456287/159145626-cb848672-8c02-4d44-ad81-d1e5b82c3b94.png)
但是这个就不可以:
![image](https://user-images.githubusercontent.com/62456287/159145723-4f10993a-1275-4b0f-8666-3a241c84381c.png)
![image](https://user-images.githubusercontent.com/62456287/159145746-ce49088e-64b8-4d56-b5cf-c24e422a98be.png)

**Comment by a15355447898a** [comment]
再次更新情况:刚才说可以的那一个,点进第二层聊天记录只会显示一片空白
![image](https://user-images.githubusercontent.com/62456287/159145884-e29c3e4c-4d8b-40f4-9186-06b2c1294fb6.png)

**Comment by Icalinguaplusplus** [comment]
[oicq 庫不支持套娃轉發](https://github.com/takayama-lily/oicq/blob/master/index.d.ts#L963)

**Comment by Icalinguaplusplus** [comment]
已支持 5e94917
