### ISSUE TITLE
[Feature Request] 群消息支持相册类型消息

### ISSUE THREAD

**Issue by vvinnpy** [Icalingua-plus-plus/Icalingua-plus-plus#311]
- 能否增加支持群中群相册类型消息?
- 目前显示
 ![image](https://user-images.githubusercontent.com/49850665/191878545-93296518-d203-49e2-99a4-749e732c9c6d.png)
- 期望显示
![2022-09-23_09-57](https://user-images.githubusercontent.com/49850665/191879487-7dac3696-546d-4d61-b52f-dc89b7da110e.jpg)

**Comment by Icalinguaplusplus** [comment]
4dd87e8a3b4de6262027f91c39a8ca41bf5f8d61
