### ISSUE TITLE
debian下用户数据移除

### ISSUE THREAD

**Issue by stargazer974** [Icalingua-plus-plus/Icalingua-plus-plus#313]
想要彻底重装一下icalingua++
发现每次卸载后都会保留上一次的数据
想知道如何彻底移除上一次的数据和配置文件

**Comment by aimerneige** [comment]
try this `rm -r ~/.config/icalingua`

If you want to keep your chat history, do not delete the `~/.config/icalingua/database` directory.

**Comment by stargazer974** [comment]
It works.   Thanks a lot!
