### ISSUE TITLE
登陆不上去

### ISSUE THREAD

**Issue by yuzi233** [Icalingua-plus-plus/Icalingua-plus-plus#314]
账号密码登陆，要求手机扫描二维码，但是二维码显示不出来说：“设备授权校验失败，请退出流程后重新进入”然后怎么关闭那个界面也关不掉，怎么重试都一样。

**Comment by yuzi233** [comment]
之前用的是aur上的，刚才下了个appimage直接运行QR又能用了，而且aur上安装的QR也行了，但是不能密码登录

**Comment by Icalinguaplusplus** [comment]
請使用短信驗證
