### ISSUE TITLE
[BUG] 使用icalingua-bridge-oicq在服务器部署，客户端无法上传文件。

### ISSUE THREAD

**Issue by Seele0oO** [Icalingua-plus-plus/Icalingua-plus-plus#316]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
客户端无法上传文件
**To Reproduce / 复现过程**
修改配置文件以连接到bridge,选择文件上传到群聊或者个人对话，显示“Not implicated”
**Expected behavior / 预期的结果**
正常上传
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://user-images.githubusercontent.com/48525679/192171314-0bbe373a-4cea-46f6-88b4-4b679de98b02.png)

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]
- OS: Linux arch 
- Version: 5.19.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 20 Sep 2022 15:17:59 +0000 x86_64 GNU/Linux

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/releases/tag/v2.10.6
