### ISSUE TITLE
登录就会导致QQ被冻结[BUG]

### ISSUE THREAD

**Issue by zhangyiming748** [Icalingua-plus-plus/Icalingua-plus-plus#326]
**Describe the bug / 描述**
我使用的是安卓手表UA
数据库使用本地redis
第一次登录的第二天
账号被冻结
可能是腾讯开始关注这个程序了

**Comment by Wkstr** [comment]
开发者可能跑路了，可惜了一个好的项目

**Comment by happi0** [comment]
the same

**Comment by zhangyiming748** [comment]
都怪腾讯 做的比他差就收购 做的比他好就封杀

**Comment by poplar-at-twilight** [comment]
I also encountered the same problem. I suddenly received dozens of login requests today, but after checking the list of logged-in devices, no unknown devices were found, and I was directly banned by Tencent.
