### ISSUE TITLE
[BUG]发送消息后转到其他聊天界面后返回会出现消息显示重复

### ISSUE THREAD

**Issue by LS-KR** [Icalingua-plus-plus/Icalingua-plus-plus#33]
**Describe the bug / 描述**
在发送一段消息后将聊天界面切换到其他好友再返回后，可能会出现自己发送的消息重复显示的情况   
重新加载后仍有此问题  

**To Reproduce / 复现过程**
发送一段消息，然后切换到其他聊天界面，过一小段时间再切换回来，有几率复现此问题  

**Screenshots / 截图**
这是icalingua界面显示的情况  
![图片](https://user-images.githubusercontent.com/64070144/159153256-79670a00-4353-4865-8122-03812f551bf1.png)  
这是对方手机QQ显示的情况  
![图片](https://user-images.githubusercontent.com/64070144/159153273-23c07b59-82e7-4257-8e09-748f20ff17b0.png)  

**System information / 系统信息**
 - OS: Windows 11 21H2 22000.556
 - Version 2.5.8

**Additional context / 附加信息**
无

**Comment by Icalinguaplusplus** [comment]
請檢查是否開啟了 **切换会话窗口时自动获取历史消息**。
根據 [oicq 協議庫的描述](https://github.com/takayama-lily/oicq/wiki/93.%E8%A7%A3%E6%9E%90%E6%B6%88%E6%81%AFID#%E8%A7%A3%E6%9E%90%E6%B6%88%E6%81%AFid)，私聊消息的seqid不是服務器管理，可能會重復，獲取歷史消息後可能會得到 seqid 和原來不同但內容完全相同的消息。

**Comment by LS-KR** [comment]
> 請檢查是否開啟了 **切换会话窗口时自动获取历史消息**。 根據 [oicq 協議庫的描述](https://github.com/takayama-lily/oicq/wiki/93.%E8%A7%A3%E6%9E%90%E6%B6%88%E6%81%AFID#%E8%A7%A3%E6%9E%90%E6%B6%88%E6%81%AFid)，私聊消息的seqid不是服務器管理，可能會重復，獲取歷史消息後可能會得到 seqid 和原來不同但內容完全相同的消息。

似乎只有开启了 **切换会话窗口时自动获取历史信息** 才会出现此问题, 因为我在我的rpi上运行时从来不开启这个功能, 而此bug似乎也没有出现过.

**Comment by xiaozhangup** [comment]
所以，能不能添加一个检测来规避情况发生？判断内容是否一致然后再显示

**Comment by Icalinguaplusplus** [comment]
https://github.com/takayama-lily/oicq/issues/329

> 所以，能不能添加一个检测来规避情况发生？判断内容是否一致然后再显示

**Comment by freechar** [comment]
尝试了几次，几乎都是发生的发送的瞬间（窗口右下角的那个圈在旋转的时候）切换到其他的聊天窗口，然后在切换回来获取历史消息然后导致消息重复，在SQLite数据库里面，两条消息的最主要区别是username的不同
![图片](https://user-images.githubusercontent.com/39230802/209945618-bf8344d4-6784-4bcd-84f3-b0328f368974.png)
一个是用户的Id，一个是You
在正常发送的情况下username是You, 重复的username是发送这条消息的用户的id，猜测在发送的途中采取了某些优化手段，用户发送的消息是通过本地直接加入进了数据库，然后切换回来获取历史消息从云端获取消息造成了消息的重复。
在没有开启**切换会话窗口时自动获取历史消息**的情况下，发送消息瞬间切换窗口，再切换回来，再手动获取历史数据也会触发这个bug，应该是发送过程中的某些操作被切换窗口中断，导致了这个bug
在手动删除SQLite中的username为“You”的消息之后，再获取历史消息就可获取正常的聊天记录，此时username为当前用户id而不是“You”

**Comment by freechar** [comment]
刚刚有看了下，即使不切换窗口，消息发出后快速手动获取历史消息，也会触发这个bug

**Comment by freechar** [comment]
刚刚研究了下，最简单的解决方案是在每次获取历史消息之前，删除本地数据库中username为“You'”的消息

**Comment by freechar** [comment]
提供一个简单粗暴的解决方案，在项目的`packages/storageProviders`目录下的`SQLStorageProvider.ts`文件内692行`async getMessage(roomId: number, messageId: string): Promise<Message>`函数首中添加上
``` typescript
        try {
            await this.db(`messages`)
            .where("username", "You")
            .where("roomId",roomId)
            .delete();
        } catch (e) {
            throw e;
        }
```
可以解决默认的sqlite的这个bug
