### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by knotoo** [Icalingua-plus-plus/Icalingua-plus-plus#330]
**Describe the bug / 描述**
qq自带大表情发送后显示为小表情，在对方视角也是小表情。但对方发的大表情是可以正常显示为大表情的。

**To Reproduce / 复现过程**
表情选择大表情发送，发送的是小表情

**Expected behavior / 预期的结果**
发送的是大表情

**Screenshots / 截图**
无

**System information / 系统信息**
 - OS: Windows11，21H2
 - Version： 2.7.3

**Additional context / 附加信息**
无

**Comment by Icalinguaplusplus** [comment]
暫不考慮支持發送大表情
