### ISSUE TITLE
今天我已经无法登陆了，你们还好吗？

### ISSUE THREAD

**Issue by kdurant** [Icalingua-plus-plus/Icalingua-plus-plus#331]
![2022-10-04_22-27](https://user-images.githubusercontent.com/2704364/193846170-b5d9a82f-f610-4bff-be28-db90918455a6.png)

**Comment by 007MZY0524** [comment]
2.7.3还可以登录，但是已经有人开始被冻结了

**Comment by FortiterInRe** [comment]
我2.7.3也无法登录了,跟你一样

**Comment by TheNorthShark** [comment]
2.7.2相同问题

**Comment by lanthth** [comment]
厚礼蟹，我还可以登，目前2.7.3双开登陆，但是一直提示自定义插件错误

**Comment by Pairman** [comment]
同样无法扫码。我的密保手机早已寄了，现在没法登录

**Comment by Indigo2233** [comment]
![image](https://user-images.githubusercontent.com/58110312/195287969-7b30216d-5efa-44ea-a7cc-0154ec5ffcee.png)

**Comment by FortiterInRe** [comment]
今天linux我居然登上去了，所以这个能否登录上去是随缘的吗

**Comment by Heng-Mei** [comment]
看已关闭问题有个二维码的反馈，有我的回复可以试试

**Comment by Icalinguaplusplus** [comment]
fixed

**Comment by wangjieaiyuan** [comment]
Version 2.7.7 今天也遇到了同样的问题，我使用这个的时间应该有个两三周了吧。这是提示信息。
![sendpix0](https://user-images.githubusercontent.com/87522374/206944322-1ca9f48f-7fd0-437b-b532-d9a6c3ca05c5.jpg)

**Comment by wangjieaiyuan** [comment]
Version 2.7.7 今天也遇到了同样的问题，我使用这个的时间应该有个两三周了吧。这是提示信息。
![sendpix0](https://user-images.githubusercontent.com/87522374/206944322-1ca9f48f-7fd0-437b-b532-d9a6c3ca05c5.jpg)
