### ISSUE TITLE
[BUG] Linux系统下无图标

### ISSUE THREAD

**Issue by drag0n1zed** [Icalingua-plus-plus/Icalingua-plus-plus#332]
**Describe the bug / 描述**
Linux系统安装后不显示图标

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**
图标看得见

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://user-images.githubusercontent.com/62168687/194052342-83fae7be-ffca-4aa0-8335-5adbc16238b2.png)

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Manjaro Cinnamon
 - Version [e.g. 2.1.4]
 - Manjaro 21.3

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by 0dragg** [comment]
![icon](https://user-images.githubusercontent.com/62168687/194318867-26be2512-f148-445e-aaee-fa386b7ebd97.png)
第二天好了
