### ISSUE TITLE
三个问题

### ISSUE THREAD

**Issue by Winyer** [Icalingua-plus-plus/Icalingua-plus-plus#335]
**Describe the bug / 描述**
第一个，登录总是出现版本过低怎么搞？（用的是2.7.3版本）
第二个，windows下不能多开吗？原版QQ都可以多开，还是我的操作方法不对？
第三个，没有老板键且X86的Windows系统无法安装？

**To Reproduce / 复现过程**
直接打开登录即可复现，尝试各个协议均无果
**Expected behavior / 预期的结果**
希望改进
**Screenshots / 截图**
暂时没有
**System information / 系统信息**
Windows X86/X64
**Additional context / 附加信息**
无

**Comment by aimerneige** [comment]
多开：https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/27#issuecomment-1253991740

**Comment by Winyer** [comment]
> 多开：[#27 （评论）](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/27#issuecomment-1253991740)

好的，谢谢

**Comment by vegetabledog-x86** [comment]
![image](https://user-images.githubusercontent.com/77112843/195242212-5ffa148a-b0f1-4679-b30f-4cea5fe45c61.png)
出现了相同的问题，今天登陆时发现，面板上能点击的按钮都试过了

**Comment by Rnfmabj327** [comment]
ubuntu，2.7.3，今天也出现了版本过低的问题

**Comment by Winyer** [comment]
> ![图像](https://user-images.githubusercontent.com/77112843/195242212-5ffa148a-b0f1-4679-b30f-4cea5fe45c61.png)出现了相同的问题，今天登陆时发现，面板上能点击的按钮都试过了

可能是协议太低了？不知道多久能解决

**Comment by Winyer** [comment]
> ubuntu，2.7.3，今天也出现了版本过低的问题

其实2.7.2的时候就有这个问题，我一直以为2.7.3解决了
