### ISSUE TITLE
qq好友头像正常显示，但是群聊头像无法正常显示

### ISSUE THREAD

**Issue by TDYQ-Liu** [Icalingua-plus-plus/Icalingua-plus-plus#338]
**Describe the bug / 描述**
qq好友头像正常显示，但是群聊头像无法正常显示。
清空 _~/.config/icalingua/Cache/_ 后顶栏头像正常显示，但侧边栏仍然无法显示

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
![1](https://user-images.githubusercontent.com/71477981/195292474-e2b54619-6ff5-4eb7-b4d9-9242d9d4ff6c.png)

**_清除cache后：_**
![2](https://user-images.githubusercontent.com/71477981/195292498-8344c981-ab15-4a9b-a34c-b152498b298f.png)

**System information / 系统信息**
 - OS: ubuntu 22.04.1lts
 - 5.15.0-48-generic
 - x86_64 x86_64 x86_64 GNU/Linux

**Additional context / 附加信息**
删除 _~/.config/icalingua/_ 后重新登录，仍然不显示。

**Comment by TDYQ-Liu** [comment]
**补充：**
清空 ~/.config/icalingua/Cache/ 后顶栏头像正常显示，但退出icalingua后重新登录又会回到群组侧边头像和顶栏头像都无法显示的状况。

**Comment by Rnfmabj327** [comment]
隔壁问题的来问下，其他功能还可以正常使用是吗，没有在登录时报“当前QQ版本过低”？
看了隔壁issue以为是全寄了

**Comment by TDYQ-Liu** [comment]
> 隔壁问题的来问下，其他功能还可以正常使用是吗，没有在登录时报“当前QQ版本过低”？ 看了隔壁issue以为是全寄了

其他功能可以正常使用，没有在登录时报“当前QQ版本过低”（我没有

**Comment by liweiwa** [comment]
前几天还这样，但今天登陆后头像显示又正常了，但一直提示自定义插件错误

**Comment by TDYQ-Liu** [comment]
现已正常显示

**Comment by TDYQ-Liu** [comment]
log out 后第一次登录头像显示正常，退出后再重新登录 群头像侧边头像和顶栏头像都无法显示

**Comment by TDYQ-Liu** [comment]
发现了一个解决办法：重复点击**_清除缓存并重新加载_**直到图像出现为止
