### ISSUE TITLE
[Feature Request]对黑色主题更友好的图标？

### ISSUE THREAD

**Issue by plumlis** [Icalingua-plus-plus/Icalingua-plus-plus#339]
目前很多 LInux 下 Gnome 用户的默认主题 adwaita 的 Dock 栏中都是黑为主的底色，在这种情况下 icalingua 的图标就会很难看清。
虽然 Linux 用户大多数可以通过修改 desktop 文件或者其他手段自定义图标，但换一个边界更加清晰的图标对于大部分黑色主题用户或许会更好一些。

![Screenshot from 2022-10-13 16-26-26](https://user-images.githubusercontent.com/6737429/195545463-9a17c98b-9822-47b9-961c-63162d68afcf.png)

**Comment by kands-code** [comment]
你可以试试这个图标（不介意其具体含义的话）
![icalingua](https://user-images.githubusercontent.com/59006329/195994687-82e76c12-3340-493e-80ed-41de00cc08ec.png)

自己手动修改 desktop 文件的 icon 路径即可

**Comment by Nevodev** [comment]
> 你可以试试这个图标（不介意其具体含义的话） ![icalingua](https://user-images.githubusercontent.com/59006329/195994687-82e76c12-3340-493e-80ed-41de00cc08ec.png)
> 
> 自己手动修改 desktop 文件的 icon 路径即可

草

**Comment by aimerneige** [comment]
> 你可以试试这个图标（不介意其具体含义的话） ![icalingua](https://user-images.githubusercontent.com/59006329/195994687-82e76c12-3340-493e-80ed-41de00cc08ec.png)
> 
> 自己手动修改 desktop 文件的 icon 路径即可

好！
