### ISSUE TITLE
[BUG] 当前QQ版本过低

### ISSUE THREAD

**Issue by DeeChael** [Icalingua-plus-plus/Icalingua-plus-plus#340]
**Describe the bug / 描述**
2.7.3 无法登录

**To Reproduce / 复现过程**
正常输入帐号和密码点击登录

**Expected behavior / 预期的结果**
正常登录

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/63186003/195625477-e8f30339-4e08-4800-aa44-e5c7c5119719.png)

**System information / 系统信息**
 - OS: Manjaro
 - Version 21.3.7

**Additional context / 附加信息**
无

**Comment by Zweisamkeiten** [comment]
Me too

**Comment by 401U** [comment]
+1

**Comment by yhm138** [comment]
+1

**Comment by KeithCoreDumped** [comment]
+1，昨天还能登录的

**Comment by InsaneOnion** [comment]
+1

**Comment by Indigo2233** [comment]
今天好像可以用了

**Comment by ParticleG** [comment]
账号密码登录好像还是不行，但二维码登录可以

**Comment by DeeChael** [comment]
> 账号密码登录好像还是不行，但二维码登录可以

我昨天开系统的时候突然又登上了。。（我设置的开机自启动）
不知道为什么时灵时不灵的

**Comment by joyanhui** [comment]
昨天可以登录，今天又不行了

aur/icalingua++ 2.7.4-1  也提示版本过低

**Comment by Icalinguaplusplus** [comment]
> 昨天可以登录，今天又不行了
> 
> aur/icalingua++ 2.7.4-1 也提示版本过低

Please click “无法登录?”, and retry.

**Comment by joyanhui** [comment]
> 



> > 昨天可以登录，今天又不行了
> > aur/icalingua++ 2.7.4-1 也提示版本过低
> 
> Please click “无法登录?”, and retry.

可以了，感谢！！！

**Comment by Zpcin** [comment]
> 账号密码登录好像还是不行，但二维码登录可以

icalingua++没有二维码呀

**Comment by ParticleG** [comment]
> > 账号密码登录好像还是不行，但二维码登录可以
> 
> icalingua++没有二维码呀

登录时不输入密码就会使用验证码登录
