### ISSUE TITLE
[BUG] 下载任务重复

### ISSUE THREAD

**Issue by EnderAvaritia** [Icalingua-plus-plus/Icalingua-plus-plus#345]
**Describe the bug / 描述**
开启aria下载之后点击文件会下载多份
**To Reproduce / 复现过程**
开启aria下载之后点击文件会下载多份
**Expected behavior / 预期的结果**
只下载一份文件
**Screenshots / 截图**![image](https://user-images.githubusercontent.com/84321282/195991762-999db0e1-91b8-4a8f-bd4c-10c98902889f.png)

**System information / 系统信息**
 - OS: 版本	Windows 10 企业版 21H2
 - Version 2.7.3

**Comment by Icalinguaplusplus** [comment]
fixed in development
