### ISSUE TITLE
[BUG] 群文件界面切出后无法下载

### ISSUE THREAD

**Issue by EnderAvaritia** [Icalingua-plus-plus/Icalingua-plus-plus#346]
**Describe the bug / 描述**
群文件界面切出后无法下载

**To Reproduce / 复现过程**
打开群文件之后点击其他窗口，在已经点开的群文件界面无法下载文件
**Expected behavior / 预期的结果**
希望能修好这个问题

**System information / 系统信息**
 - OS: 版本	Windows 10 企业版 21H2
 - Version 2.7.3

**Comment by Icalinguaplusplus** [comment]
fixed in development
