### ISSUE TITLE
[Feature Request]  添加Flatpak构建版本

### ISSUE THREAD

**Issue by LMFuture-Me** [Icalingua-plus-plus/Icalingua-plus-plus#347]
在package.json中加入flatpak。本人测试没有成功，故提此issue

**Comment by chisaato** [comment]
Flathub 上已经有对++版本的打包了(就是在原仓库上),只不过版本一直没更

**Comment by leohearts** [comment]
flatpak上的自动更新终于被合并了 （草） https://github.com/flathub/io.github.Icalingua.Icalingua/pull/29
我一直在用flatpak构建版本，没啥问题的
