### ISSUE TITLE
[BUG] 二维码登录提示 "设备授权校验失败"

### ISSUE THREAD

**Issue by TDYQ-Liu** [Icalingua-plus-plus/Icalingua-plus-plus#348]
**Describe the bug / 描述**
使用二维码登录时会提示：**_设备授权校验失败，请退出流程后重新进入。_**
或者就是没有提示一直在加载也加载不出来二维码。

**To Reproduce / 复现过程**
登录 > 扫码验证

**Expected behavior / 预期的结果**
能够扫码验证登录

**Screenshots / 截图**
![Screenshot from 2022-10-16 14-48-09](https://user-images.githubusercontent.com/71477981/196022607-79265887-1113-42dd-925f-b3b969f83976.png)
![2](https://user-images.githubusercontent.com/71477981/196022603-7cdd1863-838b-4fb1-8d59-e7c36a17409d.png)
![1](https://user-images.githubusercontent.com/71477981/196022571-f001eefd-c979-4785-8fb0-a81474318ee2.png)

**System information / 系统信息**
 - OS:  ubuntu 22.04.1lts
 - Kernel: 5.15.0-48-generic
 - Version Icalingua++ 2.73

**Additional context / 附加信息**
无

**Comment by Heng-Mei** [comment]
同样的ubuntu同样的bug，我也碰到了

**Comment by zyeuu** [comment]
same problem on same OS for v2.4.3 in snap store

**Comment by Heng-Mei** [comment]
有个曲线救国的方法，只输入账号然后点击二维码登陆，那个二维码可以加载

**Comment by zyeuu** [comment]
> 有个曲线救国的方法，只输入账号然后点击二维码登陆，那个二维码可以加载

thanks it work in v2.7.3

**Comment by TDYQ-Liu** [comment]
> 有个曲线救国的方法，只输入账号然后点击二维码登陆，那个二维码可以加载

谢谢！
