### ISSUE TITLE
[BUG] KDE下输入Emoji表情时程序停止响应

### ISSUE THREAD

**Issue by Eslzzyl** [Icalingua-plus-plus/Icalingua-plus-plus#352]
**Describe the bug / 描述**
KDE环境下，打开表情输入面板，选中“Emojis”选项卡，点击任意表情，程序随即失去响应。重启程序后恢复正常。

**To Reproduce / 复现过程**
如上。该问题不是每次均出现，但可以稳定复现。平均每输入5-6个emoji表情时就会出现。

**Expected behavior / 预期的结果**
Emoji表情可以稳定输入，不再引起程序卡死。

**System information / 系统信息**
 - OS: Kubuntu 22.04，KDE Plasma 5.24.6，KDE Framework 5.92.0
 - Version 2.7.5

**Comment by Icalinguaplusplus** [comment]
是渲染進程卡死還是主進程卡死？

**Comment by Eslzzyl** [comment]
> 是渲染進程卡死還是主進程卡死？

抱歉，我不懂Electron，因此无法分辨是哪个进程卡死。
但有一点，程序在无响应阶段仍然可以收到新消息并显示，但不能响应点击了。

**Comment by Icalinguaplusplus** [comment]
> > 是渲染進程卡死還是主進程卡死？
> 
> 抱歉，我不懂Electron，因此无法分辨是哪个进程卡死。 但有一点，程序在无响应阶段仍然可以收到新消息并显示，但不能响应点击了。

請更新 Electron 后試試是否還有問題？（主綫上已更新為 Electron21）

**Comment by Eslzzyl** [comment]
最近一段时间的断续使用中没有再遇到问题，感谢
