### ISSUE TITLE
[BUG] win11 休眠一段时间后，程序无法重连

### ISSUE THREAD

**Issue by Ecalose** [Icalingua-plus-plus/Icalingua-plus-plus#353]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
win11 休眠一段时间后，程序无法重连，reconnect now将会一直转圈
**To Reproduce / 复现过程**
扫码登录后，win11 休眠一段时间
**Expected behavior / 预期的结果**
应正常恢复连接
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://user-images.githubusercontent.com/47114714/197384474-2c7425d4-b97a-4495-9e22-1e1d865f263a.png)

**System information / 系统信息**
 - OS: [windows11]
 - Version [2.7.5]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
token 失效，需重新登入
使用密碼登入可防止出現這個問題

**Comment by Ecalose** [comment]
> token 失效，需重新登入 使用密碼登入可防止出現這個問題

ok
