### ISSUE TITLE
[BUG] a javascript error occurred in the main process

### ISSUE THREAD

**Issue by ghost** [Icalingua-plus-plus/Icalingua-plus-plus#356]
**Describe the bug / 描述**
启动时弹窗 「a javascript error occurred in the main process」，且运行中不时弹窗，但是不影响功能(貌似)

**To Reproduce / 复现过程**
启动软件/运行时不定期弹窗

**Expected behavior / 预期的结果**
希望能解决弹窗问题

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/61445867/197667966-21af64d4-983a-4694-a011-4bd99b88aac2.png)

**System information / 系统信息**
 - OS: ArchLinux
 - WM: Swaywm
 - 包来源: aur/icalingua++、Github Release 中包

**Additional context / 附加信息**
是  electron 问题嘛，目前版本都是最新的
![image](https://user-images.githubusercontent.com/61445867/197668188-58186f7d-777c-465b-be77-e1904e04ba3c.png)

**Comment by Icalinguaplusplus** [comment]
是否是在接收到語音消息時出現？
