### ISSUE TITLE
[Feature Request] 希望添加输出 apk 的功能

### ISSUE THREAD

**Issue by CornWorld** [Icalingua-plus-plus/Icalingua-plus-plus#357]
就我所知，目前 Ic++ 已经有触摸适配并且 Electron 具有良好的可移植性，并且手机上的 QQ 使用体验也不是很阳间，那么能否添加一个适用于手机的版本呢？

**Comment by Icalinguaplusplus** [comment]
Electron 只適用於桌面環境

**Comment by CornWorld** [comment]
目前技术栈已经运行在 Android 上运行 Electron 应用，只需要对底层调用进行适配即可。 @Icalinguaplusplus

**Comment by SteveWorkshop** [comment]
现在想在安卓上面用还得想办法搞个Linux子系统。。。

**Comment by lanthth** [comment]
求求了，icalingua快来android来拯救吧，官方QQ一坨💩，功能最多用到%20，空间动辄10G『AAAA』はよー!僕を助けにやんー！
