### ISSUE TITLE
[BUG]Debian 11 无法安装

### ISSUE THREAD

**Issue by hmsjy2017** [Icalingua-plus-plus/Icalingua-plus-plus#36]
**Describe the bug / 描述**
从 Debian 11 开始，代替，而 Icalingua++ 依赖于 `libappindicator3-1`。

**To Reproduce / 复现过程**
在 Debian 11 上 安装 Icalingua++ 就会出现依赖问题。

**Expected behavior / 预期的结果**
Icalingua++ 能正常安装

**Screenshots / 截图**

![BAF401C7-B7AF-4745-8C35-8EDB81C3A92B](https://user-images.githubusercontent.com/42692274/160129609-24be8204-cfda-4c20-b10f-c2d9ad32d8fe.jpeg)

**System information / 系统信息**
 - OS: Debian 11
 - Version 2.5.8

**Additional context / 附加信息**
解决方法：
打包 deb 时将 `libappindicator3-1`  替换为 `libayatana-appindicator3-1` 。

![3D70829E-D50E-4AAE-A9D8-E56960388DE0](https://user-images.githubusercontent.com/42692274/160129986-beab63a4-09b8-453e-8d57-4fb663e4eb5c.jpeg)

**Comment by Icalinguaplusplus** [comment]
更換新版本 electron-builder 後已將 libappindicator3-1 列為 Recommend
