### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by ncwuguo** [Icalingua-plus-plus/Icalingua-plus-plus#362]
[安全提醒]当前登录存在安全风险，请使用常用设备或通过手机号登录

**Comment by Icalinguaplusplus** [comment]
Does clicking the "无法登录?" button help?

**Comment by ncwuguo** [comment]
> Does clicking the "无法登录?" button help?

No, I reinstalled the software again, but this time it shows "当前QQ版本过低，请升级至最新版后再登录。"

**Comment by Icalinguaplusplus** [comment]
> > Does clicking the "无法登录?" button help?
> 
> No, I reinstalled the software again, but this time it shows "当前QQ版本过低，请升级至最新版后再登录。"

請在出現登錄失敗提示后點擊 "無法登錄" 的按鈕以更換設備信息

**Comment by ncwuguo** [comment]
> > > Does clicking the "无法登录?" button help?
> > 
> > 
> > No, I reinstalled the software again, but this time it shows "当前QQ版本过低，请升级至最新版后再登录。"
> 
> 請在出現登錄失敗提示后點擊 "無法登錄" 的按鈕以更換設備信息

ok，Login succeeded
