### ISSUE TITLE
[BUG] 输入法有输入项，回车上屏时，会直接把icalingua直接发送消息出去

### ISSUE THREAD

**Issue by yaocccc** [Icalingua-plus-plus/Icalingua-plus-plus#364]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

有个bug，就是有时候输入法有输入项，回车上屏时，会直接把icalingua直接发送消息出去，出现频率非常高

**To Reproduce / 复现过程**

输入过程中用回车上屏

**Expected behavior / 预期的结果**

只上屏输入法内容 而不发送消息

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.16.1]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
IME 的問題，建議修改發送快捷鍵

**Comment by yaocccc** [comment]
> IME 的問題，建議修改發送快捷鍵

那感觉降低体验好多，昨天与另一个朋友聊天，他采用了一个消除抖动的方法来规避这个bug，不过感觉不太优雅
![1](https://user-images.githubusercontent.com/53512609/198501270-370202e3-9858-427d-9637-091291911f7b.png)

**Comment by yaocccc** [comment]
感觉上可以用消除抖动的思路解决，延迟100ms后对比上次和当前次的message是否相等，相等则发送，不相等return

**Comment by Icalinguaplusplus** [comment]
使用的 IME 和系統是什麽

**Comment by yaocccc** [comment]
> 使用的 IME 和系統是什麽

ARCHLINUX +  FCITX5

**Comment by yaocccc** [comment]
该问题存在普遍性。我身边好多linux的用户都类似。。

**Comment by Icalinguaplusplus** [comment]
使用什麽 Electron 版本？17.4.11 測試無問題

**Comment by yaocccc** [comment]
> 
20.0.3， 我尝试一下

**Comment by yaocccc** [comment]
我也是17.4.11， 跟着仓库走的

**Comment by yaocccc** [comment]
https://user-images.githubusercontent.com/53512609/198508704-8ee9c954-6cca-461d-bd3a-207d53d43ef3.mp4

**Comment by Icalinguaplusplus** [comment]
Icalingua++ 在 isComposing 的時候已經返回了，如果發出去了就説明沒有收到 Compose 消息，試試更新下 IME

**Comment by yaocccc** [comment]
> isComposing

我尝试了下，仅有在开启输入法预编辑模式的时候 isComposing 才可能有true值，其他情况均为false，这可能是ime的锅了。
