### ISSUE TITLE
[Feature Request]在登录时显示当前所用的设备名

### ISSUE THREAD

**Issue by kuzuanpa** [Icalingua-plus-plus/Icalingua-plus-plus#366]
**Is your feature request related to a problem? Please describe.**
并没有

**Describe the solution you'd like**
在登陆按钮下方或者什么地方显示当前正在使用的设备名

**Describe alternatives you've considered**
登录后显示在主界面右上角应该也不错

**Additional context**
tx风控系统可以通过填帐号信息的方式解除，需要填绑定手机号、曾用头像、曾用设备三项
但是我注意到icalingua最近新增了一个随机生成设备名的功能，这样对风控解除造成一定困难（最后一步）

**Comment by Icalinguaplusplus** [comment]
生成的 device name 均以 `ILPP ` 做前綴

**Comment by kuzuanpa** [comment]
那也希望在那个弹出的窗口里或者什么位置提示下，可以避免疑问产生
