### ISSUE TITLE
[BUG] 与好友私聊过程中使用回复在其他设备不显示回复

### ISSUE THREAD

**Issue by KinnerFisch** [Icalingua-plus-plus/Icalingua-plus-plus#368]
与好友私聊过程中使用回复在其他设备不显示回复

在和好友聊天时我回复了她的某一天消息，但在我的手机以及她的电脑上并没有显示回复

**系统信息**
 - OS: Windows 11 22H2 (22621.674)
 - Version 2.7.7

截图：

![image](https://user-images.githubusercontent.com/75480729/198877835-4878aa16-65d2-4765-b555-f834dc18829d.png)
![image](https://user-images.githubusercontent.com/75480729/198877870-9a56a3fe-3ee8-4494-b09c-37988b725f5e.png)
![image](https://user-images.githubusercontent.com/75480729/198877926-c568a104-0edd-4b23-aaeb-55e0c115440b.png)

**Comment by Icalinguaplusplus** [comment]
已解決
