### ISSUE TITLE
[Feature Request]之前的保存表情可以直接保存到QQ云表情里面去，现在你更新的版本这个功能没有了！！

### ISSUE THREAD

**Issue by yuanjie408** [Icalingua-plus-plus/Icalingua-plus-plus#372]
之前的保存表情可以直接保存到QQ云表情里面去，现在你更新的版本这个功能没有了！！

**Comment by Icalinguaplusplus** [comment]
什麽版本可以？

**Comment by yuanjie408** [comment]
2.5以前！



发自我的手机


-------- 原始邮件 --------
发件人： The Icalingua++ Authors ***@***.***>
日期： 2022年11月2日周三 11:12
收件人： Icalingua-plus-plus/Icalingua-plus-plus ***@***.***>
抄送： yuanjie408 ***@***.***>, Author ***@***.***>
主 题： Re: [Icalingua-plus-plus/Icalingua-plus-plus] [Feature Request]之前的保存表情可以直接保存到QQ云表情里面去，现在你更新的版本这个功能没有了！！ (Issue #372)

什麽版本可以？

**Comment by Icalinguaplusplus** [comment]
一直都是本地表情，從來就沒有保存到漫游表情的功能
