### ISSUE TITLE
[Feature Request]Windows端增加图标随Windows系统深浅色设定自动变色

### ISSUE THREAD

**Issue by KagaJiankui** [Icalingua-plus-plus/Icalingua-plus-plus#373]
希望在Windows端增加任务栏图标随Windows系统深浅色主题自动变色功能。

现有任务栏图标在Windows端深浅色切换时不会自动变色，需要手动勾选/取消勾选“深色图标”选项。
![image](https://user-images.githubusercontent.com/58453886/199673046-1466b825-2cc6-4b7f-944d-4ba4af746614.png)

浅色主题时自动切换到深色任务栏图标：
![image](https://user-images.githubusercontent.com/58453886/199672633-8d18eaa2-c80c-452e-92a2-7aa3e8e81a56.png)
深色主题时自动切换到浅色任务栏图标：
![image](https://user-images.githubusercontent.com/58453886/199672878-f54b8b30-6afe-4eb3-b266-533b818b910c.png)

**Comment by Icalinguaplusplus** [comment]
更換 Electron 版本后已支持
