### ISSUE TITLE
[BUG] 消息重复

### ISSUE THREAD

**Issue by xgugugu** [Icalingua-plus-plus/Icalingua-plus-plus#374]
**Describe the bug / 描述**
两则消息ID和内容完全一致的消息一上一下显示在回话里，时间间隔1秒

**To Reproduce / 复现过程**
发送一则消息，然后获取历史记录

**Expected behavior / 预期的结果**
不出现消息重复的问题

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/85472190/199856964-e3c34ee3-5edc-4057-a4d9-f878de51151f.png)
![image](https://user-images.githubusercontent.com/85472190/199856991-cecaa856-a231-47ed-91cc-e224f14c193f.png)

**System information / 系统信息**
 - OS: Ubuntu 22.04 & Manjaro GNOME
 - Version 2.7.7

**Additional context / 附加信息**
我想bug的原因可能是icalingua++在消息发送时存储了一遍消息，然后在获取历史消息时又重新获取了一遍
可能的修复方法：消息ID是完全一致的，可以依此进行去重操作

**Comment by pointertobios** [comment]
+1

**Comment by KarmaRich** [comment]
+1

**Comment by SoDebug** [comment]
+2

**Comment by Icalinguaplusplus** [comment]
消息 ID 并非一致，無法去重
