### ISSUE TITLE
[Feature Request] 添加監察器, 當 icalingua++ 高佔用時結束 icalingua++ 及附屬 electron 行程

### ISSUE THREAD

**Issue by kobe-koto** [Icalingua-plus-plus/Icalingua-plus-plus#375]
**您的功能请求是否与问题相关？**
是的, icalingua++ 常常出現高佔用, 導致本不富裕的 CPU 雪上加霜(x

**描述您想要的解决方案**
添加監察器 ( 獨立於 electron ,如 bash ), 當 icalingua++ 高佔用時結束 icalingua++ 及附屬 electron 行程

**描述您考虑过的替代方案**
使用 matrix-qq, 自行編寫 bash 腳本等

**其他**
系統訊息:
OS: Manjaro Linux x86_64 
Kernel: 5.15.76-1-MANJARO 
Shell: bash 5.1.16

**Comment by Neubulae** [comment]
和[这个issue](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/14)是否有关呢

**Comment by kobe-koto** [comment]
> 和[这个issue](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/14)是否有关呢

yep
