### ISSUE TITLE
[Feature Request]希望可以自定义聊天背景

### ISSUE THREAD

**Issue by wzk0** [Icalingua-plus-plus/Icalingua-plus-plus#377]
![如图所示](https://user-images.githubusercontent.com/89891126/200270631-b5952b29-af9a-4de4-b513-db4f476f2e5f.png)

如图所示, `Dark Mode`的时候侧边栏和聊天框融为一体, 虽然挺好看的, 但是有时候对眼神不行的人(比如我)不是很友好.

可否加一个自定义背景功能, 或者自定义css呢?

**Comment by aimerneige** [comment]
自定义css: https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/93#issuecomment-1148784236
