### ISSUE TITLE
更新提示遮挡视线，设置关闭

### ISSUE THREAD

**Issue by heptarri** [Icalingua-plus-plus/Icalingua-plus-plus#380]
**Is your feature request related to a problem? Please describe.**
在聊天更新你的时候，绿色的下拉提示框会遮挡主体的显示。

**Describe the solution you'd like**
将该种提示叠加或者可以在设置中挂你吧

**Describe alternatives you've considered**

**Additional context**

**Comment by heptarri** [comment]
Does there anyone to solve it?

**Comment by aimerneige** [comment]
> 将该种提示叠加或者可以在设置中挂你吧

您在说什么

**Comment by aimerneige** [comment]
![image](https://user-images.githubusercontent.com/51701792/202193924-e3303133-25f4-47a1-91d0-e89be1e7f254.png)
