### ISSUE TITLE
[Feature Request] 添加扫码功能

### ISSUE THREAD

**Issue by lyc8503** [Icalingua-plus-plus/Icalingua-plus-plus#386]
**Describe the solution you'd like**
在使用安卓或 pad 协议登录时, 是否能提供一个扫码功能, 选择现有的二维码打开进行扫码(模拟使用手机设备时的扫码).
可以做到使用 icalingua 扫码登陆.

**Comment by Icalinguaplusplus** [comment]
根據協議實現難度，暫不考慮
