### ISSUE TITLE
[BUG]在深色模式下窗口标题栏依然为白色

### ISSUE THREAD

**Issue by LOGYT-Eberk** [Icalingua-plus-plus/Icalingua-plus-plus#388]
标题栏似乎不适配深色模式
![屏幕截图_20221115_192746](https://user-images.githubusercontent.com/117907349/201908801-c2f1cd16-cb66-4e94-8479-ca865bf0e0e6.png)

System information 
 - OS: Windows 11
 - Version 22623.891

**Comment by storm-1614** [comment]
这个和icalingua无关，是系统主题缘故

**Comment by aimerneige** [comment]
没记错的话修改系统主题就行

窗口标题栏的颜色主要取决于系统主题而不是软件

**Comment by LOGYT-Eberk** [comment]
系统主题改为深色，标题栏依然是白色的

**Comment by hwitdew** [comment]
可以使用mica for everyone来实现

**Comment by aimerneige** [comment]
如果你在用 Gnome，除了在设置中修改外，还需要在 gnome-tweak-tool 中修改

**Comment by Nevodev** [comment]
> 这个和icalingua无关，是系统主题缘故

欸，你还别说，他确实和icalingua有关系。标题栏的深浅色是应用程序自己决定的。
编辑：在Windows上

**Comment by dmlgzs** [comment]
> > 这个和icalingua无关，是系统主题缘故
> 
> 欸，你还别说，他确实和icalingua有关系。标题栏的深浅色是应用程序自己决定的。 编辑：在Windows上

这是 Electron 的问题，升级就好了
