### ISSUE TITLE
[BUG] Can't send big files(~ 10MB)

### ISSUE THREAD

**Issue by glyh** [Icalingua-plus-plus/Icalingua-plus-plus#39]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

Can't send files 
**To Reproduce / 复现过程**
Send a file to friend

**Expected behavior / 预期的结果**
Succeeds.

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
Fails. 

**System information / 系统信息**
 - OS: `Linux arch 5.16.16-arch1-1 #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000 x86_64 GNU/Linux`
 - Version
 
![image](https://user-images.githubusercontent.com/12870742/160520755-500c7d6e-4832-4124-8d1d-220d6d560527.png)

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by chiyuki0325** [comment]
OICQ库不支持给好友发送文件，可以关了（手动滑稽）

**Comment by glyh** [comment]
If there's no such support, please add information about it or just delete the send file button. Thanks.
