### ISSUE TITLE
[BUG] 图片查看器有时不能加载图片

### ISSUE THREAD

**Issue by Xmarmalade** [Icalingua-plus-plus/Icalingua-plus-plus#395]
**Describe the bug / 描述**
当点击聊天中的图片时，有概率出现如下方截屏中的白色窗口而不加载图片

**To Reproduce / 复现过程**
见描述

**Expected behavior / 预期的结果**
窗口应该是正常显示为“图片查看”

**Screenshots / 截图**
截图描述的是一张图片在图片查看器和Chrome中的显示
![image](https://user-images.githubusercontent.com/16839488/202900309-f732be9f-bc4a-4cae-94dd-aa1a5c94becb.png)

**System information / 系统信息**
 - OS: Windows 11

**Additional context / 附加信息**
此外，我无法通过F12或者CTRL+Shift+I打开devtools

**Comment by Icalinguaplusplus** [comment]
系統問題，防毒軟體可能會影響新窗體的創建
