### ISSUE TITLE
[BUG]Deepin20.7版本用一段时间会崩溃

### ISSUE THREAD

**Issue by chenmingjun2** [Icalingua-plus-plus/Icalingua-plus-plus#396]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
软件直接崩溃
**To Reproduce / 复现过程**
在Deepin20.7系统中，使用2.7.7版本的软件，使用一段时间就会崩溃
**Expected behavior / 预期的结果**
不会崩溃
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
![图片](https://user-images.githubusercontent.com/111257814/203296591-9796d4db-7f18-40cd-ab8c-55a555ec6487.png)

 - Version [e.g. 2.1.4]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
如果没有任何错误日志，自行更换无问题的 Electron 版本即可
