### ISSUE TITLE
[BUG] unable to open on Raspberry Pi, guess something to do with electron.

### ISSUE THREAD

**Issue by kernelbin** [Icalingua-plus-plus/Icalingua-plus-plus#4]
**Describe the bug / 描述**

I tried to run Icalingua-2.5.2 on raspberry pi (install Raspberry Pi OS)  and it failed.
guess something to do with electron?
```
pi@raspberrypi:~/Desktop $ ./Icalingua-2.5.2-arm64.AppImage
(node:12836) UnhandledPromiseRejectionWarning: Error: /tmp/.org.chromium.Chromium.Q2rUEP: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/tmp/.mount_IcalinNuvJoM/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/tmp/.mount_IcalinNuvJoM/resources/app.asar/node_modules/silk-sdk/index.js:3:33)
(Use `icalingua --trace-warnings ...` to show where the warning was created)
(node:12836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**To Reproduce / 复现过程**

just download the [Icalingua-2.5.2-arm64.AppImage](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/releases/download/v2.5.2/Icalingua-2.5.2-arm64.AppImage) on raspberry pi, and try to run it.

**Expected behavior / 预期的结果**

Icalingua starts.

**System information / 系统信息**

```
pi@raspberrypi:~/Desktop $ uname -a
Linux raspberrypi 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux
```

I use KDE as desktop.

**Additional context / 附加信息**
If need any help (like testing or so) just call me.

**Comment by Icalinguaplusplus** [comment]
It has been tried to fix in **v2.5.3**, please use the **2.5.3** version to test if there is the same bug or a new bug, thank you.

**Comment by kernelbin** [comment]
> It has been tried to fix in **v2.5.3**, please use the **2.5.3** version to test if there is the same bug or a new bug, thank you.

Great! I will test it later!

**Comment by kernelbin** [comment]
Awesome! It works on my raspberry pi! 😃
Thanks a lot!

**Comment by kernelbin** [comment]
BTW, when using `.deb` version, I also encountered a problem telling me `libappindicator3-1` can not be found. I solved it by replacing it with `libayatana-appindicator3-1`. ( AppImage version does not exist this problem)

**Comment by kernelbin** [comment]
Now `icalingua-plus-plus` can successfully launch on my RPI, but when accessing SQLite, it failed, telling me `GLIBC_2.33` not found. The symptom looks exactly like [Issue #5](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/5) (except the version), so I won't copy the error log here again. haven't tried external DB yet.

**Comment by Icalinguaplusplus** [comment]
I'm sorry currently I don't have an arm64 device, so I can't test it. Please try to install the latest version of `glibc` using the package management tool in your system. Or you can install `glibc`, clone this repository, build and test it.
