### ISSUE TITLE
[BUG] 自定义插件出错

### ISSUE THREAD

**Issue by ShulkerSakura** [Icalingua-plus-plus/Icalingua-plus-plus#400]
**描述与复现**
登录后打开任意一个聊天会话都会从上方弹出
“自定义插件出错“

**Screenshot/截图**
![-6527c92dca523748](https://user-images.githubusercontent.com/50770360/203995049-07d3e888-cccd-4e9e-884a-28ee6e3d8cd8.png)

**System information / 系统信息**
 - OS: [Debian GNU/Linux]
 - Version [11]

**Comment by dmlgzs** [comment]
#305

**Comment by ShulkerSakura** [comment]
我这个ica是全新安装的，直接就遇到了这个问题所以，这个自定义插件应该是默认启用的

**Comment by dmlgzs** [comment]
> 我这个ica是全新安装的，直接就遇到了这个问题所以，这个自定义插件应该是默认启用的

默认禁用的，重新安装并不会删除以前的配置https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/blob/4d23b9e76ad8bb7e852d2859e3f6b27de9bc42f3/icalingua/src/main/utils/configManager.ts#L112
