### ISSUE TITLE
[BUG]找不到可用的本地查看器

### ISSUE THREAD

**Issue by ryanlo713** [Icalingua-plus-plus/Icalingua-plus-plus#403]
**Describe the bug / 描述**

对图片右键跳出菜单点击「使用本地查看器打开」弹出「找不到可用的本地查看器」

**Expected behavior / 预期的结果**

需要如何配置以指定用特定程序开启？

**Screenshots / 截图**

![image](https://user-images.githubusercontent.com/12672523/204136328-6d038b82-a08f-4a1d-96ea-ca4ea45a56f3.png)

![image](https://user-images.githubusercontent.com/12672523/204136356-21de8b79-67ad-4d51-beb3-e09b5cb3e510.png)

**System information / 系统信息**
 - OS: Windows 11 22H2
 - Version 2.7.7

**Comment by Icalinguaplusplus** [comment]
不支持 Windows

**Comment by ryanlo713** [comment]
摸索了一下，其实只要装Windows版的Gimp或Okular并设置PATH就能正常使用该功能了。
