### ISSUE TITLE
[BUG]复制出的图片无法在其他程序粘贴

### ISSUE THREAD

**Issue by orz12** [Icalingua-plus-plus/Icalingua-plus-plus#404]
**Describe the bug / 描述**
复制出的图片无法在其他程序粘贴

**To Reproduce / 复现过程**
在聊天中发的各种图片，右键复制图片，只能在ica中粘贴，其他程序无法识别到剪贴板中有图片

**Expected behavior / 预期的结果**
在其他程序中可以粘贴，例如画图、微信聊天窗口等

**Screenshots / 截图**
不适用

**System information / 系统信息**
Windows 10 Pro for Workstations 22H2 19045.2251

**Additional context / 附加信息**

**Comment by dmlgzs** [comment]
Microsoft Word 可以正常粘贴

**Comment by orz12** [comment]
有点问题 是点开图片查看详情那里复制不能粘贴 word确实能识别到 估计是去特定url下载的？
