### ISSUE TITLE
[Feature Request] 停止播放表情欄裏的gif表情

### ISSUE THREAD

**Issue by kands-code** [Icalingua-plus-plus/Icalingua-plus-plus#406]
**Is your feature request related to a problem? Please describe.**

如果表情欄裏的gif表情比較多的話，每次打開表情欄都會加載很久，感覺不是很有必要

**Describe the solution you'd like**

或許可以讓gif表情預覽時只顯示第一幀，這樣即可以看到內容，加載也會快很多

**Describe alternatives you've considered**

無

**Additional context**

如果網不好的話還會出現這種情況（

![image](https://user-images.githubusercontent.com/59006329/204437132-d855d5d0-870b-40db-bda3-26197fcdd86b.png)

**Comment by bcegkmqs23** [comment]
也许可以考虑鼠标移动过去才播放

**Comment by kobe-koto** [comment]
lazy load 也挺不錯
