### ISSUE TITLE
[Feature Request] 打开一个聊天窗口时返回上次打开该窗口时时看的最后一条记录

### ISSUE THREAD

**Issue by jiangsy** [Icalingua-plus-plus/Icalingua-plus-plus#408]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
目前打开一个聊天窗口时会直接跳转到最新的聊天记录，希望能够返回上次打开该窗口时看的最后一条记录

**Describe alternatives you've considered**
或者可以添加一个书签功能标记某条聊天记录然后可以直接跳转

**Comment by Icalinguaplusplus** [comment]
7d40ab45867f85fc6f296166463976bcf3523fe2
