### ISSUE TITLE
[BUG] 會把各種神奇的東西識別成鏈接

### ISSUE THREAD

**Issue by LS-KR** [Icalingua-plus-plus/Icalingua-plus-plus#41]
**Describe the bug / 描述**  
在聊天過程中，特別是在交流代碼的時候，經常會將各種東西識別成鏈接造成可讀性下降  

**To Reproduce / 复现过程**  
例如，可以發送一段`System.Windows.Application.Current.Shutdown()`，會發現它將`System.Windows`識別成了網頁鏈接  

**Screenshots / 截图**
像這樣，它把代碼塊中的`exit.Click`和`System.Windows`識別成了鏈接  
![图片](https://user-images.githubusercontent.com/64070144/160720395-b1867803-d120-43c8-8450-0909ffaea1ca.png)  
同樣，甚至連用戶名也會被識別:  
![图片](https://user-images.githubusercontent.com/64070144/160720615-8142a531-4b44-4b14-8094-507a7d0f5557.png)

**System information / 系统信息**
 - OS: Windows 11 21H2 22000.556
 - Version 2.5.8

**Additional context / 附加信息**
除Windows以外，在各個Linux版本中也會出現這種問題，包括我正在使用的Arch Linux  
似乎之前的版本也會出現這個問題

**Comment by Icalinguaplusplus** [comment]
不易修復，因為現在的 TLD 太多了，如果修改判斷，會漏判很多新域，例如提到的 `System.Windows` 實際上確實是存在的屬於微軟的鏈接，而 `system.io` 也是正常存在的鏈接

**Comment by LS-KR** [comment]
那麼可不可以用上下文的內容判定是否爲網頁鏈接？比如前面提到的`System.Windows`後面還有一個`.Application`，這明顯不是一個網頁鏈接應有的後綴(或者應該叫"內容"?)；同樣，在前文所提到的`System.IO`後面也有一個`.Exception`，也明顯不是一個網頁鏈接應有的後綴。可以通過這種方式判定是否爲網頁鏈接(?)  

除此以外，我還發現直IP的鏈接不能夠生效，比如`127.0.0.1`  
而添加`http://`後，即變爲`http://127.0.0.1`後，就能夠正常識別，望修復  
![图片](https://user-images.githubusercontent.com/64070144/160791432-dc3cc45c-d99a-47cf-ab79-7d532bf2735a.png)

**Comment by Icalinguaplusplus** [comment]
Icalingua++ 中判定鏈接使用的是 linkifyjs 庫，如果希望能修改規則請到 [linkifyjs 倉庫](https://github.com/Hypercontext/linkifyjs) 反饋，謝謝
