### ISSUE TITLE
[BUG] 在我的文件助手聊天框发出去的消息看不到，但在手机上确能收到

### ISSUE THREAD

**Issue by doveppp** [Icalingua-plus-plus/Icalingua-plus-plus#410]
**Describe the bug / 描述**
win11  aPad模式登录 使用该软件在我的文件助手聊天框发出去的消息在该软件上看不到， 在手机上能收到消息
**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: win11
 - Version 2.7.7

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
新協議已解決
