### ISSUE TITLE
[BUG]重启后，Aria2c每次需要在选项中重新保存才能使用

### ISSUE THREAD

**Issue by MALossov** [Icalingua-plus-plus/Icalingua-plus-plus#412]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
每次重启后，如果要使用aria2c作为下载器，需要先从菜单的选项中，点开aria2c下载器选项并保存，才能正常使用aria2c。
**To Reproduce / 复现过程**
成功连接aria2c之后重启。
**Expected behavior / 预期的结果**
应该自动保存aria2c设置，无需重新启动。

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
【显示published to aria2 json failed.】
**System information / 系统信息**
 - OS: Ubuntu22.04.1
 - Version 2.7.7

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
在之前几代的版本当中，未出现这个问题。

**Comment by bcegkmqs23** [comment]
原因应该是aria2启动时机过晚，而icalingua只会尝试连接一次，如果icalingua启动时aria2尚未启动，则会连接失败需要手动重连。
