### ISSUE TITLE
[BUG]无法发送通知

### ISSUE THREAD

**Issue by cloudw233** [Icalingua-plus-plus/Icalingua-plus-plus#413]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
如题

**To Reproduce / 复现过程**
接收消息

**Expected behavior / 预期的结果**
正常收到通知

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![图片](https://user-images.githubusercontent.com/86039582/205421450-c8b9361d-3d56-42ff-82c9-975714881cb2.png)

**System information / 系统信息**
 - OS: [Windows 11]
 - Version [2.7.7]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
請檢查是否有軟體攔截了 `p.qlogo.cn`
