### ISSUE TITLE
[BUG]无法发起下载

### ISSUE THREAD

**Issue by cloudw233** [Icalingua-plus-plus/Icalingua-plus-plus#414]
**Describe the bug / 描述**
无法下载文件

**To Reproduce / 复现过程**
任意选取一个文件下载

**Expected behavior / 预期的结果**
正常下载文件

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
无截图

**System information / 系统信息**
 - OS: [Windows 11 22H2]
 - Version [2.7.7]

**Additional context / 附加信息**
该BUG是偶然出现的，并非能100%复现

**Comment by Icalinguaplusplus** [comment]
若單擊群文件并未彈出下載確認提示框，則該文件已被刪除或因違規被屏蔽
