### ISSUE TITLE
[Feature Request]希望增加一下快捷键

### ISSUE THREAD

**Issue by Natural12349978** [Icalingua-plus-plus/Icalingua-plus-plus#418]
比如支持自定义快捷键全局启动主界面。比如像真正的浏览器一样Ctrl+Tab、Ctrl+Shift+Tab实现不同会话的切换。再比如单独关闭某个会话的快捷键。尤其是进入主界面不需要去到任务栏。直接快捷键打开会很方便

**Comment by SilentInt** [comment]
来新消息直接用快捷键打开聊天窗口！我也想要这个！

**Comment by ForkKILLET** [comment]
我试着写一下
