### ISSUE TITLE
能否把程序的外框去掉 或者改为和程序内部一致的颜色[Feature Request]

### ISSUE THREAD

**Issue by LEGIONgrl** [Icalingua-plus-plus/Icalingua-plus-plus#420]
看着很别扭
程序内部是深色 外面有个框是浅色

**Comment by LEGIONgrl** [comment]
![Uploading 屏幕截图_20221206_112007.png…]()

**Comment by David-Alfred** [comment]
I am facing with the same problem, too.

**Comment by aimerneige** [comment]
duplicate https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/388

**Comment by iosyyy** [comment]
可以在Icalingua-plus-plus-clone\icalingua\src\main\utils\windowManager.ts中的第27行乃个类的配置中加一个        titleBarOverlay:{
            color:themeColor
        },
应该可以解决问题 具体参考https://www.electronjs.org/zh/docs/latest/api/browser-window

**Comment by sunglove** [comment]
I am facing with the same problem, too.

**Comment by dmlgzs** [comment]
更新 Electron21 即可
