### ISSUE TITLE
[BUG]未修改设置的情况下突然打不开主界面

### ISSUE THREAD

**Issue by AstroNomen** [Icalingua-plus-plus/Icalingua-plus-plus#423]
**Describe the bug / 描述**
点击快捷方式和exe都不能打开主程序，任务管理器显示有后台进程但是没有前台主任务

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/47104966/206586293-4c460243-fc85-4a00-9fad-59ebda187969.png)

**System information / 系统信息**
 - OS: Windows 10 x64
 - Version: 22H2 19045.2311

**Additional context / 附加信息**
距离上次成功打开期间只更新过一次AMD显卡的驱动

**Comment by AstroNomen** [comment]
> **Describe the bug / 描述** 点击快捷方式和exe都不能打开主程序，任务管理器显示有后台进程但是没有前台主任务
> 
> **Screenshots / 截图** ![image](https://user-images.githubusercontent.com/47104966/206586293-4c460243-fc85-4a00-9fad-59ebda187969.png)
> 
> **System information / 系统信息**
> 
> * OS: Windows 10 x64
> * Version: 22H2 19045.2311
> 
> **Additional context / 附加信息** 距离上次成功打开期间只更新过一次AMD显卡的驱动

补充:
1. 在电脑上开了个新的账户环境进行全新安装是正常可用的，排除系统环境问题
2. 没有使用过 `--hide` 参数之类隐藏主窗口（目前是登录窗口就直接不显示，双击图标后毫无反应，只能看到后台有进程）

**Comment by CornWorld** [comment]
我也出现了相同的情况，但是我这里根本不显示图标

![image](https://user-images.githubusercontent.com/43746030/206885243-96e08264-a73d-4a6c-bbba-d387607727ae.png)

ic++ version: 2.7.7
windows version: win server 2012 r2

**Comment by Icalinguaplusplus** [comment]
是否有托盤圖標？若有請檢查配置文件（`%AppData%\icalingua\config.yaml`）中 `winSize` 字段的内容是否正常，若無建議刪除 `%AppData%\icalingua\` 中除去 `data` `databases` `stickers` 等數據以外的所有文件后重試。

**Comment by AstroNomen** [comment]
> 是否有托盤圖標？若有請檢查配置文件（`%AppData%\icalingua\config.yaml`）中 `winSize` 字段的内容是否正常，若無建議刪除 `%AppData%\icalingua\` 中除去 `data` `databases` `stickers` 等數據以外的所有文件后重試。

感谢，已恢复。检查时发现 config.yaml 无法正常打开，似乎值全部为null，在删除所有文件后恢复正常。

**Comment by AstroNomen** [comment]
> 我也出现了相同的情况，但是我这里根本不显示图标
> 
> ![image](https://user-images.githubusercontent.com/43746030/206885243-96e08264-a73d-4a6c-bbba-d387607727ae.png)
> 
> ic++ version: 2.7.7 windows version: win server 2012 r2

我这里也是托盘根本不显示图标，可以参考上面的回答删除文件后应该就正常了。
