### ISSUE TITLE
[Feature Request] 希望增加一个截图工具

### ISSUE THREAD

**Issue by Qicloud-W** [Icalingua-plus-plus/Icalingua-plus-plus#424]
希望新增一个截图工具

**Comment by aimerneige** [comment]
1. Icalingua 是一个 **“会话前端框架”**，截图功能应该由截图软件提供。
2. 使用 electron 实现跨平台的截图功能非常复杂。

**Comment by fwz233** [comment]
各种软件都有截图工具.....应该没必要吧

**Comment by ihuanx** [comment]
确实 自己去下一个截图 又不是刚需

**Comment by xiaole3349** [comment]
建議去下載一個QQ截圖的剝離版

**Comment by KaRuichin** [comment]
> 建議去下載一個QQ截圖的剝離版

https://bbs.pediy.com/thread-271225.htm
