### ISSUE TITLE
文件名相同（内容不同）的文件下载会被互相覆盖[BUG]

### ISSUE THREAD

**Issue by yzjn6** [Icalingua-plus-plus/Icalingua-plus-plus#426]
**Describe the bug / 描述**
下载相同名称的文件,不管内容是否相同，都会被当成同一个文件，互相覆盖，不能同时存在

**To Reproduce / 复现过程**
在下载目录中可以看到新的文件覆盖了旧的文件，最后只剩下新文件。
**Expected behavior / 预期的结果**
预期一：软件能判断两个文件不同，将新的文件重命名（比如："XXXXXX_(1)"）
预期二：直接判断下载目录是否有同名文件，有就重命名（把是否重复下载交由用户自己判断）
预期三：每次下载单独根据时间创建文件夹

**System information / 系统信息**
 - OS: Win10/11 x64
 - Version 2.7.7

**Comment by aimerneige** [comment]
duplicate #384
