### ISSUE TITLE
表情分类功能在过多地方显示[BUG]

### ISSUE THREAD

**Issue by xiaozhangup** [Icalingua-plus-plus/Icalingua-plus-plus#43]
**Describe the bug / 描述**
表情分类功能在过多地方显示

**To Reproduce / 无需

**Expected behavior / 预期的结果**

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/68374769/161302523-c8a1fb72-8c8b-4a53-b4f3-28e681662b86.png)
![image](https://user-images.githubusercontent.com/68374769/161302556-e457883a-d7e5-4461-8fcd-7b8ca3e50541.png)

**Comment by Icalinguaplusplus** [comment]
感謝反饋，此 BUG 昨天已在 dev 修復，今天已發 release (https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/5fee95a46b66f5a78b8e49d207b24b4e8dad1cea)
