### ISSUE TITLE
[BUG] tray icon显示颜色错误

### ISSUE THREAD

**Issue by kands-code** [Icalingua-plus-plus/Icalingua-plus-plus#430]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

在我已经选中使用浅色图标的前提下，icalingua的tray icon还是使用的是深色图标，或者「与系统颜色相反」

**To Reproduce / 复现过程**

我做了个录屏

<details>

[Screencast from 2022-12-13 23-14-16.webm](https://user-images.githubusercontent.com/59006329/207372836-6682d4aa-462a-4e14-bb93-6bffe4225f96.webm)

</details>

打开软件，发现图标颜色不对

**Expected behavior / 预期的结果**

他应该使用浅色图标

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

<details>

![image](https://user-images.githubusercontent.com/59006329/207373307-88154264-228d-4a1c-a650-daccd9d0bf0b.png)

</details>

**System information / 系统信息**
 - OS: [e.g. Arch Linux] Arch
    ```text
    kands@ksc 
    OWOS: Arch Linux 
    MOWODEL: 81YN Lenovo XiaoXinAir-14ARE 2020 
    KEWNEL: 6.1.0-zen1-1-zen 
    SHEWW: /bin/bash 
    CPUWU: AMD Ryzen 5 4600U with Radeon Graphics [42.1°C] 
    GPUWU: AMD ATI 04:00.0 Renoir 
    MEMOWY: 3.86GiB / 15.00GiB (25%) 
    PKGS: 1186 (pacman), 27 (flatpak) 
    ```
 - Version [e.g. 2.1.4] 2.7.8

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

我使用的是 **AppImage** 版本，与系统 _electron_ 版本应该无关，而且我系统上没有全局安装的 _electron_

**Comment by kands-code** [comment]
注：我已经确认，`config.yaml` 里的设置没有问题，和tray menu显示的是一致的

![image](https://user-images.githubusercontent.com/59006329/207380752-9c667c2a-ea1d-4d6f-9729-0e8ac7e684ff.png)

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/f4a2ed83b2343a7b13a7cea1ec4a149ba24da880

**Comment by kands-code** [comment]
> [f4a2ed8](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/f4a2ed83b2343a7b13a7cea1ec4a149ba24da880)

但是我这里这个情况是可以复现的，这个问题在 `2.7.7` 没有问题，但是在 `2.7.8` 是存在的
