### ISSUE TITLE
[BUG] 托盘图标不更新

### ISSUE THREAD

**Issue by xiaozhangup** [Icalingua-plus-plus/Icalingua-plus-plus#432]
**Describe the bug / 描述**
托盘图标小红点在我读完所有消息后，依然显示

**To Reproduce / 复现过程**
打开，让好朋友给你发个消息使红点亮起，打开最新的消息

**Expected behavior / 预期的结果**
在我看完所有未读消息时，红点应该小时

**Screenshots / 截图**
![图片](https://user-images.githubusercontent.com/68374769/207470233-4eed32b9-392f-4ea1-aca4-c92edcbc42cb.png)

**System information / 系统信息**
Fedora 37

**Comment by Icalinguaplusplus** [comment]
bfe98cc2b614781dc68fd1ce132c6d69685fb662
