### ISSUE TITLE
[BUG] 2.7.8托盘图标颜色不能记忆上次设置

### ISSUE THREAD

**Issue by ChongChengAC** [Icalingua-plus-plus/Icalingua-plus-plus#433]
**Describe the bug / 描述**
更新2.7.8后无法记住托盘图标颜色，每次打开都是深色图标的样子（尽管设置里显示的依然是浅色）

**To Reproduce / 复现过程**
更新后每次打开icalingua都会这样

**Expected behavior / 预期的结果**
每次打开icalingua后都像第一张图一样

**Screenshots / 截图**
这是浅色图标在我的系统上正常时候的样子：
![image](https://user-images.githubusercontent.com/63496547/207528588-3a3b50ba-d6a5-4e07-b97a-44284b114cfe.png)

更新2.7.8后每次打开都是深色图标的样子，需要手动点一下“浅色图标”才会变成浅色图标：
![image](https://user-images.githubusercontent.com/63496547/207528420-3958a563-614b-4597-bc36-967521b17c06.png)

**System information / 系统信息**
 - OS: Manjaro Linux Xfce
 - Version 2.7.8-1 (AUR)

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/430#issuecomment-1348876191
