### ISSUE TITLE
[Feature Request] 希望能跳转到AT我和全体成员的位置

### ISSUE THREAD

**Issue by teglaven** [Icalingua-plus-plus/Icalingua-plus-plus#434]
目前这个软件稚嫩跳转到最早未读消息，在群聊里有人@我或@全体成员的话无法快速跳转到该消息。
或者也有可能是跳转的按钮很不明显。

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/23457b61608128091fdaf8b3930a2e3fd9478684
