### ISSUE TITLE
[BUG] 2.8.1 版本可能有内存泄漏的问题

### ISSUE THREAD

**Issue by jyi2ya** [Icalingua-plus-plus/Icalingua-plus-plus#435]
**Describe the bug / 描述**

icalingua 使用的虚拟内存数量明显不正常。

**To Reproduce / 复现过程**

运行 icalingua 大约三天，然后使用 `htop` 命令观察 icalingua 所对应一栏的 `VIRT` 项目。

**Expected behavior / 预期的结果**

使用的虚拟内存数量看起来比较合理。

**Screenshots / 截图**

![scrshot](https://user-images.githubusercontent.com/86813521/208061624-747f94aa-c894-4b2d-9a5a-0d27a4c819a5.png)

虽然我不太理解这是什么意思，但是这个数值是其他进程的几百倍甚至上千倍，怎么看也不对。

**System information / 系统信息**
 - OS: Debian GNU/Linux bookworm/sid
 - Version 2.8.1

**Additional context / 附加信息**

**Comment by soloopooo** [comment]
RES 才是进程实际使用的内存
VIRT 是程序请求分配的内存，chromium下长时间运行1000GB很正常，请求分配在64位下可以分配到16EB 16777216TB

**Comment by jyi2ya** [comment]
> RES 才是进程实际使用的内存 VIRT 是程序请求分配的内存，chromium下长时间运行1000GB很正常，请求分配在64位下可以分配到16EB 16777216TB

我明白了，谢谢你！
