### ISSUE TITLE
[Feature Request]群文件支持查看发送者和不同方式排序

### ISSUE THREAD

**Issue by FFDVDGD** [Icalingua-plus-plus/Icalingua-plus-plus#441]
**Is your feature request related to a problem? Please describe.**
查看群文件时不知道是谁发的，老师发的卷子标题都一个样(っ °Д °;)っ。
当知道文件是谁发的但是不知道发送日期或日期久远时按时间排序就显得比较麻烦

**Describe the solution you'd like**
支持显示群文件的发送者并且可以以日期、文件名、发送者（或其他）的方式排序或筛选

**Describe alternatives you've considered**

**Additional context**

**Comment by Icalinguaplusplus** [comment]
3570caeca3aa491b5e7fc91ba6aaeebfdb1467ac
