### ISSUE TITLE
[Feature Request]两个功能请求

### ISSUE THREAD

**Issue by Xagher** [Icalingua-plus-plus/Icalingua-plus-plus#447]
**Is your feature request related to a problem? Please describe.**
1.无群文件搜索功能
2.习惯于Ctrl+Enter发送，但是默认其为换行

**Describe the solution you'd like**
1.添加群文件搜索
2.加入输入习惯的自定义设置

**Describe alternatives you've considered**
略

**Additional context**
社区开发者们辛苦了
我能力不够就不提交pr了

**Comment by Puqns67** [comment]
有关于第二项
![image](https://user-images.githubusercontent.com/57405236/209440137-ed7e1870-3288-45eb-b3ac-52000344b7b3.png)
