### ISSUE TITLE
[Feature Request]希望添加有关频道的功能

### ISSUE THREAD

**Issue by sf467** [Icalingua-plus-plus/Icalingua-plus-plus#449]
希望添加有关频道的功能，非常感谢

**Comment by sf467** [comment]
> 希望添加有关频道的功能，非常感谢
这个软件真的非常好

**Comment by Icalinguaplusplus** [comment]
频道不会添加了，目前也没有完整且完美的协议实现
另外官方已经发布正式版 QQ 且支持频道了

**Comment by MomentQYC** [comment]
> 另外官方已经发布正式版 QQ 且支持频道了

很多人用这个就是为了不用官方的QQ
