### ISSUE TITLE
[BUG]Windows下触摸时打开菜单位置不跟随手指而是在原来鼠标的位置

### ISSUE THREAD

**Issue by KrisowX** [Icalingua-plus-plus/Icalingua-plus-plus#45]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
Windows下触摸时打开菜单位置不跟随手指而是在原来鼠标的位置

**To Reproduce / 复现过程**
1.使用一台带有触摸屏的Windows设备
2.打开一个聊天窗口
3.点击右上角"..."
4.发现问题

**Expected behavior / 预期的结果**
使用带有触摸屏的设备时，打开的菜单跟随手指点击位置。

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://user-images.githubusercontent.com/58591281/161397209-fcbf5829-496f-4b39-9c3f-9051a1a53459.png)

**System information / 系统信息**
 - OS: Windows11
 - Version build.22000.593

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by KrisowX** [comment]
建议把跟随鼠标打开菜单改成固定位置打开菜单，这样也不用加对应触摸的部分了

**Comment by Icalinguaplusplus** [comment]
暫不考慮支持 Windows 觸摸屏設備

**Comment by qwqVictor** [comment]
@KrisowX 这个行为是 electron 框架导致的，electron 的 `menu.popup` 方法默认会获取当前鼠标坐标并弹出窗口，且目前来看若指定坐标 (x, y) 需为绝对坐标，感觉比较难以处理。如果有合理的方式的话我可能会修掉（作为一个 Windows 平板用户
