### ISSUE TITLE
[BUG]关于icalingua++-2.8.2-1无法预览图片的bug 

### ISSUE THREAD

**Issue by Frank-Wang-2007** [Icalingua-plus-plus/Icalingua-plus-plus#450]
**Describe the bug / 描述**
icalingua++-2.8.2-1无法预览图片

**To Reproduce / 复现过程**
单击群聊中的聊天图片，弹出的对话框中只有js代码

**Expected behavior / 预期的结果**
单击图片弹出预览窗口

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/70057967/209462104-2dd16bce-0098-40dc-83bb-c96f3736a1be.png)

**System information / 系统信息**
 - OS: Archlinux 
 - Version 6.0.12-arch1-1

**Comment by ForkKILLET** [comment]
未能复现，你重启一下 icalingua 试试？

**Comment by dmlgzs** [comment]
更新后需要重启
