### ISSUE TITLE
[Feature Request]新功能请求

### ISSUE THREAD

**Issue by AeroBeats** [Icalingua-plus-plus/Icalingua-plus-plus#452]
**Is your feature request related to a problem? Please describe.**
现在有分组功能但是好像并不能直观反映每个分组是否有未读消息

**Describe the solution you'd like**
在分组图标上加个表示未读消息提醒/数量的小圆点

**Describe alternatives you've considered**

**Additional context**
辛苦各位大大了
阿里嘎多

**Comment by ForkKILLET** [comment]
在写啦

**Comment by AeroBeats** [comment]
还有那个分组功能用了之后感觉咱还是再写个群助手吧，不然我这种群又多群友话也多的人要是有人突然找到我我要在all chats里翻好久才能翻到是谁给我发消息😭
