### ISSUE TITLE
[BUG] 群名称包含有 emoji 时标题栏显示异常

### ISSUE THREAD

**Issue by aimerneige** [Icalingua-plus-plus/Icalingua-plus-plus#46]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

如图，群名称包含有 emoji 时标题栏显示异常

![image](https://user-images.githubusercontent.com/51701792/161412093-e2492cb7-6efa-443e-8e47-89ba0d407606.png)

**To Reproduce / 复现过程**

群名称修改为包含有 emoji 的内容。

**Expected behavior / 预期的结果**

可以正常显示完整群名称

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

上附

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]

- OS: `Pop!_OS 21.10`
- Version: `2.6.1`

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
無法復現，初步判斷為系統字體/窗口管理器問題，與 Icalingua++ 無關

**Comment by aimerneige** [comment]
已证实，显示异常系**系统字体配置**问题，与 icalingua 无关。
