### ISSUE TITLE
[Feature Request]希望可以在查看图片界面为 Mac 触控板增加支持

### ISSUE THREAD

**Issue by Mindigma** [Icalingua-plus-plus/Icalingua-plus-plus#463]
希望添加下面的支持：
1. 可以使用双指在触控板上划动来划动图片（就是和在触控屏设备上单指划动一样）
2. 可以用两指 分开 / 合拢 来实现 放大 / 缩小 图片

**Comment by Icalinguaplusplus** [comment]
目前按住 Shift 键应该就能滑动图片了
