### ISSUE TITLE
[BUG]表情包没有同步

### ISSUE THREAD

**Issue by endercatone** [Icalingua-plus-plus/Icalingua-plus-plus#464]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
Icalingua++的remote表情包没有自动同步，也不能手动同步

**To Reproduce / 复现过程**
Icalingua++开着，在手机或其他电脑上传表情包，Icalingua++没有自动同步或者手动同步的功能，只能重启Icalingua++才能看到

**Expected behavior / 预期的结果**
可以自动同步或者有一个功能可以手动同步

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS:  Manjaro
 - Version: 2.8.2

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
oicq 提供的接口似乎无法获取到最新的，只能重启

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/0e2ce08032d96eb60bd7e1ab2d10dd0d3a78a858
