### ISSUE TITLE
[BUG] 成员活跃数据显示异常

### ISSUE THREAD

**Issue by xgugugu** [Icalingua-plus-plus/Icalingua-plus-plus#466]
**Describe the bug / 描述**

成员活跃数据显示异常

**To Reproduce / 复现过程**

![图片](https://user-images.githubusercontent.com/85472190/209607089-33b631ef-2722-4dcb-a77f-f84778926506.png)

![图片](https://user-images.githubusercontent.com/85472190/209607123-1a86f921-de18-44b0-a78a-ae99d5c6ec45.png)

**Expected behavior / 预期的结果**

能正常显示

**System information / 系统信息**
 - OS: Manjaro
 - Version 2.8.2

**Comment by dmlgzs** [comment]
这个只有管理员能看（

**Comment by xgugugu** [comment]
> 这个只有管理员能看（

但是我记得以前的版本是能正常显示的

**Comment by dmlgzs** [comment]
> > 这个只有管理员能看（
> 
> 但是我记得以前的版本是能正常显示的

只有你是管理员的时候才能显示
而且这个在手机QQ是管理群的界面里才有的
至于为什么应该去问腾讯
