### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by duziduzi** [Icalingua-plus-plus/Icalingua-plus-plus#468]
win11arm，用的也是ARM版，最新的2.8.3无法登录，显示连接失败，换回2.8.1就可以

**Comment by LatencyHearn** [comment]
同样的，win11arm专业版，最新的2.8.3无法登陆，显示链接失败，使用的是默认sqlite，但是2.82可以正常使用

**Comment by LatencyHearn** [comment]
> win11arm，用的也是ARM版，最新的2.8.3无法登录，显示连接失败，换回2.8.1就可以

请问您现在可以使用2.8.3了嘛，我还在用2.8.2，此版本可以正常使用

**Comment by Icalinguaplusplus** [comment]
474235fc5108445c6efb3c273f62073219d557ba
