### ISSUE TITLE
[Feature Request]关于获取历史信息，希望优先同步私聊，

### ISSUE THREAD

**Issue by WAYYYAW** [Icalingua-plus-plus/Icalingua-plus-plus#470]
现象：启动一大晌，一直在同步一些99+的大群，获取了上万条历史信息，而私发信息没有及时获得同步
1、希望能优先同步私聊
2、对屏蔽通知的群聊滞后同步
3、或者增加选项，让用户自己设置获取历史信息次序
感谢

**Comment by Mindigma** [comment]
> 现象：启动一大晌，一直在同步一些99+的大群，获取了上万条历史信息，而私发信息没有及时获得同步 1、希望能优先同步私聊 2、对屏蔽通知的群聊滞后同步 3、或者增加选项，让用户自己设置获取历史信息次序 感谢

在 2.8.2 版本的时候（2.8.3 不知道有没有），如果是第一次触发启动后自动获取历史消息的话，那么那个数字会一直上涨，然后过一会儿就会重置，因为那个会话已经获取完了，解决方法为重启 ica++，然后十几秒就获取成功了。
