### ISSUE TITLE
[BUG]转发某些类型文件时 icalingua++ 不会同步该消息，同时提一个建议

### ISSUE THREAD

**Issue by worksoup** [Icalingua-plus-plus/Icalingua-plus-plus#471]
**描述**
在真实 Android Phone 上向私聊转发某些类型的文件时，比如 `*.txt` ， icalingua++ 不会同步该消息。但是另一些类型的文件，如 `*.apk` 等则会同步。

**复现过程**
在某群内发送某文本文件，然后在手机上转发给某私聊， icalingua++ 无法同步该条消息。

**预期的结果**
和其它消息或是其他客户端一样同步了该消息。或者干脆不显示，毕竟 icalingua++ 暂时还不支持私发文件。

**系统信息**
 - 系统：[Kubuntu]
 - 版本：[22.10]
---
同时建议，由于私聊时接受文件的提示和发送文件的消息几乎一模一样，点击接受文件的提示下载按钮后还会弹出错误提示，如下：

![图片](https://user-images.githubusercontent.com/78455197/209755066-2fbc33ab-7609-44c6-a4c0-6ea9a3eb9a1b.png)

希望能够改进一下。

**Comment by Icalinguaplusplus** [comment]
原因：Android QQ 轉發群文件到私聊的消息有問題無法被 oicq 獲取到，同樣也無法接收他人亦同樣方式轉發的文件，而直接發送或者使用 PCQQ 轉發無此問題。
另外 Icalingua++ 早已支持發送私聊文件
彈窗報錯則是 electron-dl 的問題，暫時無法解決

**Comment by worksoup** [comment]
虽然确实是 electron-dl 的问题，但是这个地方（即，对方接受了文件之后的反馈提示）本不应该有下载按钮吧？🤔
