### ISSUE TITLE
[BUG] 电脑QQ发送的视频以音频文件呈现

### ISSUE THREAD

**Issue by WhatDamon** [Icalingua-plus-plus/Icalingua-plus-plus#472]
**Describe the bug / 描述**
当使用PC版QQ直接拖入视频文件发送，在Icalingua++中则会以音频文件方式呈现

**To Reproduce / 复现过程**
1. 在PC版QQ拖入视频文件发送
2. 在Icalingua++查看
3. 效果呈现

**Expected behavior / 预期的结果**
显示为音频而非视频

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/59256766/209774472-b3b78410-48f4-4694-9cec-018090c3b69d.png)
_这是一个视频文件_

**System information / 系统信息**
 - OS: Windows 11 Dev
 - Version 2.8.3

**Additional context / 附加信息**
文件来源于QQ录屏，在电脑QQ可以正常显示并且点击跳转默认播放器播放

**Comment by Icalinguaplusplus** [comment]
這不是音頻顯示，這是解碼器不支持。
