### ISSUE TITLE
[BUG]对方接收发送的文件会显示错误

### ISSUE THREAD

**Issue by FFDVDGD** [Icalingua-plus-plus/Icalingua-plus-plus#473]
**Describe the bug / 描述**
一下是一段聊天记录，对方接收我发的文件被显示成了对方发送了一个文件
![image](https://user-images.githubusercontent.com/82321430/209831154-523183ca-7472-49e2-bc43-45cd85bb6759.png)

**To Reproduce / 复现过程**
发送文件
对方接收
**Expected behavior / 预期的结果**
正常显示“对方已接收”的提示语
**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/82321430/209831231-39003435-487c-4b34-b1c6-8b94b5808faa.png)

**System information / 系统信息**
 - OS: win11
 - Version 22H2

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
這個不是 BUG，這個是 OICQ 特性

**Comment by aimerneige** [comment]
![image](https://user-images.githubusercontent.com/51701792/210032776-f4968ad0-d421-4e9d-86fe-1c781e7f17ee.png)
