### ISSUE TITLE
[BUG] QQ语音消息下载失败

### ISSUE THREAD

**Issue by Fhokud** [Icalingua-plus-plus/Icalingua-plus-plus#477]
**Describe the bug / 描述**
QQ语音消息下载失败

**Screenshots / 截图**
![图片](https://user-images.githubusercontent.com/62986412/210031037-bb6957b1-04c7-4858-a45c-a7959c237f93.png)

**System information / 系统信息**
 - OS: Win10 22H2
 2.8.3

内置数据库

**Comment by xiaozhangup** [comment]
我时不时也会遇到这个问题，而且视频文件有时候会成白色无法播放

**Comment by Icalinguaplusplus** [comment]
ffmpeg

**Comment by xiaozhangup** [comment]
> ffmpeg

安装了，而且这个是概率失败。
举个例子，第一次打开会话有，关闭，打开，就没了

**Comment by dmlgzs** [comment]
> 举个例子，第一次打开会话有，关闭，打开，就没了

不可能，你打开有语音就说明已经在数据库中了，后面再打开都是一样的

**Comment by xiaozhangup** [comment]
> > 举个例子，第一次打开会话有，关闭，打开，就没了
> 
> 不可能，你打开有语音就说明已经在数据库中了，后面再打开都是一样的

但在我这里确实如此。或者说，有些能获取，有些不能

**Comment by dmlgzs** [comment]
> > > 举个例子，第一次打开会话有，关闭，打开，就没了
> > 
> > 
> > 不可能，你打开有语音就说明已经在数据库中了，后面再打开都是一样的
> 
> 但在我这里确实如此。或者说，有些能获取，有些不能

建议右键重新获取，发下错误信息

**Comment by Light-Century** [comment]
我的是全部无法获取语音。

**Comment by dmlgzs** [comment]
> 我的是全部无法获取语音。

全部无法获取就是你没装 ffmpeg 到环境变量

**Comment by Light-Century** [comment]
> > 我的是全部无法获取语音。
> 
> 全部无法获取就是你没装 ffmpeg 到环境变量

抱歉，忘掉了（

**Comment by xiaozhangup** [comment]
> > > > 举个例子，第一次打开会话有，关闭，打开，就没了
> > > 
> > > 
> > > 不可能，你打开有语音就说明已经在数据库中了，后面再打开都是一样的
> > 
> > 
> > 但在我这里确实如此。或者说，有些能获取，有些不能
> 
> 建议右键重新获取，发下错误信息

![图片](https://user-images.githubusercontent.com/68374769/210599211-c924e2e8-709b-49a4-9b25-153c6486b92d.png)
重新获取多次后正常
