### ISSUE TITLE
[Feature Request] 账号锁定功能

### ISSUE THREAD

**Issue by Ikaleio** [Icalingua-plus-plus/Icalingua-plus-plus#479]
如题

类似于Telegram或原生QQ Ctrl+Alt+L锁定账号

并用本地存储的独立密码解锁

最好能鼠标键盘五分钟无动作自动锁号

谢谢qwq

**Comment by Ikaleio** [comment]
顺带一提 登陆界面能不能设置不保存密码 qwq

**Comment by Mindigma** [comment]
支持

**Comment by Icalinguaplusplus** [comment]
Icalingua 存储的数据均未加密，增加锁定功能意义应该不大（

**Comment by Ikaleio** [comment]
> Icalingua 存储的数据均未加密，增加锁定功能意义应该不大（

主要是防止家长查QQ（

还是很实用的

**Comment by ForkKILLET** [comment]
锁定主要就是用来防止别人偷偷看一眼消息，不加密我倒是觉得无所谓

**Comment by SteveWorkshop** [comment]
> > Icalingua 存储的数据均未加密，增加锁定功能意义应该不大（
> 
> 主要是防止家长查QQ（
> 
> 还是很实用的

很难不赞同

**Comment by Ikaleio** [comment]
@Icalinguaplusplus

**Comment by ForkKILLET** [comment]
我试着写一下
