### ISSUE TITLE
[Feature Request] 增加禁用GPU加速相关命令行参数提示

### ISSUE THREAD

**Issue by chiyuki0325** [Icalingua-plus-plus/Icalingua-plus-plus#48]
**Describe the bug / 描述**
能登录，但前端无法渲染

**To Reproduce / 复现过程**
我啥都没干啊 ... 只是 滚了一下然后重启电脑而已

**Expected behavior / 预期的结果**

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/73830635/161429238-e664483d-6106-4e2c-9d19-30c8aad44183.png)
![image](https://user-images.githubusercontent.com/73830635/161429241-392c4cd6-bf66-4f65-ac21-3ada3971b3f2.png)

**System information / 系统信息**
 - OS: Arch Linux
 - Version 2.6.1
 - PRIME 双显卡，是否使用 prime-run 都会这样

**Comment by chiyuki0325** [comment]
更正 不止icalingua，几乎所有electron都炸了
可能是驱动滚挂了 没事了

**Comment by chiyuki0325** [comment]
经检验为 electron 18 bug。
可以写出禁用 GPU 加速的方法（原版 issue 里有些，但新仓库没有）。
降低到 17.2.0 可以临时解决，但不是长久之计。

**Comment by Icalinguaplusplus** [comment]
此问题与 GPU 加速无关，是因为 Electron 18 移除了 nativeWindowOpen，无法兼容旧应用

**Comment by Icalinguaplusplus** [comment]
由於 Electron 在 v18 中移除了 nativeWindowOpen，無法兼容，使用 Electron 17 即可解決問題。與 GPU 加速無關。
現在 vscode 等均未更換 Electron 18，暫不對 Electron 18 提供支持。

**Comment by Icalinguaplusplus** [comment]
另外 AUR 中的包已經使用 Electron 17，無本問題
