### ISSUE TITLE
[BUG] 发送的消息重复显示两条

### ISSUE THREAD

**Issue by Fhokud** [Icalingua-plus-plus/Icalingua-plus-plus#480]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
发一条消息，显示两条，实际发送一条
**To Reproduce / 复现过程**
发一条消息，概率出现

**Screenshots / 截图**
![图片](https://user-images.githubusercontent.com/62986412/210134510-47d46a58-86c8-4aa7-a120-5e3e40f6a281.png)

**System information / 系统信息**
 Windows10 22H2 
 2.8.3
**Additional context / 附加信息**
内置数据库

**Comment by Icalinguaplusplus** [comment]
6a06833 b130048
