### ISSUE TITLE
[BUG] 发送文件显示本地路径 并未正常发送

### ISSUE THREAD

**Issue by lumineyuri** [Icalingua-plus-plus/Icalingua-plus-plus#481]
**Describe the bug / 描述**
发送文件显示本地路径 通过手机查看发送只显示了文件名

**To Reproduce / 复现过程**
Ubuntu 20.04环境 搭设bridge-oicq 2.8.3

**Expected behavior / 预期的结果**
成功发送文件 并非文件名

**Screenshots / 截图**
![图片](https://files.catbox.moe/ei9s87.gif)

**System information / 系统信息**
 - OS: Ubuntu 20.04
 - Version 2.8.3

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
bridge 并未支持發送文件

**Comment by Icalinguaplusplus** [comment]
正常來説連接 bridge 時發送文件會提示 `Not implicated`，自己改過代碼？

另外，非 bridge 右鍵的地址是本地地址是正常的

**Comment by dmlgzs** [comment]
你这别是自作主张把 oicqAdapter 里的文件的代码复制到 bridge 里用了吧，同机倒是应该没问题，不同机怎么可能找到文件上传

**Comment by htxzdfunny** [comment]
> 正常來説連接 bridge 時發送文件會提示 `Not implicated`，自己改過代碼？
> 
> 另外，非 bridge 右鍵的地址是本地地址是正常的

我这边也是 bridge 2.8.3，同样出现了这个问题且没有出现`Not implicated`。客户端使用的是 release 2.8.3 ，无任何改动

![图片](https://user-images.githubusercontent.com/54425771/210175573-2081ac2c-0916-49dd-94a8-5cbcb8055e53.png)
![图片](https://user-images.githubusercontent.com/54425771/210175577-c3b598b7-6da8-475c-bade-b41caa0faae2.png)

**Comment by dmlgzs** [comment]
> > 正常來説連接 bridge 時發送文件會提示 `Not implicated`，自己改過代碼？
> > 另外，非 bridge 右鍵的地址是本地地址是正常的
> 
> 我这边也是 bridge 2.8.3，同样出现了这个问题且没有出现`Not implicated`。客户端使用的是 release 2.8.3 ，无任何改动
> 
> ![图片](https://user-images.githubusercontent.com/54425771/210175573-2081ac2c-0916-49dd-94a8-5cbcb8055e53.png) ![图片](https://user-images.githubusercontent.com/54425771/210175577-c3b598b7-6da8-475c-bade-b41caa0faae2.png)

这是用什么方法部署的 bridge？

**Comment by lumineyuri** [comment]
> 正常來説連接 bridge 時發送文件會提示 `Not implicated`，自己改過代碼？
> 
> 另外，非 bridge 右鍵的地址是本地地址是正常的

并没有修改 原版代码
