### ISSUE TITLE
[BUG] 多选转发后在QQ或TIM客户端中看到的消息乱序

### ISSUE THREAD

**Issue by humonia-sys** [Icalingua-plus-plus/Icalingua-plus-plus#486]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

**To Reproduce / 复现过程**
发几条消息并且多选转发

**Expected behavior / 预期的结果**
为正确的顺序

**Screenshots / 截图**
![图片](https://user-images.githubusercontent.com/85441099/210215444-90ed7c0a-81a9-4b7e-9472-c3a06c99326f.png)
![图片](https://user-images.githubusercontent.com/85441099/210215466-540f22bd-30f0-4d4e-b160-1e6c28d232d4.png)

**System information / 系统信息**
 - OS: Windows 10

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by dmlgzs** [comment]
并不能复现

**Comment by dmlgzs** [comment]
建议提供转发消息的xml代码

**Comment by humonia-sys** [comment]
> 建议提供转发消息的xml代码



<?xml version="1.0" encoding="utf-8"?>
<msg brief="[聊天记录]" m_fileName="63F1F102-93DF-479E-A6D7-4BC7E562F4FE" action="viewMultiMsg" tSum="3" flag="3" m_resid="i0chYGKx+8yMf5ifhBmB31AnPOBDNUXB2LJ7NqV2tFCT5UznxaB0CBjNnkIuWaIU" serviceID="35" m_fileSize="170"><item layout="1"><title color="#000000" size="34">转发的聊天记录</title><title color="#777777" size="26">Chara_SS: 1</title><title color="#777777" size="26">Chara_SS: 2</title><title color="#777777" size="26">Chara_SS: 3</title><hr></hr><summary color="#808080" size="26">查看3条转发消息</summary></item><source name="聊天记录"></source></msg>

**Comment by dmlgzs** [comment]
并没有乱序问题
![Screenshot_2023-01-03-00-15-25-992_com tencent mobileqq](https://user-images.githubusercontent.com/24828354/210256559-280a4b13-ef29-4953-b278-50a14f36d5c9.jpg)

**Comment by dmlgzs** [comment]
PCQQ 也完全正常
![image](https://user-images.githubusercontent.com/24828354/210257226-9ea4a7f3-4913-4f5c-bf2a-73e23bf508f6.png)

**Comment by humonia-sys** [comment]
奇怪...我再看一下是不是我这边版本的问题

**Comment by humonia-sys** [comment]
![图片](https://user-images.githubusercontent.com/85441099/210288548-b3736f3b-0fdc-4f51-a0bd-c6bff0299d0c.png)
![图片](https://user-images.githubusercontent.com/85441099/210288553-2ccdf7c0-5a4b-49ba-a54b-80511c134994.png)
补充信息:
系统: Windows 10
ICG++版本: 2.8.5
手机系统: iOS 16.0.2
手机QQ版本: v8.9.25.627

**Comment by humonia-sys** [comment]
我觉得这个多多少少带点玄学,将完全相同的文字转给一个群,多数人看到的是正确的1 2 3,而少部分人乱序

**Comment by humonia-sys** [comment]
> ![图片](https://user-images.githubusercontent.com/85441099/210288548-b3736f3b-0fdc-4f51-a0bd-c6bff0299d0c.png) ![图片](https://user-images.githubusercontent.com/85441099/210288553-2ccdf7c0-5a4b-49ba-a54b-80511c134994.png) 补充信息: 系统: Windows 10 ICG++版本: 2.8.5 手机系统: iOS 16.0.2 手机QQ版本: v8.9.25.627

将QQ版本升级到了最新版 v8.9.28.635, 依旧有这个问题

**Comment by humonia-sys** [comment]
我的数个iOS群友都会出现这个问题

**Comment by dmlgzs** [comment]
那只能说是 iOS QQ 的问题，转发中的 protobuf 是按照正确顺序的，官方的 Electron QQ (macOS 和Linux) 也均显示正常
