### ISSUE TITLE
[Feature Request]一个小小的新功能

### ISSUE THREAD

**Issue by AeroBeats** [Icalingua-plus-plus/Icalingua-plus-plus#488]
**Is your feature request related to a problem? Please describe.**
每次更新虽然有提示但是都要到GitHub下载再安装，有那么一点点不方便

**Describe the solution you'd like**
直接在菜单栏里加一栏检查更新，然后比如最小化到应用窗口左下角显示更新进度

**Describe alternatives you've considered**

**Additional context**

**Comment by Icalinguaplusplus** [comment]
软件自己更新自己不现实，如果下载速度慢可以去镜像站（

**Comment by xiaozhangup** [comment]
新LinuxQQ是吧
