### ISSUE TITLE
[Feature Request] 多账号登录的请求

### ISSUE THREAD

**Issue by Huasushis** [Icalingua-plus-plus/Icalingua-plus-plus#489]
我在Windows环境下想同时登录多个QQ号，但是发现并不支持此功能，甚至不能保存多个账号的信息。希望增加此功能，谢谢。

**Comment by dmlgzs** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/197#issuecomment-1253982280
