### ISSUE TITLE
[Feature Request]希望增加主动加好友得功能

### ISSUE THREAD

**Issue by xwy231321** [Icalingua-plus-plus/Icalingua-plus-plus#490]
**Is your feature request related to a problem? Please describe.**
希望可以增加主动搜索和添加好友和添加群聊得功能
**Describe the solution you'd like**
在好友列表旁边加个搜索好友/群  这样就可以了
**Describe alternatives you've considered**
暂无
**Additional context**
暂无

**Comment by Icalinguaplusplus** [comment]
不会增加

**Comment by tenauge** [comment]
我也希望增加主动加好友的功能，让我觉得这款软件能更加完美

**Comment by mengguyi** [comment]
> 我也希望增加主动加好友的功能，让我觉得这款软件能更加完美

bot库不支持吧
