### ISSUE TITLE
本地表情预览部分失效

### ISSUE THREAD

**Issue by SGK2401** [Icalingua-plus-plus/Icalingua-plus-plus#491]
问题: 在切换本地表情分组之后出现部分表情预览无法加载, 且有可见的闪烁

复现: 打开表情页面后切换分组

预期: 正常预览

图片: ![image](https://user-images.githubusercontent.com/82282650/210433674-2680302b-cde4-4d0c-8607-71e0acea4998.png)

- OS: Windows11 21H2 22000.1219
- ICA: 最新构建版(2.8.5)

PS: 鼠标移动至无法加载的表情预览上可以暂时恢复预览, 某些分组下可以直接恢复
PSS: 删除本地表情预览缓存后可以正常显示

**Comment by KagaJiankui** [comment]
退出icalingua++后删除‘C:\Users\你的用户名\AppData\Roaming\icalingua\stickers_preview’文件夹重启icalingua++，等待icalingua重新加载表情缓存，加载完就修复了

**Comment by SGK2401** [comment]
> 退出icalingua++后删除‘C:\Users\你的用户名\AppData\Roaming\icalingua\stickers_preview’文件夹重启icalingua++，等待icalingua重新加载表情缓存，加载完就修复了

是这样解决的, 只是因为清除缓存并重新加载并不会包括本地表情预览缓存所以丢了个issue
以及这应该不是缓存文件的问题.. 就是ICA没有加载. 

刚才看了一眼开发工具的信息, 控制台有file not found err(估计是刚才删缓存的原因), 以及未加载状态的预览在元素视图里面直接是空白(只有分组, 没有内容)(然后鼠标移动到表情上会加载原图片而不是预览, 这大概是为什么挪开就继续不显示)(但是这没法解释为什么看起来和缓存文件损坏了一样. 缓存文件本身是没有损坏的, 可以正常在其他图片软件内打开).

**Comment by SGK2401** [comment]
有可能是chromium的问题? 有些预览文件在ICA的chromium内核里面就是打不开, edge倒是能正常显示.
这方面我不了解...

UserAgent:
ICA: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) icalingua/2.8.5 Chrome/106.0.5249.199 Electron/21.3.3 Safari/537.36`
EDGE: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54`

**Comment by Icalinguaplusplus** [comment]
现在更换缓存生成的触发方式了，应该能缓解
