### ISSUE TITLE
[BUG] 改变窗口大小导致菜单栏和右上角三点图标没有反应

### ISSUE THREAD

**Issue by triccsr** [Icalingua-plus-plus/Icalingua-plus-plus#492]
将窗口从正常大小变成最大化窗口，或从最大化还原后，菜单栏以及聊天窗口右上角的三点图标失效，需要关闭窗口再点击托盘上的icalingua图标才能解决。
**To Reproduce / 复现过程**
正常情况下，左键点击菜单栏或右上角三点图标应该出现功能栏，但假设先在正常大小窗口左键菜单栏或三点图标（此时正常），然后最大化，再左键菜单栏，则没有反应。若先在最大化的窗口左键菜单栏，再还原窗口，然后左键菜单栏，也没有反应。

**System information / 系统信息**
kubuntu22.04 amd64
icalingua++ 2.8.5

**Comment by BenderBlog** [comment]
要不录个视频看看？我感觉 KDE 不应该这样啊(
electron 应用走的是窗口管理器的方框吧。

**Comment by triccsr** [comment]
https://user-images.githubusercontent.com/36883469/211443512-d3c4ccf1-b310-4ef5-a7d4-d9243fc6ee8f.mp4

**Comment by BenderBlog** [comment]
抱歉刚看见。
看上去是 Electron 或者是 KDE 的锅吧，我发现放大后点1次成了点2次。
个人猜测(

**Comment by Icalinguaplusplus** [comment]
应该是 Electron 或者窗口管理器的问题，可以尝试自行更换 Electron 版本尝试
