### ISSUE TITLE
[BUG]消息撤回后聊天列表却显示的还是撤回的消息

### ISSUE THREAD

**Issue by xiaoyv404** [Icalingua-plus-plus/Icalingua-plus-plus#495]
### 现状
![已撤回消息](https://user-images.githubusercontent.com/63290381/210760626-d956b3f2-7854-4fad-a978-4130ab466d91.png)

![依旧还是显示原本的消息](https://user-images.githubusercontent.com/63290381/210760648-7ea051de-6d05-4fcd-9e98-4f7db8395420.png)

### 希望的效果
撤回之后显示最近一个未撤回的消息
或者显示消息已撤回

**Comment by Icalinguaplusplus** [comment]
~~右键都能显示撤回消息的就没必要隐藏了吧~~

**Comment by xiaoyv404** [comment]
~掩耳盗铃一下嘛~

**Comment by shenjackyuanjie** [comment]
掩耳盗铃可还行（

**Comment by dmlgzs** [comment]
~~这是 feature~~
