### ISSUE TITLE
[Feature Request]输入中文时使用英文标点

### ISSUE THREAD

**Issue by north82** [Icalingua-plus-plus/Icalingua-plus-plus#496]
希望可以增加在聊天输入中文时使用英文标点的选项 如同windows提供的那样
![image](https://user-images.githubusercontent.com/64515742/210957874-8e3dcf93-7902-4b94-9525-da7078b20118.png)

**Comment by Icalinguaplusplus** [comment]
¿ 这不是应该去 IME 那边提吗（
