### ISSUE TITLE
[BUG] 有时文件上传会卡住并最终上传失败

### ISSUE THREAD

**Issue by NobodyHere-rrr** [Icalingua-plus-plus/Icalingua-plus-plus#497]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
在上传文件时，有时上传进度会卡在某一进度，然后不再增加，最后报错Unknown Highway Error（每次的错误码不一样，也许和文件类型有关）。

**To Reproduce / 复现过程**
上传文件。

**Expected behavior / 预期的结果**
正常上传文件。

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
<img width="103" alt="截屏2023-01-12 08 02 54" src="https://user-images.githubusercontent.com/62543054/211945023-a5a96ef6-df6d-456a-bcc4-e15baaea7f36.png">
<img width="316" alt="截屏2023-01-12 08 17 16" src="https://user-images.githubusercontent.com/62543054/211945848-c2f112f1-3833-4d61-a208-1bbec7f4d13b.png">
测试文件大小：532.8MB；类型：视频

<img width="95" alt="截屏2023-01-12 08 12 31" src="https://user-images.githubusercontent.com/62543054/211945345-455b06d7-f5cb-46b5-984c-1801582ea8e6.png">
<img width="275" alt="截屏2023-01-12 08 12 55" src="https://user-images.githubusercontent.com/62543054/211945455-8f538917-af0a-4125-969f-d6b5f41fa58b.png">
测试文件大小：540.4MB；类型：压缩包

**System information / 系统信息**
 - OS: [e.g. Arch Linux] macOS
 - Version [e.g. 2.1.4] 一直都有出现（12-13）

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
通常出现该问题的文件较大，但不排除小文件出现相同情况。

**Comment by Icalinguaplusplus** [comment]
~~服务器会抽风~~

**Comment by NobodyHere-rrr** [comment]
但是使用QQ上传时没有出现过类似错误

**Comment by tjw123hh** [comment]
> 

上传和群文件名重复的文件100%复现该问题

**Comment by xiaozhangup** [comment]
有时给朋友传小文件也会这样，但是似乎和文件类型有关

**Comment by Yurinann** [comment]
+1，但尝试重复多次发送同一文件时有概率发送成功，但对方似乎无法接收。
![image](https://user-images.githubusercontent.com/75569395/222890415-2ef5080d-8089-44c7-af26-924f8cfd6ded.png)

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus/commit/8c8682826ca3847ccb11ac6e7722cb6b15fece1c
新版本已修复
