### ISSUE TITLE
[BUG] 登录账号时提示无法连接至数据库

### ISSUE THREAD

**Issue by NobodyHere-rrr** [Icalingua-plus-plus/Icalingua-plus-plus#498]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
登录账号完成验证码后提示“无法连接至数据库”

**To Reproduce / 复现过程**
登录账号，完成验证码

**Expected behavior / 预期的结果**
正常登录

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
<img width="372" alt="截屏2023-01-08 10 14 09" src="https://user-images.githubusercontent.com/62543054/211177823-f62c4b52-24f3-4b5f-9df9-5d28e81a5312.png">

**System information / 系统信息**
 - OS: [e.g. Arch Linux] macOS
 - Version [e.g. 2.1.4] 13.2 (a)

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
曾使用腾讯官方的QQ在该电脑登录过该账号，在系统版本为13.1时并未出现该情况，Icalingua++版本为2.8.5。

**Comment by Icalinguaplusplus** [comment]
请在终端启动并提供日志

**Comment by NobodyHere-rrr** [comment]
objc[1463]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb512700e0) and /Applications/Icalingua++.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x111261328). One of the two will be used. Which one is undefined.
Cannot find an external media player
Cannot find an external image viewer
icalingua> (node:1460) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `Icalingua++ --trace-warnings ...` to show where the warning was created)
{
  self_id: 2570608578,
  time: 1673173797,
  post_type: 'system',
  system_type: 'login',
  sub_type: 'slider',
  url: 'https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=2570608578&sid=2059338143231548197&cap_cd=wZpNzTsuXdALIVqev3d4jAcxfyiyrTxi8KjKALWF-I-BFeX8drIg0Q**&clientype=1&apptype=2'
}
{
  self_id: 2570608578,
  time: 1673173812,
  post_type: 'system',
  system_type: 'login',
  sub_type: 'slider',
  url: 'https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=2570608578&sid=722258358051707700&cap_cd=VveVWmeDATvHC05JOokR1dXBaAcx4-dMkMpK25NmPy1djkPVKUjv8Q**&clientype=1&apptype=2'
}
[Error: select * from sqlite_master where type = 'table' and name = 'dbVersion' - SQLITE_CORRUPT: database disk image is malformed] {
  errno: 11,
  code: 'SQLITE_CORRUPT'
}
(node:1460) UnhandledPromiseRejectionWarning: Error: ERR_FAILED (-2) loading 'file:///Applications/Icalingua++.app/Contents/Resources/app.asar/dist/electron/index.html#/main'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7510)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:165:7885)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at EventEmitter.topLevelDomainCallback (node:domain:152:15)
    at EventEmitter.callbackTrampoline (node:internal/async_hooks:128:24)
(node:1460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by Icalinguaplusplus** [comment]
你的数据库文件损坏了，修复或者删掉重建即可

**Comment by NobodyHere-rrr** [comment]
解决了，感谢
