### ISSUE TITLE
[solve]MySQL数据库连接失败

### ISSUE THREAD

**Issue by flower-elf** [Icalingua-plus-plus/Icalingua-plus-plus#499]
**Describe the bug / 描述**

在登录时出现连接MySQL数据库（本地）失败的问题。但使用Navicat类数据库软件连接正常
且使用其他软件测试，均能成功连接，唯独Icalingua++不行

**To Reproduce / 复现过程**

打开软件登录，数据库选择MySQL，输入服务器地址，密码与数据库名称
扫码
点击已扫码按钮
报错

**Expected behavior / 预期的结果**

可以成功登录并正常使用

**Screenshots / 截图**

无

**System information / 系统信息**
 - OS: Windows 11 Enterprise
 - Version 22623.1095

**Additional context / 附加信息**

使用Windows10 22H2 (19045.2364)测试过问题依旧，防火墙等可能影响的设置已经全部排除
Icalingua++版本：2.8.5

**Comment by Icalinguaplusplus** [comment]
请在终端启动并提供日志

**Comment by flower-elf** [comment]
抱歉打扰了，经过N遍排查后发现是数据库引擎的锅
Icalingua不支持MyISAM引擎
