### ISSUE TITLE
[Feature Request] 更方便的At人，以及群员管理

### ISSUE THREAD

**Issue by just-a-pony** [Icalingua-plus-plus/Icalingua-plus-plus#50]
目前只能右键头像来at某个人，无法通过输入@来at人，如果消息被顶上去了，手动翻到那个人的消息位置也很费事，而且似乎无法at全体
可以考虑增加一个下拉菜单之类， 所有的成员都在拉下来的菜单里面，可以进行搜索成员，并对其操作，at、禁言或者踢出之类

**Comment by Icalinguaplusplus** [comment]
at 全體可直接輸入 `@全体成员 `
at 列表會納入計劃，將在後期實現
