### ISSUE TITLE
对不支持的消息，能否显示原始数据

### ISSUE THREAD

**Issue by SteveWorkshop** [Icalingua-plus-plus/Icalingua-plus-plus#500]
对于群通知，群公告，转发说说等某些非文本信息，能不能给一个查看原始数据的功能，而不是仅仅显示一个[Json]或者[xml]
可以暂时做不到渲染，但好歹显示一下原始数据吧，不然根本看不到是什么消息

**Comment by Icalinguaplusplus** [comment]
右键复制代码即可
