### ISSUE TITLE
希望添加屏幕截图功能

### ISSUE THREAD

**Issue by MengNianxiaoyao** [Icalingua-plus-plus/Icalingua-plus-plus#503]
聊天界面增加屏幕截图功能以及相关的快捷键

**Comment by Mcayear** [comment]
支持，加上裁剪和涂鸦功能就比 window 自带的`win + Prt Sc`更方便了。

**Comment by lambdark** [comment]
没有必要在里面集成截图功能，qq这样做完全是多余的
可以下载[snipaste](https://zh.snipaste.com/)，非常好用

**Comment by Mcayear** [comment]
> 没有必要在里面集成截图功能，qq这样做完全是多余的 可以下载[snipaste](https://zh.snipaste.com/)，非常好用

确实不错🤓

**Comment by Icalinguaplusplus** [comment]
#80
