### ISSUE TITLE
[BUG]嵌套的合并转发消息在qq、tim无法正常显示

### ISSUE THREAD

**Issue by lambdark** [Icalingua-plus-plus/Icalingua-plus-plus#504]
**Describe the bug / 描述**
嵌套的合并转发消息在Icalingua++
正常显示，但在在手机电脑等平台的qq、tim中均无法正常显示

**Screenshots / 截图**
Icalingua++截图
![Icalingua++](https://user-images.githubusercontent.com/62467094/211746963-96624674-1813-4b17-9b50-f4b7621c0cf3.png)
tim截图
![tim](https://user-images.githubusercontent.com/62467094/211747701-a82b717f-f02b-48d0-80c9-b3a2dbbd01a4.png)

**System information / 系统信息**
 - OS: Windows 11
 - Version 2.8.5

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus/commit/87808438b1026af189f7d82304ee0cf64967319f
