### ISSUE TITLE
[BUG] 当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面

### ISSUE THREAD

**Issue by sakuradied** [Icalingua-plus-plus/Icalingua-plus-plus#505]
当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面

![image](https://user-images.githubusercontent.com/48938188/211751287-16b615f0-ae59-490f-95d1-608317c2e312.png)

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [2.8.5-1]

**Comment by Icalinguaplusplus** [comment]
切换协议或生成新的设备信息或许能解决，如果不行可能是账号已经无法使用老协议或被风控

**Comment by sakuradied** [comment]
> 切换协议或生成新的设备信息或许能解决，如果不行可能是账号已经无法使用老协议或被风控切换协议或生成新的设备信息或许能解决，如果不行可能是账号已经无法使用老协议或被风控

已解决,确实如此
