### ISSUE TITLE
[BUG] 表情列表的部分bug

### ISSUE THREAD

**Issue by NobodyHere-rrr** [Icalingua-plus-plus/Icalingua-plus-plus#506]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
如视频。

https://user-images.githubusercontent.com/62543054/211942864-66f56045-3787-473c-bf85-98a26252068e.mp4

https://user-images.githubusercontent.com/62543054/211942886-57965961-2f81-4501-abd7-8eeb7eaa505e.mp4

**To Reproduce / 复现过程**
如视频。
第二个视频的效果是在窗口较小的情况下出现的。

**Expected behavior / 预期的结果**
没有多余的无内容部分，在所有窗口较小的时候都不会出现向下的滑动条

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
如视频。

**System information / 系统信息**
 - OS: [e.g. Arch Linux] macOS 13.2 (b)
 - Version [e.g. 2.1.4] 2.8.5

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
这些BUG不是一定会出现的（或者说没有这么明显），具体触发条件不明。
但是都是因为窗口缩放而导致的。

**Comment by Icalinguaplusplus** [comment]
请录制视频而不是本因淘汰的 gif 动图
另外请不要使用百度网盘，根本无法查看

**Comment by NobodyHere-rrr** [comment]
我也想录视频，但一开始录成动图，后来又没法复现了，今天会尝试复现一下

**Comment by NobodyHere-rrr** [comment]
已更新为视频。

**Comment by Icalinguaplusplus** [comment]
这个是 chromium 的 bug

**Comment by Icalinguaplusplus** [comment]
chromium 渲染的 height 不知道为什么不按照 ComputedStyle 了，而且离谱的是打开 devtools 后就全部正常了
