### ISSUE TITLE
[BUG]消息撤回成功后仍然显示Failed to delete message

### ISSUE THREAD

**Issue by lambdark** [Icalingua-plus-plus/Icalingua-plus-plus#508]
**Describe the bug / 描述**
消息撤回成功后仍然显示
Failed to delete message
unknown

**Expected behavior / 预期的结果**
撤回消息，不显示失败提示

**System information / 系统信息**
 - 2.8.5

**Comment by Icalinguaplusplus** [comment]
私聊消息特性，不是 bug
因为不返回数据
