### ISSUE TITLE
[BUG] 2.8.5在Windows 10下启动无界面

### ISSUE THREAD

**Issue by Afefegeb** [Icalingua-plus-plus/Icalingua-plus-plus#509]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
2.8.5在Windows 10下启动无界面

**To Reproduce / 复现过程**
启动

**Expected behavior / 预期的结果**
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![图片](https://user-images.githubusercontent.com/69704410/212224203-7642bb6a-1653-4388-9fc6-56dcd0e0f97b.png)

**System information / 系统信息**
 - OS: [e.g. Arch Linux] Windows 10 22H2
 - Version [e.g. 2.1.4] 2.8.5

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
你的配置文件有问题，请检查 `%AppData\icalingua\` 中的配置文件

**Comment by Afefegeb** [comment]
感谢，已解决
