### ISSUE TITLE
[Feature Request] 静默启动

### ISSUE THREAD

**Issue by freeze-dolphin** [Icalingua-plus-plus/Icalingua-plus-plus#51]
默认启动时会直接弹出主界面

如果有开机启动 ical 的需求，就会导致开机蹦出主界面，不美观

**Comment by Icalinguaplusplus** [comment]
啟動時增加 `--hide` 即可隱藏主界面

**Comment by deorth-kku** [comment]
> 啟動時增加 `--hide` 即可隱藏主界面

可否考虑在readme或者wiki说明命令行选项？
