### ISSUE TITLE
[Feature Request] 请求完善窗口抖动行为

### ISSUE THREAD

**Issue by dbxxx-ac** [Icalingua-plus-plus/Icalingua-plus-plus#516]
目前好友发窗口抖动时，只会将原本最小化或关闭的窗口显示，请求完善并增加以下行为：

- 当窗口处于显示状态但不在最顶部时，将其调整为最顶部；
- 自动将聊天窗口调整到发窗口抖动的好友一方。

谢谢！

**Comment by Icalinguaplusplus** [comment]
d773928b
