### ISSUE TITLE
[BUG] 安装后找不到主程序exe

### ISSUE THREAD

**Issue by Mashirl** [Icalingua-plus-plus/Icalingua-plus-plus#518]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug 
安装后找不到主程序exe

**To Reproduce / 复现过程**
下载Icalingua++-2.8.6_arm64.exe 并安装

**Expected behavior / 预期的结果** 
正常启动程序

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![Screenshot 2023-01-19 1](https://user-images.githubusercontent.com/36019702/213348760-d13e33cd-a476-41c0-be82-f52d4c071507.png)

![Screenshot 2023-01-19 2](https://user-images.githubusercontent.com/36019702/213348510-0edfdf39-26d4-4ebd-a021-c5c2aab0a052.png)
-4bb3-861f-fb8e67655bab.png)

**System information / 系统信息**
 - OS: Windows 11 Version 22H2
 - Version 2.8.6

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
你下载的架构版本错了

**Comment by Mashirl** [comment]
> 你下载的架构版本错了

见笑了，我第一眼看成了amd64
