### ISSUE TITLE
[BUG]含有QLottie超级表情的群聊会话加载速度无法接受。

### ISSUE THREAD

**Issue by worksoup** [Icalingua-plus-plus/Icalingua-plus-plus#519]
**Describe the bug / 描述**
当加载的会话记录中含有QLottie超级表情时，加载该会话所需的时间远远大于其他会话。尤其是篮球的表情（QLottie:13,114），感觉上要比其他表情加载所需的时间更长。
严重影响使用体验。有时甚至会导致客户端崩溃。

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: Kubuntu
 - Version 22.10

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
71ade7f39230878ec6df7ac4d7fd560069c32ffc 禁用即可
