### ISSUE TITLE
[BUG]在macOS平台勾选“默认使用本地图片查看器”后单击图片提示“找不到本地图片查看器”

### ISSUE THREAD

**Issue by AlwaysGuu** [Icalingua-plus-plus/Icalingua-plus-plus#524]
**Describe the bug / 描述**
在macOS上使用“默认使用本地图片查看器”时提示“找不到可用的本地查看器”，将图片下载到本地后可以使用macOS内置的“Preview”正常打开，系统已经将Preview设置为默认图片查看器。

**To Reproduce / 复现过程**
在菜单栏启用“默认使用本地图片查看器”后，单击群聊内图片均提示“找不到可用的本地查看器”。

**Screenshots / 截图**
<img width="397" alt="Screenshot 2023-01-23 at 22 11 11" src="https://user-images.githubusercontent.com/47023706/214061086-978b4570-4b99-45a1-850d-d2b6a238d0de.png">
<img width="401" alt="Screenshot 2023-01-23 at 22 11 14" src="https://user-images.githubusercontent.com/47023706/214061101-b8472637-deb0-452a-a39f-035102b0b08b.png">
实际系统已将Preview设置为默认图片查看器，并且可以正常预览下载后的图片。
<img width="263" alt="Screenshot 2023-01-23 at 22 12 38" src="https://user-images.githubusercontent.com/47023706/214061258-11488fe5-cc98-404b-bb12-812338b0e76f.png">

**System information / 系统信息**
 - OS: macOS 13.1
 - Version: 2.8.6

**Comment by synthale** [comment]
@AlwaysGuu 
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/blob/develop/icalingua/src/main/ipc/openImage.ts#L16
似乎这些是检测的图片查看器列表

**Comment by AlwaysGuu** [comment]
> @AlwaysGuu 
> 
> https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/blob/develop/icalingua/src/main/ipc/openImage.ts#L16
> 
> 似乎这些是检测的图片查看器列表

不过感觉提供一个打开图片软件的设置功能会更完善点

**Comment by ManiaciaChao** [comment]
可以考虑 Linux 下使用 xdg-open（不过有些发行版没有预装 xdg-utils），macOS 下使用 open 命令。
