### ISSUE TITLE
[BUG]希望输入“@全体成员”文本后不要自动@全体成员

### ISSUE THREAD

**Issue by i35010u** [Icalingua-plus-plus/Icalingua-plus-plus#525]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
输入“@全体成员”文本后会自动@全体成员
**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: Windows
 - Version 2.8.5

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
真的很烦，不知不觉就给整个群发通知了

**Comment by yeeyuechen** [comment]
所以你@了全体成员
不@全体成员你想干嘛()
请不要提无意义的issue

**Comment by i35010u** [comment]
> 所以你@了全体成员 不@全体成员你想干嘛() 请不要提无意义的issue

我只是想输入“@全体成员”这几个字（

**Comment by xiaozhangup** [comment]
有时确实有用，但是这个功能实现起来感觉不是太容易【

**Comment by i35010u** [comment]
> 有时确实有用，但是这个功能实现起来感觉不是太容易【

但是给个开关来关闭识别“@全体成员”的功能就行了吧（

**Comment by xiaozhangup** [comment]
> > 有时确实有用，但是这个功能实现起来感觉不是太容易【
> 
> 但是给个开关来关闭识别“@全体成员”的功能就行了吧（

这个开关放哪呢（
如果有时真的要at全体还得开一次未免太淦

**Comment by i35010u** [comment]
> > > 有时确实有用，但是这个功能实现起来感觉不是太容易【
> > 
> > 
> > 但是给个开关来关闭识别“@全体成员”的功能就行了吧（
> 
> 这个开关放哪呢（ 如果有时真的要at全体还得开一次未免太淦

工具栏最左边Icalingua++那里吧（

**Comment by xiaozhangup** [comment]
> > > > 有时确实有用，但是这个功能实现起来感觉不是太容易【
> > > 
> > > 
> > > 但是给个开关来关闭识别“@全体成员”的功能就行了吧（
> > 
> > 
> > 这个开关放哪呢（ 如果有时真的要at全体还得开一次未免太淦
> 
> 工具栏最左边Icalingua++那里吧（

cancanneed

**Comment by yeeyuechen** [comment]
> > 所以你@了全体成员 不@全体成员你想干嘛() 请不要提无意义的issue
> 
> 我只是想输入“@全体成员”这几个字（

可是你为什么不能。。。
换一种写法？
例如at全体成员
我觉得你这个issue确实提的有些水了

**Comment by WAAutoMaton** [comment]
如果我没记错的话，QQ官方客户端也是差不多的行为，直接输“@全体成员”就会转换成真正的@，需要一些特殊操作才能避免转换。

**Comment by i35010u** [comment]
> 如果我没记错的话，QQ官方客户端也是差不多的行为，直接输“@全体成员”就会转换成真正的@，需要一些特殊操作才能避免转换。

但是在Icalingua++中无法避免。。。我记得官方端只要在出现@选择菜单时，点一下输入框就可以避免了？

**Comment by ForkKILLET** [comment]
虽然意义不大，但确实是一个存在的问题。
