### ISSUE TITLE
[Feature Request]移动端支持/导出移动端可用登录信息

### ISSUE THREAD

**Issue by yunbian123** [Icalingua-plus-plus/Icalingua-plus-plus#527]
在桌面端基本上已经可以替代日常使用了，但是移动端依然缺失
再加上移动端只剩下巨大的QQ了，原有的轻聊版和HD版已经无法登录。
不知道有没有扩展支持到移动端的计划，或者添加导出可以给旧版本使用的登录信息的功能来曲线救国

**Comment by Icalinguaplusplus** [comment]
手机 QQ 的登录信息应该是加密的吧，没办法导出
移动端支持应该不太可行了，由于是 Electron 应用，应该只能全部重构
