### ISSUE TITLE
[BUG] 自定义插件错误

### ISSUE THREAD

**Issue by shenjackyuanjie** [Icalingua-plus-plus/Icalingua-plus-plus#535]
目前最新commit（https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/a3f6df61e50bfa200b201eada6b94c291dbbd473 ）
打开自定义插件功能之后仍然会报 自定义插件错误
![image](https://user-images.githubusercontent.com/54507071/215805583-4e3ab596-002e-46fc-9d8c-33e2431a525a.png)

**Comment by shenjackyuanjie** [comment]
![image](https://user-images.githubusercontent.com/54507071/215811319-1cb9cd06-37bf-4535-9908-5c2412b0643b.png)
以及我查了一下源码，看到了这东西
![image](https://user-images.githubusercontent.com/54507071/215811498-7dae29d3-76fb-43e8-a2f3-69bae7d373b7.png)
但很明显 没log出来

**Comment by shenjackyuanjie** [comment]
有需求~（
以及范例插件不起作用（tsc编译之后直接报错，放到data里依然出错

**Comment by dmlgzs** [comment]
> 有需求~（ 以及范例插件不起作用（tsc编译之后直接报错，放到data里依然出错

文档里是与 data 目录同级存放而不是放到这个目录里面

**Comment by dmlgzs** [comment]
>  但很明显 没log出来

log 需要在终端中启动才能看，devtools 只能看前端的 log
如果是 bridge 则会直接输出到控制台

**Comment by ForkKILLET** [comment]
看不到错误可以 `messageError(e+'')`（
