### ISSUE TITLE
[BUG] 无法发送图片

### ISSUE THREAD

**Issue by Wishing-Qi** [Icalingua-plus-plus/Icalingua-plus-plus#538]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
无法发送本地图片/Windows截图
**To Reproduce / 复现过程**
截图并黏贴到输入框/使用附件发送本地图片
**Expected behavior / 预期的结果**
图片裂了，在本机及远程均有同样情况，图片链接404，同时放在sticker文件夹下的图片概率发送成功
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://user-images.githubusercontent.com/53641728/215998330-632ac2ec-d46a-4f44-97c7-6ce2b4d6eba3.png)

**System information / 系统信息**
 - OS:Windows 10 专业版
 - Version 22H2 19045.2486

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
安装时选择过为所有人安装和仅为我安装，也试着更改过安装路径，问题依旧

**Comment by Wishing-Qi** [comment]
补充：若发送图片时非位于最新消息处，则有大概率成功

**Comment by Wishing-Qi** [comment]
![image](https://user-images.githubusercontent.com/53641728/216000405-cc28dd56-efc9-415e-83f3-989e24f9dec9.png)

**Comment by Wishing-Qi** [comment]
![image](https://user-images.githubusercontent.com/53641728/216000460-817cf4b2-a1c1-49cc-9cb3-7903969464a0.png)

**Comment by Icalinguaplusplus** [comment]
图片过大会被服务器拒绝上传，请使用文件发送（右键附件图标上传文件）

**Comment by Wishing-Qi** [comment]
10k左右的截图应该不算大吧
而且同一图片，放在sticker文件夹里能发出去，直接发就发不出去了，这么玄学的吗

**Comment by Icalinguaplusplus** [comment]
请提供无法发送的图片、MD5 及右键复制的 URL
并尝试右键重新获取对应消息

**Comment by Wishing-Qi** [comment]
![logo-homepage-hero@2x 00617950](https://user-images.githubusercontent.com/53641728/216006771-3b1aded6-f537-4f66-945e-39b357c15de1.png)

URL https://gchat.qpic.cn/gchatpic_new/0/0-0-E845AE3FEA7F344884E761BAD493EA86/0

MD5 
E845AE3FEA7F344884E761BAD493EA86

**Comment by Wishing-Qi** [comment]
似乎在其他设备发送一次之后，之前的图片也都能恢复显示

**Comment by Icalinguaplusplus** [comment]
用的什么协议？
这个地址明显不是这张图的

**Comment by Wishing-Qi** [comment]
> 用的什么协议？ 这个地址明显不是这张图的

我以为这东西不会恢复，于是找了还灰着的图，后来发现会自动恢复显示，我的问题

**Comment by Wishing-Qi** [comment]
![image](https://user-images.githubusercontent.com/53641728/216008337-a758c9c0-425f-4701-889e-af84998959c0.png)

**Comment by Wishing-Qi** [comment]
现在情况变成了这样，而且似乎恢复了发送其他图片的能力

**Comment by Wishing-Qi** [comment]
![image](https://user-images.githubusercontent.com/53641728/216008569-e5adfa27-1322-4338-bdca-ba6ef1d04e91.png)

**Comment by Icalinguaplusplus** [comment]
那估计是网络问题（
发送的 sticker 默认显示的本地文件所以可以显示，其他的都是重新从服务器获取的

**Comment by Wishing-Qi** [comment]
请问有日志之类的可供发送的材料吗，这看起来是偶发问题

**Comment by Icalinguaplusplus** [comment]
> 请问有日志之类的可供发送的材料吗，这看起来是偶发问题

日志大部分都输出在终端中，部分错误日志可在数据目录里的 Crashpad 中找到

**Comment by Wishing-Qi** [comment]
确实是网络问题，换了网络之后又发不出去了

**Comment by Wishing-Qi** [comment]
方便询问一下这个的数据从哪些服务器走吗

**Comment by Icalinguaplusplus** [comment]
> 方便询问一下这个的数据从哪些服务器走吗

上传服务器是 Uni 包实时提供的，下载服务器是 gchat.qpic.cn。
如果发送的图片其他设备（如用流量的手机 QQ）可以查看，请检查 DNS 问题。

**Comment by Wishing-Qi** [comment]
已解决，不使用223.5.5.5作为DNS后可以正常发送图片

**Comment by KeeLee2005** [comment]
我也无法发送图片，但无论是改DNS并清除DNS缓存，还是把图片复制到icalingua的stickers文件夹下再发送也都不行，但似乎在AppData目录外的图片就可以。
我之前图省空间用mklink创建符号链接把AppData目录下icalingua的缓存文件夹移到了其他盘，也是发送不了截图的图片，把缓存文件夹搬回来后就好了，但第二天又不行了。
截图中可发送的为 E:\下载\常规 目录下，发送不了的在 %userprofile%\Pictures\Screenshots 目录下或者剪切板内的图片文件。
![屏幕截图_20230204_124655](https://user-images.githubusercontent.com/92454987/216749088-2400b648-a8ab-4c52-94cd-29c944ed9b14.png)
是否表明位于绝对路径的图片才可以正常发送？
谢谢
