### ISSUE TITLE
[BUG] 无法成功登录，显示QQ版本过低 / Unable to log in successfully. The QQ version is too low

### ISSUE THREAD

**Issue by baguotao233** [Icalingua-plus-plus/Icalingua-plus-plus#539]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
在输入账号密码选择任意协议均无法登录QQ，显示：[禁止登录]您好，您当前使用的版本过低，前往QQ官网im.qq.com下载新版QQ。

After entering the account password and selecting any protocol, you cannot log in to QQ. The following message is displayed: [Do not log in] Hello, your current version is too low. Go to the QQ official website im.qq.com to download the new version of QQ.

**To Reproduce / 复现过程**

如上所述

As described above

**Expected behavior / 预期的结果**

希望可以修复此问题，并可以正常登录

I hope you can fix this problem and log in normally

**System information / 系统信息**

版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎12/‎6
操作系统版本	22621.1105
设备名称	Dell
处理器	Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.70 GHz
机带 RAM	8.00 GB (7.87 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器

Version Windows 11 Professional
Version 22H2
Installation date: December 6, 2022
Operating system version 22621.1105
Device Name Dell
Processor Intel (R) Core (TM) i5-7200U CPU @ 2.50GHz 2.70 GHz
With RAM 8.00 GB (7.87 GB available)
System type 64-bit operating system, x64-based processor

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/505#issuecomment-1383100403
