### ISSUE TITLE
[Feature Request] Chat-log import and log-viewer

### ISSUE THREAD

**Issue by TomTheDragon** [Icalingua-plus-plus/Icalingua-plus-plus#54]
Since we can only get chat history up to a certain point, i was wondering if a import function of QQ logs could be possible.
QQ itself supports the export of logs in mht, bak and plain txt files.

A simple log viewer similar like the one from QQ, would make this even better :)

**Comment by Icalinguaplusplus** [comment]
The type `bak` of chat records exported by QQ are encrypted and cannot be imported. Other types of files lack some information and cannot be imported.
There is no plan to make a chat history viewer
