### ISSUE TITLE
[BUG]拉伸右侧表情面板影响到左侧列表大小

### ISSUE THREAD

**Issue by MintCoolMC** [Icalingua-plus-plus/Icalingua-plus-plus#542]
**Describe the bug / 描述**
将表情面板向右侧拉伸到最小会使左侧列表变小

**To Reproduce / 复现过程**
打开表情面板，向右侧拉伸到最小

**Expected behavior / 预期的结果**
拉伸到最小后不影响其他面板大小

**System information / 系统信息**
 - OS: Windows 10 22H2
 - Version 2.8.6

**Comment by Icalinguaplusplus** [comment]
28be04a5d06a4465a0f551f5aebceb210b9d109e
