### ISSUE TITLE
[Feature Request]打卡功能 能不能考虑一下

### ISSUE THREAD

**Issue by Chenyu550** [Icalingua-plus-plus/Icalingua-plus-plus#554]
**群打卡功能，成员打卡显示，还有群帖子（妄想），能不能考虑一下**

还有一个，网页应用里面那个群公告只能编辑已有的 没找到在哪里发布

**Comment by dmlgzs** [comment]
发公告滚动到页面底部就有了，在所有已有公告的下面(

**Comment by Chenyu550** [comment]
我这边没显示啊




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Icalingua-plus-plus/Icalingua-plus-plus"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, Feb 10, 2023 06:02 PM
***@***.***&gt;;
Cc:&nbsp;" ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [Icalingua-plus-plus/Icalingua-plus-plus] [Feature Request]打卡功能 能不能考虑一下 (Issue #554)





 
发公告滚动到页面底部就有了，在所有已有公告的下面(

**Comment by Chenyu550** [comment]
> 发公告滚动到页面底部就有了，在所有已有公告的下面(

我这边没显示啊

**Comment by dmlgzs** [comment]
> 我这边没显示啊

所有已有公告下方，如果漫游说明没有发公告权限

**Comment by Chenyu550** [comment]
真没有，我当群主和当管理的群都没有，难不成我找错地方了？<br/><br/><br/><html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
<div class="ntes-mailmaster-quote" style="padding-top: 1px; padding-bottom: 1px" >
    <div style=" margin-top: 20px; margin-bottom: 12px; font-size: 14px; line-height: 1.25; color: #89898c; " >---- 回复的原邮件 ----</div>
    <div style=" margin-bottom: 12px; font-size: 13px; line-height: 1.25; color: #2c2c2e; padding: 2px; border-radius: 8px; background-color: #f0f0f0; " >
        <table width="100%" cellpadding="0" cellspacing="10" border="0">
            <tr>
                <td valign="top" style=" width: 4em; font-size: 13px; line-height: 1.25; color: #89898c; white-space: nowrap; " >发件人</td>
                <td valign="top" style=" font-size: 13px; line-height: 1.25; color: #2c2c2e; word-break: break-all; " ><a class="mail-from" style="color: #1c83eb; text-decoration: none" ***@***.***" >***@***.***&gt;</a></td>
            </tr>
            <tr>
                <td valign="top" style=" width: 4em; font-size: 13px; line-height: 1.25; color: #89898c; white-space: nowrap; " >日期</td>
                <td class="mail-date" valign="top" style=" font-size: 13px; line-height: 1.25; color: #2c2c2e; word-break: break-all; " >2023年02月11日 00:25</td>
            </tr>
            <tr style="">
                <td valign="top" style=" width: 4em; font-size: 13px; line-height: 1.25; color: #89898c; " >收件人</td>
                <td valign="top" style=" font-size: 13px; line-height: 1.25; color: #2c2c2e; word-break: break-all; " ><a class="mail-to" style="color: #1c83eb; text-decoration: none" ***@***.***" >***@***.***&gt;</a></td>
            </tr>
            <tr style="">
                <td valign="top" style=" width: 4em; font-size: 13px; line-height: 1.25; color: #89898c; " >抄送至</td>
                <td valign="top" style=" font-size: 13px; line-height: 1.25; color: #2c2c2e; word-break: break-all; " ><a class="mail-cc" style="color: #1c83eb; text-decoration: none" ***@***.***" >***@***.***&gt;</a>、<a class="mail-cc" style="color: #1c83eb; text-decoration: none" ***@***.***" >***@***.***&gt;</a></td>
            </tr>
            <tr>
                <td valign="top" style=" width: 4em; font-size: 13px; line-height: 1.25; color: #89898c; " >主题</td>
                <td class="mail-subject" valign="top" style=" font-size: 13px; line-height: 1.25; color: #2c2c2e; word-break: break-all; " >Re: [Icalingua-plus-plus/Icalingua-plus-plus] [Feature Request]打卡功能 能不能考虑一下 (Issue #554)</td>
            </tr>
        </table>
    </div>
    <div><p></p>

<blockquote>

<p dir="auto">我这边没显示啊</p>

</blockquote>

<p dir="auto">所有已有公告下方，如果漫游说明没有发公告权限</p>



<p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">&mdash;<br />Reply to this email directly, <a href="https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/554#issuecomment-1426047090">view it on GitHub</a>, or <a href="https://githuications/unsubsuth/A3GBVC2J6ND4OEGISXP5Y64YA">unsubscribe</a>.<br />You are receiving this because you authored the thread.<img src="https://github.c、M4CL5BULWWZTXXA5CNFSM6AAAAAAUWWO4YCWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSU77AHE.gif" height="1" width="1" alt="" /><span style="color: transparent; font-size: 0; display: none; visibility: hidden; overflow: hidden; opacity: 0; width: 0; height: 0; max-width: 0; max-height: 0; mso-hide: all">Message ID: <span>&lt;Icalingua-plus-plus/Icalingua-plus-plus/issues/554/1426047090</span><span>@</span><span>github</span><span>.</span><span>com&gt;</span></span></p>

<script type="application/ld+json">[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/554#issuecomment-1426047090",

"url": "https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/554#issuecomment-1426047090",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]</script>
</div>
</div>
</body>
</html>

**Comment by dmlgzs** [comment]
> 真没有，我当群主和当管理的群都没有，难不成我找错地方了？

网页应用里打开群公告列表，列表最下方就有发布新公告按钮
![image](https://user-images.githubusercontent.com/24828354/218248372-9a424d10-ca5f-4e3b-b3e6-e8ad3c4a897d.png)

**Comment by Chenyu550** [comment]
打开公告可以看到编辑，主界面就是没有发布

难道真是我的问题了？






------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年2月11日(星期六) 下午4:27
To: ***@***.***&gt;; 
Cc: " ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [Feature Request]打卡功能 能不能考虑一下 (Issue #554)





  
真没有，我当群主和当管理的群都没有，难不成我找错地方了？
  
网页应用里打开群公告列表，列表最下方就有发布新公告按钮

**Comment by ForkKILLET** [comment]
> 打开公告可以看到编辑，主界面就是没有发布 难道真是我的问题了？
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: ***@***.***&gt;; Date: 2023年2月11日(星期六) 下午4:27 To: ***@***.***&gt;; Cc: " ***@***.***&gt;; ***@***.***&gt;; Subject: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [Feature Request]打卡功能 能不能考虑一下 (Issue #554) 真没有，我当群主和当管理的群都没有，难不成我找错地方了？ 网页应用里打开群公告列表，列表最下方就有发布新公告按钮 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

版本？

**Comment by Chenyu550** [comment]
2.8.7




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年2月11日(星期六) 下午4:32
To: ***@***.***&gt;; 
Cc: " ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [Feature Request]打卡功能 能不能考虑一下 (Issue #554)





  
打开公告可以看到编辑，主界面就是没有发布 难道真是我的问题了？
 …
 ------------------&nbsp;Original&nbsp;------------------ From: @.&gt;; Date: 2023年2月11日(星期六) 下午4:27 To: @.&gt;; Cc: " @.&gt;; @.&gt;; Subject: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [Feature Request]打卡功能 能不能考虑一下 (Issue #554) 真没有，我当群主和当管理的群都没有，难不成我找错地方了？ 网页应用里打开群公告列表，列表最下方就有发布新公告按钮 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
版本？

**Comment by dmlgzs** [comment]
> 2.8.7

要 develop 的才行（

**Comment by ForkKILLET** [comment]
> > 2.8.7
> 
> 要 develop 的才行（

我 就 知 道

**Comment by Chenyu550** [comment]
原来如此，我下的是release里的😥



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年2月11日(星期六) 下午4:34
To: ***@***.***&gt;; 
Cc: " ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [Feature Request]打卡功能 能不能考虑一下 (Issue #554)





  
2.8.7
  
要 develop 的才行（
