### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Chenyu550** [Icalingua-plus-plus/Icalingua-plus-plus#556]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
出大事了 刚刚腾讯好像提升了版本限制 现在用这个软件的两个平板协议都不能登录了 只能用MAC协议
**To Reproduce / 复现过程**
用aPad或iPad登录
**Expected behavior / 预期的结果**
登录成功
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Chenyu550** [comment]
补充：好像不是所有账号都这样 但我大号确实这样了 但是小号还能登录 不清楚其中的逻辑
（大号只剩8.9.25和8.9.28两个版本能登录了）
现在整个人都是蒙圈状态的

**Comment by Chenyu550** [comment]
问了好多人好像真是我被针对了 那就先这样吧 不过你们也可以提升一下平板协议所用的版本

**Comment by Icalinguaplusplus** [comment]
> 大号只剩8.9.25和8.9.28两个版本能登录了

手机QQ8.9.23旧版本也不能登录？

**Comment by Chenyu550** [comment]
当时测试时是这样的，而且今天小号也登不上了，让升级



------------------&nbsp;Original&nbsp;------------------
From: "The Icalingua++ ***@***.***&gt;; 
Date: 2023年2月12日(星期天) 下午3:56
To: ***@***.***&gt;; 
Cc: " ***@***.***&gt;; "State ***@***.***&gt;; 
Subject: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG] (Issue #556)





  
大号只剩8.9.25和8.9.28两个版本能登录了
  
手机QQ8.9.23旧版本也不能登录？

**Comment by Chenyu550** [comment]
完全没头绪，我也不知道为什么会这样，因为不是所有人都这样




------------------&nbsp;Original&nbsp;------------------
From: "The Icalingua++ ***@***.***&gt;; 
Date: 2023年2月12日(星期天) 下午3:56
To: ***@***.***&gt;; 
Cc: " ***@***.***&gt;; "State ***@***.***&gt;; 
Subject: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG] (Issue #556)





  
大号只剩8.9.25和8.9.28两个版本能登录了
  
手机QQ8.9.23旧版本也不能登录？
