### ISSUE TITLE
[BUG] 表情面板显示异常，常规情况下无法切换表情类别

### ISSUE THREAD

**Issue by SoDebug** [Icalingua-plus-plus/Icalingua-plus-plus#557]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
表情面板高度太高了，以至于看不到切换表情类别的head
![image](https://user-images.githubusercontent.com/30922923/218101542-8cac7d59-32aa-4094-a513-164fb2b51eba.png)
只有打开开发者选项后才能切换
![image](https://user-images.githubusercontent.com/30922923/218101661-5543d5cf-df3e-4110-a81a-5818ada0a5b5.png)

**To Reproduce / 复现过程**
总是出现
**Expected behavior / 预期的结果**
表情面板高度始终，能够正常切换表情类别
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://user-images.githubusercontent.com/30922923/218101542-8cac7d59-32aa-4094-a513-164fb2b51eba.png)
![image](https://user-images.githubusercontent.com/30922923/218101661-5543d5cf-df3e-4110-a81a-5818ada0a5b5.png)
**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]
Win 11 专业工作站（22623.1255）
**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by dmlgzs** [comment]
应该是自己添加的 style.css 有问题

**Comment by SoDebug** [comment]
> 应该是自己添加的 style.css 有问题

还真是，很久之前添加的样式了。我都快忘记自己弄了
