### ISSUE TITLE
[BUG]突然登不了

### ISSUE THREAD

**Issue by Chenyu550** [Icalingua-plus-plus/Icalingua-plus-plus#558]
今天突然就这样了，两个号都这样，想和手机电脑一起登录只能用watch登录了
![image](https://user-images.githubusercontent.com/114039435/218295680-4a8abb6e-ab3e-423d-a446-c1811f57a4e5.png)
![image](https://user-images.githubusercontent.com/114039435/218295663-d07ea073-50da-4aac-9bd3-cfa72ad93c9a.png)
而且貌似并不是所有人都会这样
用的是release的最新版

**Comment by Icalinguaplusplus** [comment]
点击无法登录更换设备信息也不能登录？

**Comment by Chenyu550** [comment]
没尝试过，但是手机QQ也这样了，升级最新版才登上




------------------&nbsp;Original&nbsp;------------------
From: "The Icalingua++ ***@***.***&gt;; 
Date: 2023年2月12日(星期天) 下午4:04
To: ***@***.***&gt;; 
Cc: " ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG]突然登不了 (Issue #558)





 
点击无法登录更换设备信息也不能登录？

**Comment by Icalinguaplusplus** [comment]
> 没尝试过，但是手机QQ也这样了，升级最新版才登上

待会更新个8.9.30的 apad 试试看？
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/actions/runs/4155614826/

**Comment by Icalinguaplusplus** [comment]
> 没尝试过，但是手机QQ也这样了，升级最新版才登上

CI 跑完了（
看看不更换设备信息的情况下还会不会提示版本低？

**Comment by Chenyu550** [comment]
![image](https://user-images.githubusercontent.com/114039435/218303523-084eae78-f125-42d9-b3b0-f186f63faae2.png)
不行

**Comment by Chenyu550** [comment]
重新生成设备信息也是这样

**Comment by Chenyu550** [comment]
![IMG_20230212_174102.jpg](https://user-images.githubusercontent.com/114039435/218303645-02daf683-fff4-4123-a8e7-b84a6a5fa306.jpg)

手机版升级以前也是这样，升级后就好了

**Comment by Icalinguaplusplus** [comment]
> 重新生成设备信息也是这样

那估计没办法了（
要更新包体比较麻烦

**Comment by Chenyu550** [comment]
行，反正用手表还能登 只不过黄脸表情显示不出来就是了 其他的没影响




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年2月12日(星期天) 晚上10:03
To: ***@***.***&gt;; 
Cc: " ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG]突然登不了 (Issue #558)





  
重新生成设备信息也是这样
  
那估计没办法了（
 要更新包体比较麻烦

**Comment by dmlgzs** [comment]
> 行，反正用手表还能登 只不过黄脸表情显示不出来就是了 其他的没影响

不输入密码，扫码登录，或许可行

**Comment by Joyzhyu** [comment]
我也中招了，所有设备必须更新QQ才能登录了，可是我旧手机不想更新QQ啊😭

**Comment by Chenyu550** [comment]
是，我一个朋友前两天也中招了<br/>如果有核心破解，可以升级到最新版本完成登录，然后强行降级<br/><br/><br/><font style="color:rgb(137,137,140);"><font style="font-size:14px;">---- 回复的原邮件 ----<br/></font></font><span style="background-color:rgb(240,240,240);"><font style="color:rgb(137,137,140);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">发件人</span></font></font> <a ***@***.***"><font style="color:rgb(28,131,235);"><font style="font-size:13px;"><span ***@***.***&gt;</span></font></font></a> <font style="color:rgb(137,137,140);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">日期</span></font></font> <font style="color:rgb(44,44,46);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">2023年02月17日 00:58</span></font></font> <font style="color:rgb(137,137,140);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">收件人</span></font></font> <a ***@***.***"><font style="color:rgb(28,131,235);"><font style="font-size:13px;"><span ***@***.***&gt;</span></font></font></a> <font style="color:rgb(137,137,140);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">抄送至</span></font></font> <font style="font-size:13px;"><span style="background-color:rgb(240,240,240);"><a ***@***.***"><font ***@***.***&gt;</font></a><font style="color:rgb(44,44,46);">、</font><a ***@***.***"><font ***@***.***&gt;</font></a></span></font> <font style="color:rgb(137,137,140);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">主题</span></font></font> <font style="color:rgb(44,44,46);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG]突然登不了 (Issue #558)</span></font></font> <br/></span>我也中招了，所有设备必须更新QQ才能登录了，可是我旧手机不想更新QQ啊😭<br/><font style="color:rgb(102,102,102);">—<br/>Reply to this email directly, <a href="https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/558#issuecomment-1433407228">view it on GitHub</a>, or unsubscribe.<br/>You are receiving this because you authored the thread.<img style="max-width: 960px" src="cid:0432b771bc42c8b9b4208a7ff7846761" />Message ID: ***@***.***&gt;<br/></font><br/><br/><br/><html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>

</body>
</html>

**Comment by Joyzhyu** [comment]
> 是，我一个朋友前两天也中招了<br/>如果有核心破解，可以升级到最新版本完成登录，然后强行降级<br/><br/><br/><font style="color:rgb(137,137,140);"><font style="font-size:14px;">---- 回复的原邮件 ----<br/></font></font><span style="background-color:rgb(240,240,240);"><font style="color:rgb(137,137,140);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">发件人</span></font></font> <a ***@***.***"><font style="color:rgb(28,131,235);"><font style="font-size:13px;"><span ***@***.***&gt;</span></font></font></a> <font style="color:rgb(137,137,140);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">日期</span></font></font> <font style="color:rgb(44,44,46);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">2023年02月17日 00:58</span></font></font> <font style="color:rgb(137,137,140);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">收件人</span></font></font> <a ***@***.***"><font style="color:rgb(28,131,235);"><font style="font-size:13px;"><span ***@***.***&gt;</span></font></font></a> <font style="color:rgb(137,137,140);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">抄送至</span></font></font> <font style="font-size:13px;"><span style="background-color:rgb(240,240,240);"><a ***@***.***"><font ***@***.***&gt;</font></a><font style="color:rgb(44,44,46);">、</font><a ***@***.***"><font ***@***.***&gt;</font></a></span></font> <font style="color:rgb(137,137,140);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">主题</span></font></font> <font style="color:rgb(44,44,46);"><font style="font-size:13px;"><span style="background-color:rgb(240,240,240);">Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG]突然登不了 (Issue #558)</span></font></font> <br/></span>我也中招了，所有设备必须更新QQ才能登录了，可是我旧手机不想更新QQ啊😭<br/><font style="color:rgb(102,102,102);">—<br/>Reply to this email directly, <a href="[#558 (comment)](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/558#issuecomment-1433407228)">view it on GitHub</a>, or unsubscribe.<br/>You are receiving this because you authored the thread.<img style="max-width: 960px" src="cid:0432b771bc42c8b9b4208a7ff7846761" />Message ID: ***@***.***&gt;<br/></font><br/><br/><br/><html> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> </head> <body> </body> </html>

这方法治标不治本，只能单一设备操作（单单降级一设备其它设备依旧提示版本过低），而且旧手机硬件及系统限制也无法安装最新版QQ。好后悔装了Icalingua++，单纯为了体验一下把主号给搞死在版本这了。

▼估计是无法使用老协议了
>[Icalinguaplusplus：切换协议或生成新的设备信息或许能解决，如果不行可能是账号已经无法使用老协议或被风控](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/505#issuecomment-1383100403)

**Comment by dmlgzs** [comment]
> 好后悔装了Icalingua++，单纯为了体验一下把主号给搞死在版本这了。

所有设备都版本低和 Icalingua++ 没有任何关系。
腾讯前段时间开始灰度测试新协议，抽到的号老协议老客户端都会无法登录，同时范围还在扩大，估计很快就会全员了，到时候没有升级协议的框架都得死。
同样的 PCQQ 也一样，大部分账号不是最新版本都已经不能登录，提示版本低了。

**Comment by dmlgzs** [comment]
腾讯现在在筹备 QQ9 相关事项，很多东西会有很大变动无法避免。

**Comment by Chenyu550** [comment]
> > 好后悔装了Icalingua++，单纯为了体验一下把主号给搞死在版本这了。
> 
> 所有设备都版本低和 Icalingua++ 没有任何关系。 腾讯前段时间开始灰度测试新协议，抽到的号老协议老客户端都会无法登录，同时范围还在扩大，估计很快就会全员了，到时候没有升级协议的框架都得死。 同样的 PCQQ 也一样，大部分账号不是最新版本都已经不能登录，提示版本低了。

所以Icalingua++的更新已经迫在眉睫了

**Comment by Joyzhyu** [comment]
> > 好后悔装了Icalingua++，单纯为了体验一下把主号给搞死在版本这了。
> 
> 所有设备都版本低和 Icalingua++ 没有任何关系。 腾讯前段时间开始灰度测试新协议，抽到的号老协议老客户端都会无法登录，同时范围还在扩大，估计很快就会全员了，到时候没有升级协议的框架都得死。 同样的 PCQQ 也一样，大部分账号不是最新版本都已经不能登录，提示版本低了。

问题就这个号前几天用过 Icalingua++ ，不会这么巧给抽到吧😥
ios10 | 11系统无法更新最新版了，聊天记录还得想办法导出来。

**Comment by Mr54233** [comment]
我也是,手机pc都提示版本过低,腾讯要搞大事啊

**Comment by Chenyu550** [comment]
唉，为了一个破QQ9搞这么多事，真是....




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Icalingua-plus-plus/Icalingua-plus-plus"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, Feb 17, 2023 10:00 AM
***@***.***&gt;;
Cc:&nbsp;" ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG]突然登不了 (Issue #558)





 
我也是,手机pc都提示版本过低,腾讯要搞大事啊

**Comment by bcegkmqs23** [comment]
我也寄了

**Comment by Chenyu550** [comment]
不要坐以待毙，作者和contributor快来干活！




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年2月17日(星期五) 晚上8:42
To: ***@***.***&gt;; 
Cc: " ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG]突然登不了 (Issue #558)





 
我也寄了

**Comment by SteveWorkshop** [comment]
这样下去不是个办法啊，虽然QQ官方要换electron，但是么懂得都懂，反正我是不愿意用的
是时候把icallingua3提上日程了。不然一旦那边完成协议更新这项目就失去价值了

**Comment by SteveWorkshop** [comment]
我之前报名了QQ9的预约，会不会和这个有关系

**Comment by shenjackyuanjie** [comment]
hmmmmm
所以目前问题是qq新协议？

**Comment by SteveWorkshop** [comment]
怀疑是

**Comment by SteveWorkshop** [comment]
新协议还没有人坡姐出来吧

**Comment by shenjackyuanjie** [comment]
似乎是的（？

**Comment by SteveWorkshop** [comment]
又得回到用虚拟机装QQ的日子了

**Comment by SteveWorkshop** [comment]
刚刚：又挂了
再改一下子版本号试试？

**Comment by SteveWorkshop** [comment]
> > 没尝试过，但是手机QQ也这样了，升级最新版才登上
> 
> 待会更新个8.9.30的 apad 试试看？ https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/actions/runs/4155614826/

已经不管用了

**Comment by Icalinguaplusplus** [comment]
> 已经不管用了

试试2.8.10+更换设备信息？

**Comment by SteveWorkshop** [comment]
试了此方法，暂时解决了问题

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: The Icalingua++ ***@***.***>
发送时间: 2023年2月21日 11:41
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG]突然登不了 (Issue #558)


已经不管用了

试试2.8.10+更换设备信息？

―

**Comment by Chenyu550** [comment]
![image](https://user-images.githubusercontent.com/114039435/220252175-92d96d46-d62e-4021-a838-58f808f044d3.png)
更新后变成这样了，还是不行。。。

**Comment by SteveWorkshop** [comment]
疑似使用亻弋王里软件会增加失败风控概率

**Comment by Chenyu550** [comment]
现在连扫码都不行了，又只能手表协议登录了

**Comment by SteveWorkshop** [comment]
有没有一种可能？OICQ协议库被TX发现是机器人了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月21日 15:51
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG]突然登不了 (Issue #558)


现在连扫码都不行了，又只能手表协议登录了

―

**Comment by joyseapony** [comment]
一样遇到了，刚开始显示版本过低现在要更换网络不稳定。小号也不行，估计寄了。。

**Comment by shenjackyuanjie** [comment]
![image](https://user-images.githubusercontent.com/54507071/220357279-05458da4-e656-4c6e-9b1f-cb3f27863669.png)
坏了，我也灰度了

**Comment by shenjackyuanjie** [comment]
![image](https://user-images.githubusercontent.com/54507071/220358191-c5a467f8-bfcc-4194-b5da-1d458ceba289.png)
错误码 235

**Comment by shenjackyuanjie** [comment]
![image](https://user-images.githubusercontent.com/54507071/220358575-006cb982-44ce-4be4-81aa-8b97db0b0461.png)
以及好消息，重新生成之后就可以了

**Comment by SteveWorkshop** [comment]
我怀疑这更有可能是TX针对这个机器人的对策
最近最好小心点，万一他们发现这个仓库那可就事大了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月21日 21:33
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG]突然登不了 (Issue #558)


[image]<https://user-images.githubusercontent.com/54507071/220358575-006cb982-44ce-4be4-81aa-8b97db0b0461.png>
以及好消息，重新生成之后就可以了

―

**Comment by shenjackyuanjie** [comment]
确实，有可能

**Comment by SteveWorkshop** [comment]
实在不行可以学lyricease，先把仓库暂时私有，更新通过其他CDN分发，这阵过去了再看看情况而定

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月21日 21:36
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG]突然登不了 (Issue #558)


确实，有可能

―

**Comment by Chenyu550** [comment]
已经彻底废了，任何协议均无法登录

**Comment by dmlgzs** [comment]
> 已经彻底废了，任何协议均无法登录

我这边没有问题，你的号应该是灰度要544，基本上没救

**Comment by Chenyu550** [comment]
> > 已经彻底废了，任何协议均无法登录
> 
> 我这边没有问题，你的号应该是灰度要544，基本上没救

那这咋办，总有一天这些协议会全面过期，难道就不升级了？

**Comment by dmlgzs** [comment]
> 那这咋办，总有一天这些协议会全面过期，难道就不升级了？

怎么说的好像升级很容易一样（
就连 mirai 都还一直在用老协议包体
看看2.8.13吧，那个改了一部分了（不过我估计这种号还是不能登录的
一般来说为了日活是不会全部强制推进的，所以一般不会到全面过期

还有最好试试自己新设备能不能登陆，也有可能是账号被风控了

**Comment by SteveWorkshop** [comment]
那这个项目离archive不远了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月24日 19:39
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG]突然登不了 (Issue #558)


已经彻底废了，任何协议均无法登录

我这边没有问题，你的号应该是灰度要544，基本上没救

那这咋办，总有一天这些协议会全面过期，难道就不升级了？

―

**Comment by Icalinguaplusplus** [comment]
出现禁止登录的可以尝试使用这个版本 https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/actions/runs/4264199292

**Comment by shenjackyuanjie** [comment]
> ![image](https://user-images.githubusercontent.com/54507071/220358575-006cb982-44ce-4be4-81aa-8b97db0b0461.png) 以及好消息，重新生成之后就可以了

以及更好消息，目前我的号用ipad可以登录

**Comment by Chenyu550** [comment]
最新版又嘎了，禁止登录
