### ISSUE TITLE
[BUG] 字还没打完，消息就自动发出去了

### ISSUE THREAD

**Issue by NicholasLD** [Icalingua-plus-plus/Icalingua-plus-plus#56]
**Describe the bug / 描述**

在聊天时，很大几率字还没打完，消息就自动发出了，但是消息框里消息还在，包括在@人时，有时候刚@完就自动发出去了，也没有按到Enter快捷键。导致我失恋了！

**Screenshots / 截图**
![img](https://s2.loli.net/2022/04/07/3WxYushVpkIyzFo.png)

**System information / 系统信息**
 - OS: macOS Monterey
 - Version 12.3.1

**Additional context / 附加信息**
软件版本2.6.1

**Comment by ManiaciaChao** [comment]
Workaround for macOS before PR #60 is merged:

> Just stroke key `space` instead of key `enter` to select candidate words.
