### ISSUE TITLE
[BUG]草稿切换聊天时仍然在输入框内

### ISSUE THREAD

**Issue by Eletary** [Icalingua-plus-plus/Icalingua-plus-plus#560]
**Describe the bug / 描述**
草稿不保存，且留在聊天框内

**To Reproduce / 复现过程**
输入任意文字，切换聊天对象

**Expected behavior / 预期的结果**
每个聊天框保留草稿

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: Ubuntu
 - Version 20.04

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by ForkKILLET** [comment]
是预期效果吧，个人觉得比较方便，但确实可以做一个分别保存草稿的选项就是了

**Comment by SteveWorkshop** [comment]
可别预期效果啊，曾经UWPqq有这个“特性”，我就深受其害过（一不小心发错人了）

**Comment by SteveWorkshop** [comment]
> 可别预期效果啊，曾经UWPqq有这个“特性”，我就深受其害过（一不小心发错人了）

那场面简直无法形容

**Comment by clansty** [comment]
这真的是 feature。最早的时候会删除草稿。现在你甚至可以跨聊天回复（引用）消息
