### ISSUE TITLE
适配竖屏显示

### ISSUE THREAD

**Issue by SteveWorkshop** [Icalingua-plus-plus/Icalingua-plus-plus#561]
在屏幕宽度较小时折叠左侧会话列表，点击会话打开新页面，类似于手q，屏幕宽度较大时保持现在布局。或者做一个汉堡菜单也行
最好能根据屏幕旋转（宽度调整）自适应

**Comment by Amarillys** [comment]
你有尝试降左边联系人栏拉到最小宽度吗，icalingua我觉得在头像栏很窄的一栏下面也还可以的
