### ISSUE TITLE
自定义Sticker路径

### ISSUE THREAD

**Issue by vstar37** [Icalingua-plus-plus/Icalingua-plus-plus#562]
希望可以自定Sticker路径，方遍使用OneDrive多设备间同步。

**Comment by Amarillys** [comment]
或许你可以试试软链接 mklink？

**Comment by unknown10777** [comment]
![image](https://user-images.githubusercontent.com/83267603/219845958-88228d28-952a-405e-a766-54382e53b190.png)
--user-data-dir=你盘:/你Onedrive文件地址

**Comment by Icalinguaplusplus** [comment]
建议使用目录符号链接
