### ISSUE TITLE
[Feature Request] 添加新LinuxQQ的登陆协议

### ISSUE THREAD

**Issue by PTALTS-LK** [Icalingua-plus-plus/Icalingua-plus-plus#567]
**Is your feature request related to a problem? Please describe.**
新的Linux版QQ推出了，但是在使用上仍然不令人满意

**Describe the solution you'd like**
能不能添加一个新LinuxQQ的登陆协议

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

**Comment by dmlgzs** [comment]
QQNT 协议差异大，tg 群内之前说不会做
