### ISSUE TITLE
转发的消息中有文件时不会显示

### ISSUE THREAD

**Issue by Wenti-D** [Icalingua-plus-plus/Icalingua-plus-plus#570]
**Describe the bug / 描述**

QQ 的合并消息转发可以包含其他来源的文件，但这些文件在 Icalingua++ 中查看合并转发消息时就消失了。

**To Reproduce / 复现过程**

叫朋友给你合并转发一些文件。

**Expected behavior / 预期的结果**

合并转发消息中应包含转发的文件。

**Screenshots / 截图**

![image](https://user-images.githubusercontent.com/73067578/220020726-3b3a6540-e880-4dcf-9ae8-bef0af12a995.png)
![image](https://user-images.githubusercontent.com/73067578/220021017-0ec893ce-9e09-4ee1-b4ef-1e4cd277219f.png)

**System information / 系统信息**

 - OS: Windows 11 Pro
 - Version: 2.9.3

**Additional context / 附加信息**

不知道这算「BUG」还是「未实现的功能」，总之这里先当做 bug。

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus/commit/124c4973008b9fdf36911a6fdea121f123f390f1
