### ISSUE TITLE
希望能把用户的数据目录放在同一级目录或子文件夹中

### ISSUE THREAD

**Issue by Baka943-0v0** [Icalingua-plus-plus/Icalingua-plus-plus#571]
希望能把用户的数据目录放在同一级目录或子文件夹中，这样就可以打包到U盘中，不会把用户数据泄漏到本地电脑中，望采纳

**Comment by dmlgzs** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus#:~:text=%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E7%9B%AE%E5%BD%95%3A%20%2D%2Duser%2Ddata%2Ddir%3D%24path%2Dyou%2Dwant
