### ISSUE TITLE
[Feature Request] 能不能加一个跳转到@的功能？

### ISSUE THREAD

**Issue by EnderAvaritia** [Icalingua-plus-plus/Icalingua-plus-plus#575]
能不能加一个@提示以及跳转到@的功能，群里@我我找不到在哪。

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/23457b61608128091fdaf8b3930a2e3fd9478684
