### ISSUE TITLE
[BUG]转发消息无法查看

### ISSUE THREAD

**Issue by ccyykkcyk** [Icalingua-plus-plus/Icalingua-plus-plus#576]
**Describe the bug / 描述**
合并转发消息无法查看，显示为[JSON][聊天记录]，2.8.10出现这个问题，2.8.7可以查看

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/91893497/220635022-ce451293-32a9-485d-b78e-82e719302561.png)

**System information / 系统信息**
 - OS: [Windows 10]
 - Version [19045.2604]

**Additional context / 附加信息**
协议都是ipad

**Comment by dmlgzs** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/5640cbe8d2782c02d47883b54aa74f94c226c420
看这已经支持了
