### ISSUE TITLE
[BUG]使用oicq bridge的时候无法发出图片

### ISSUE THREAD

**Issue by Neubulae** [Icalingua-plus-plus/Icalingua-plus-plus#58]
**描述**
如题。

**复现过程**
1. 使用icalingua++的oicq bridge
2. 试图发送图片
3. ...转圈圈

**预期的结果**
图片发送

**截图**
![图片](https://user-images.githubusercontent.com/24774842/162370012-e4ec6c99-e6ef-4930-b8ae-c42bfe78e4dc.png)

**系统信息**
 - i use Arch btw :)
 - action的latest build

**Comment by Icalinguaplusplus** [comment]
是否檢查過網絡問題？發送過程中是否有網絡活動？

**Comment by Neubulae** [comment]
> 是否檢查過網絡問題？發送過程中是否有網絡活動？

有的，其他消息都可以发送，从聊天中直接复制粘贴的消息也可以发送，只有直接从本地上传的不行

**Comment by Icalinguaplusplus** [comment]
> > 是否檢查過網絡問題？發送過程中是否有網絡活動？
> 
> 有的，其他消息都可以发送，从聊天中直接复制粘贴的消息也可以发送，只有直接从本地上传的不行

請檢查發送的圖片是否過大，使用 bridge 時圖片會先傳送到 bridge 後再發送

**Comment by Neubulae** [comment]
> > > 是否檢查過網絡問題？發送過程中是否有網絡活動？
> > 
> > 
> > 有的，其他消息都可以发送，从聊天中直接复制粘贴的消息也可以发送，只有直接从本地上传的不行
> 
> 請檢查發送的圖片是否過大，使用 bridge 時圖片會先傳送到 bridge 後再發送

过大的话究竟什么样是过大呢，几kb是过大吗…

Bridge是否会出现详细的可以capture的log信息呢，我这里没看到…

**Comment by Neubulae** [comment]
现在主要是我完全不知道发生了什么……大概几个版本前可以发出去但是会原地显示转圈，现在是完全发不出去，log没有任何信息……

**Comment by Icalinguaplusplus** [comment]
> 现在主要是我完全不知道发生了什么……大概几个版本前可以发出去但是会原地显示转圈，现在是完全发不出去，log没有任何信息……

抓包有數據傳輸嗎

**Comment by Neubulae** [comment]
怎么抓包（
要把抓包数据发给你吗，而且我网络环境比较复杂…

**Comment by Icalinguaplusplus** [comment]
已修復

**Comment by Neubulae** [comment]
草，原来这就是问题……谢谢
