### ISSUE TITLE
[Feature Request]提供同步device.json的一个方法

### ISSUE THREAD

**Issue by Pittow** [Icalingua-plus-plus/Icalingua-plus-plus#581]
在具有系统盘写保护的设备上登陆时，每次都会随机产生不同的设备id，提高了被风控的危险性。

如果能在需要随机产生设备id时，可选输入一个幸运数字，与qq号做运算后得到随机种子。
根据该种子产生随机设备id，每次在不同的电脑上登陆时就能使用相同的device.json，降低被风控的可能。

**Comment by Pittow** [comment]
”具有系统盘写保护的设备“，就是学校的电脑/kk

**Comment by shenjackyuanjie** [comment]
（这种需求，建议使用ica-docker
（如果数据库不好迁移的话，可以使用[这位](https://hub.docker.com/r/huangz1342/icalingua-bridge-oicq)的非官方docker（逃

**Comment by Pittow** [comment]
> （这种需求，建议使用ica-docker （如果数据库不好迁移的话，可以使用[这位](https://hub.docker.com/r/huangz1342/icalingua-bridge-oicq)的非官方docker（逃

事实上，我并没有自己的服务器。
如果我能有这样一台服务器，很多问题都将迎刃而解。

传输一个随机生成的文件只需要传递生成它的时候使用的随机种子，这能很大程度上节约成本。
相比于部署一整台服务器，仅仅凭脑力记住一个数字显然更划算。

**Comment by shenjackyuanjie** [comment]
嗯，知道的，只是说一句
（不过你也可以考虑通过内网穿透等方式去直接在你的电脑上使用docker

**Comment by Pittow** [comment]
哈哈，我家的电脑就更惨了，甚至都不归我管。

**Comment by Pittow** [comment]
@Icalinguaplusplus 快来看看吧

**Comment by Icalinguaplusplus** [comment]
请自行保存到网盘
