### ISSUE TITLE
[BUG] 下载个人文件时出错

### ISSUE THREAD

**Issue by abumpkin** [Icalingua-plus-plus/Icalingua-plus-plus#587]
**Describe the bug / 描述**
下载个人文件时出错.

**复现**

在移动端向好友发送一个文件, 然后在 Icalingua++ 里下载自己发送给好友的文件就会出错

**Expected behavior / 预期的结果**
正常下载

**Screenshots / 截图**
![图片](https://user-images.githubusercontent.com/62453379/221413607-0a1b0c19-aa68-4535-8ca3-63df159e28ff.png)

**System information / 系统信息**
 - OS: Windows 10
 - Version 22H2

**Comment by Icalinguaplusplus** [comment]
自己发的 需要右键重新获取该条消息
