### ISSUE TITLE
[BUG] version 2.8.15 无法登录

### ISSUE THREAD

**Issue by blue1874** [Icalingua-plus-plus/Icalingua-plus-plus#588]
重启设备后无法登录，提示可能是风控原因，升级到最新版后登录提示被禁止登录

![image](https://user-images.githubusercontent.com/29906056/221476260-243aad18-bc0d-48f7-8125-52d202a85fa5.png)

系统信息
![image](https://user-images.githubusercontent.com/29906056/221476343-44b68e74-18a0-4053-857e-2973a2bb46b0.png)

**Comment by Icalinguaplusplus** [comment]
试试这个版本？
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/actions/runs/4264199292

**Comment by blue1874** [comment]
@Icalinguaplusplus 还是不行，一样的提示

**Comment by Icalinguaplusplus** [comment]
> @Icalinguaplusplus 还是不行，一样的提示

切 macOS 登录一次再切回来呢

**Comment by blue1874** [comment]
可以了，感谢帮助
