### ISSUE TITLE
[BUG] 当第一次使用时获取过多的聊天记录时会出现部分聊天不显示，除非手动搜索群或者人。某些情况即使这样也无法获取聊天记录。

### ISSUE THREAD

**Issue by unknown10777** [Icalingua-plus-plus/Icalingua-plus-plus#589]
当第一次使用时获取过多的聊天记录时会出现部分聊天不显示，除非手动搜索群或者人。某些情况即使这样也无法获取聊天记录。
**To Reproduce / 复现过程**
1 环境）开个超级会员，用个几年qq，开启消息漫游（两年）
2）第一次安装icalingua++
3）打开icalingua++并开启“启动时自动获取历史信息
4）重启icalingua++
5）看到获取了10个左右 3w+的群/个人聊天记录 
6）看到软件停止获取，重启后仍旧不会自动获取，并且列表只展示了部分群/个人头像

**Expected behavior / 预期的结果**
能获取2年内所有聊天记录并展示到列表
**Screenshots / 截图**

**System information / 系统信息**
 Windows 10

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by shenjackyuanjie** [comment]
有可能是信息漫游的历史接口跟普通的   不一样···？

**Comment by unknown10777** [comment]
> 有可能是信息漫游的历史接口跟普通的一样···？

假设是一样的话也不应该出现获取到了记录但不显示到面板上的问题，以及无法获取更多记录的问题

**Comment by dmlgzs** [comment]
自动获取只会获取已有会话的，不在会话列表的记录不会被获取

**Comment by unknown10777** [comment]
> 自动获取只会获取已有会话的，不在会话列表的记录不会被获取

我的意思是，“打开icalinguapp，只会显示部分会话，除非按人搜索或者按群搜索才能找到部分历史聊天记录”，正常操作逻辑主页会显示所有会话。

**Comment by dmlgzs** [comment]
> 我的意思是，“打开icalinguapp，只会显示部分会话，除非按人搜索或者按群搜索才能找到部分历史聊天记录”，正常操作逻辑主页会显示所有会话。

显示的就是已有会话，登录后收到消息的群或私聊会自动加入已有会话

**Comment by unknown10777** [comment]
> > 我的意思是，“打开icalinguapp，只会显示部分会话，除非按人搜索或者按群搜索才能找到部分历史聊天记录”，正常操作逻辑主页会显示所有会话。
> 
> 
> 
> 显示的就是已有会话，登录后收到消息的群或私聊会自动加入已有会话

抱歉，我以为这是bug。另外还想请教一下无法获取历史记录是哪里的问题。

**Comment by dmlgzs** [comment]
> 抱歉，我以为这是bug。另外还想请教一下无法获取历史记录是哪里的问题。

如果一个会话没有全部获取完成就结束（已获取超过20条）的情况下，重新开始获取就无法继续再往前获取，需要找到之前获取到的最早的消息右键选择“获取历史信息”

**Comment by unknown10777** [comment]
> > 抱歉，我以为这是bug。另外还想请教一下无法获取历史记录是哪里的问题。
> 
> 
> 
> 如果一个会话没有全部获取完成就结束（已获取超过20条）的情况下，重新开始获取就无法继续再往前获取，需要找到之前获取到的最早的消息右键选择“获取历史信息”

好的，非常感谢
