### ISSUE TITLE
[BUG] 断线重连后 Reconnect 提示不会消失

### ISSUE THREAD

**Issue by Yurinann** [Icalingua-plus-plus/Icalingua-plus-plus#593]
**Describe the bug / 描述**
断线重连后，因账号断线所产生的 Reconnect now 提示不会自动消失。
且在页面左上操作栏中 *重新加载* 页面后，此提示消失但历史消息不会自动获取，只有手动刷新时才会获取被刷新的会话（例如切换会话时）。

**To Reproduce / 复现过程**
1. 打开 Iculingua++，登录账号。
2. 断开网络致使账号断开连接，此后重连网络。
3. 使用 Reconnect now 重新登录。

**Expected behavior / 预期的结果**
提示消失且消息自动重载。

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/75569395/222038964-44fe821f-51e8-45b4-b1c8-c02731895ada.png)
（但其实此时已经重新登录+过验证码了，并且 button 后面也显示了相关的新消息提示）

**System information / 系统信息**
 - OS: Windows 10 22H2 家庭中文版
 - Version 2.8.15

**Additional context / 附加信息**
N/A

**Comment by unknown10777** [comment]
出现问题可能是网络不稳定

**Comment by Yurinann** [comment]
同意网络不稳定作为问题产生的客观因素，但重连 button 仍然存在并不像是网络不稳定所导致的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月6日(周一) 凌晨0:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Icalingua-plus-plus/Icalingua-plus-plus] [BUG] 断线重连后 Reconnect 提示不会消失 (Issue #593)




 
出现问题可能是网络不稳定

**Comment by Yurinann** [comment]
版本 2.9.1，现在的情况是有时候 Reconnect now 按钮和点击 Reconnect now 按钮唤起的验证码会同时出现，这样在完成验证后重新登录按钮不会消失。

**Comment by unknown10777** [comment]
![image](https://user-images.githubusercontent.com/83267603/227244786-28d982c2-ef90-4df9-a183-bd5a01c610ba.png)

![image](https://user-images.githubusercontent.com/83267603/227244591-9771f702-3e6c-4e28-aef8-c6b0bcd09b7c.png)
问题复现，使用bridge+zerotier链接服务器。
刷新无法解决问题，退出后重启解决。
