### ISSUE TITLE
[Feature Request] 添加 Homebrew 包

### ISSUE THREAD

**Issue by scientificworld** [Icalingua-plus-plus/Icalingua-plus-plus#595]
**Is your feature request related to a problem? Please describe.**
添加 Homebrew 软件包，包管理更方便一些。

**Describe the solution you'd like**
不知道能不能直接加进官方源，如果不行可以先在组织下创建第三方仓库。

**Additional context**
自己写的，可以作为参考：<https://github.com/scientificworld/homebrew-114514/blob/main/Casks/icalingua-plus-plus.rb>

**Comment by lanthth** [comment]
好臭的包，建议改为homobrew(
