### ISSUE TITLE
[BUG]2.9.1 又提示当前QQ版本过低

### ISSUE THREAD

**Issue by newyorkthink** [Icalingua-plus-plus/Icalingua-plus-plus#596]
![image](https://user-images.githubusercontent.com/87791643/222469303-b4c75979-406c-4eb5-b659-5fcde82ccf45.png)
![image](https://user-images.githubusercontent.com/87791643/222469539-a01c6302-3ddf-4e98-8bd7-300f9326659e.png)

**Comment by newyorkthink** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/573

**Comment by dmlgzs** [comment]
更新之前温馨提示的建议换个设备信息

**Comment by dmlgzs** [comment]
温馨提示是设备被风控不能用这个版本的协议了
