### ISSUE TITLE
[BUG] 自适应单面板模式不显示会话列表而是"No room selected"

### ISSUE THREAD

**Issue by FBIKdot** [Icalingua-plus-plus/Icalingua-plus-plus#597]
**Describe the bug / 描述**
自适应单面板模式不显示会话列表而是"No room selected"

**To Reproduce / 复现过程**
若开启自适应单面板模式, 并且符合单面板的条件下, 在会话过程中关闭Icalingua++的窗口后通过任务栏小图标唤出窗口后将不显示会话列表, 而是"No room selected".

**Expected behavior / 预期的结果**
通过任务栏小图标唤出窗口后, 显示会话列表.

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/83176414/222758563-567bd6a6-5290-4921-9588-b117848fd760.png)

**System information / 系统信息**
 - OS: Windows 10 21H2
 - Version: 2.9.1

**Additional context / 附加信息**
以下为操作复现视频:

https://user-images.githubusercontent.com/83176414/222758788-d4fdebfd-e5ca-46bc-b116-b4c03bc610a1.mp4

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/ff1f510545e88417b6ccd0955dd10cdd28c72b47
