### ISSUE TITLE
[BUG] 好友文件概率不显示

### ISSUE THREAD

**Issue by Yurinann** [Icalingua-plus-plus/Icalingua-plus-plus#598]
**Describe the bug / 描述**
接收来自好友发送的文件时，Iculingua++ 有一定概率不会显示该文件。手机端或官方端正常。

**To Reproduce / 复现过程**
1. 随机选取一位幸运好友，让他向你发送一个任意文件；
2. 此问题概率出现。

**Expected behavior / 预期的结果**
所有文件正常收发。

**Screenshots / 截图**
好友视角（发送方）：
![467ec1f74e1f7012](https://user-images.githubusercontent.com/75569395/222795329-fff74c63-862b-43b7-b568-6e3adb1828c6.jpg)

我的视角（接收方）：
![-730834d214e6d3b2](https://user-images.githubusercontent.com/75569395/222795393-59e92041-712a-41bb-8aa4-cedaa8986a34.jpg)

**System information / 系统信息**
 - OS: Windows 10 22H2 家庭版
 - Version 2.8.15

**Additional context / 附加信息**
此问题出现已久，理论上与文件大小无关，可能与文件是否过期有关。部分情况下（可能在 Iculingua++ 侧未查看此文件时）在手机端下载文件后重新转发能够显示。

**Comment by dmlgzs** [comment]
概率出现的问题，建议提供发送端的 QQ 版本信息

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus/commit/124c4973008b9fdf36911a6fdea121f123f390f1
