### ISSUE TITLE
[BUG]程序无法启动

### ISSUE THREAD

**Issue by MadobiNanami** [Icalingua-plus-plus/Icalingua-plus-plus#601]
**Describe the bug / 描述**
程序无法启动
**To Reproduce / 复现过程**
在Windows 11 1000.25309.1000.0 版本(截至2023-3-5最新的Win11Dev版本)中启动程序, 没有出现窗口,但在任务管理器内出现了3个后台进程
**Expected behavior / 预期的结果**
程序正常启动
**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/63381326/222948315-a7356c59-4dab-4967-90f6-bcda7489ec2b.png)
**System information / 系统信息**
 - OS: Windows 11 Dev
 - Version Windows Feature Experience Pack 1000.25309.1000.0

**Comment by dmlgzs** [comment]
你的配置文件是不是有问题？可以看看 config.yaml 的内容吗（记得打码密码）
