### ISSUE TITLE
[BUG] bridge-oicq docker 版本无法连接至服务器

### ISSUE THREAD

**Issue by ParticleG** [Icalingua-plus-plus/Icalingua-plus-plus#605]
**Describe the bug / 描述**
部署docker环境，客户端向服务器发送用户名密码信息后，docker无法连接至qq登录服务器，而非docker版本能正常连接

**To Reproduce / 复现过程**
按照icalingua-bridge-oicq文件夹内教程操作

**Expected behavior / 预期的结果**
和非docker版本一样正常连接

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/38580644/223612171-29629af0-d500-4fdb-8a9a-2ead78fe5914.png)

**System information / 系统信息**
 - OS: Ubuntu Server 22.04.1 LTS
 - Version 2.9.2

**Additional context / 附加信息**
```bash
$ sudo systemctl show --property=Environment docker
Environment=
$ echo $HTTP_PROXY $HTTPS_PROXY
http://192.168.0.22:7890 http://192.168.0.22:7890
```
这里命令行的HTTP_PROXY和HTTPS_PROXY的env变量应该不会影响docker吧，不知道为什么会连不上

**Comment by dmlgzs** [comment]
网络配置有误吧

**Comment by ParticleG** [comment]
不是直接docker compose up就行了么）

**Comment by zipated** [comment]
我docker用HTTP_PROXY和HTTPS_PROXY就没正常过（

**Comment by ttimochan** [comment]
> 不是直接docker compose up就行了么）

如果你是 Tencent 的服务器，请不要使用 Tencent 给的 DNS server，emmm，具体这个环境变量影响不影响，我不太清楚（我自己不喜欢这么设置代理）
