### ISSUE TITLE
[BUG]无法使用Android Watch协议登录了

### ISSUE THREAD

**Issue by NekoMua** [Icalingua-plus-plus/Icalingua-plus-plus#606]
**Describe the bug / 描述**
最近似乎不能使用Android Watch协议登录了，似乎是腾讯把接口砍了？

**To Reproduce / 复现过程**
正常登录，但是使用安卓手表协议登录就无法登录。
**Expected behavior / 预期的结果**
之前都是可以正常登录的
**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/59407295/223675516-dcdf9be5-0e89-4a48-aad8-a82aaf3383f5.png)

**System information / 系统信息**
 - OS: Windows 7 Professional x64
 - Version: Service Pack 1

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by dmlgzs** [comment]
手表协议的密码登录已经被噶了
建议使用 aPad

**Comment by AstroNomen** [comment]
最近腾讯疯狂风控低版本QQ，商店版QQ都登录不了了
