### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RichardZhang4** [Icalingua-plus-plus/Icalingua-plus-plus#607]
**Describe the bug / 描述**
无法登录

**To Reproduce / 复现过程**
断网后重连之后就无法登录，再也登不上了
**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://user-images.githubusercontent.com/57562388/223990156-fff13143-ab21-453a-9f47-0aa750f37acb.png)

**System information / 系统信息**
WIN10
2.92

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
检查账号是否错误
