### ISSUE TITLE
发送视频文件必须发送两次才行[BUG]

### ISSUE THREAD

**Issue by xiaozhangup** [Icalingua-plus-plus/Icalingua-plus-plus#61]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
发送一个视频文件时，第一次会提示正在上传，并且右下角一直转圈圈，这个过程是无限循环的。只有当我重复发送一遍，视频文件才能正常发出去

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]
![image](https://user-images.githubusercontent.com/68374769/162578203-78c59ac5-2793-4ccd-a309-0a10b3200549.png)

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
現在是否還有這個問題？

**Comment by xiaozhangup** [comment]
没了
