### ISSUE TITLE
[BUG] 无法查看由 LinuxQQ 端发送的图片

### ISSUE THREAD

**Issue by kands-code** [Icalingua-plus-plus/Icalingua-plus-plus#613]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

我之前是 LinuxQQ（3.0.0 之后版本）和 Icalingua 是换着用的，
突然发现 Icalingua 端无法查看 LinuxQQ 端自己（？）发送的图片

**To Reproduce / 复现过程**

LinuxQQ 端发送一张图片，然后切换到 Icalingua 查看，发现无法查看，
但是安卓端（其他端没有验证）是可以正常查看的

**Expected behavior / 预期的结果**

Icalingua 端可以正常看到图片

**Screenshots / 截图**

If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

<details>
  <summary>这是在 LinuxQQ 端发送的图片</summary>

![image](https://user-images.githubusercontent.com/59006329/224466892-a0bf17f0-5e14-444f-9055-3817291c207c.png)

![image](https://user-images.githubusercontent.com/59006329/224467000-8cb35984-afba-47d9-9d65-4f4bf28a5856.png)
</details>

<details>
  <summary>但是安卓端是可以正常看到的</summary>

![image](https://user-images.githubusercontent.com/59006329/224466922-1eb5be37-c2b9-4ae3-a514-98969049ebb6.png)

![image](https://user-images.githubusercontent.com/59006329/224467033-d62f3ec6-dfca-4518-9c24-c27007ba6724.png)
</details>

<details>
  <summary>但是有些图片是可以正常显示的</summary>

![image](https://user-images.githubusercontent.com/59006329/224466990-400ca4f1-64ce-4d9d-98bf-cb9cabff3429.png)
</details>

**System information / 系统信息**
 - OS: [e.g. Arch Linux] Arch Linux
 - Version [e.g. 2.1.4] 2.9.2

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

> 我已经重新启动和重新获取历史数据很多次了，都无法查看到图片

感觉不太能够每次都复现成功，但是概率还是挺大的，
而且不仅仅是这次，之前就一直有图片加载问题，
我估计可能和 cqhttp 协议对于图片的处理有关，不过我不懂这些，也只是猜测

**Comment by CyanChanges** [comment]
确实

**Comment by dmlgzs** [comment]
如果 QQNT 发送图片时 Icalingua++ 未启动，则无法加载对应的图片，原因是 QQNT 不会将图片上传 CDN，需要使用特殊包获取有效期极短的文件链接

**Comment by dmlgzs** [comment]
预计这周能全部解决
