### ISSUE TITLE
[BUG]win系统无法加载群头像、个人头像

### ISSUE THREAD

**Issue by Erwwyh** [Icalingua-plus-plus/Icalingua-plus-plus#615]
无法加载群头像，个人头像，清除缓存或清除表情缓存有概率刷出部分头像，右键查看头像显示黑色图片，不加载头像图片

环境，windows11最新版，x64安装包，macOS方式登录，2.9.2版本

顺提，希望做一下不显示头像的选项卡，QQ的头像不是必要显示信息
说起来，头像不换的话应该是保存在本地，但是为什么能加载不出来呢

**Comment by Erwwyh** [comment]
补充一下图片
![image](https://user-images.githubusercontent.com/91678266/224529634-20b34d64-990b-412f-8faa-ebb8b4b41d07.png)
![image](https://user-images.githubusercontent.com/91678266/224529651-bf90a7d7-d4da-4af6-a95b-e8ac514fdb98.png)

**Comment by futuretech6** [comment]
最近遇到这个情况，清除缓存重新加载也没用，反而直接重新加载有效果

**Comment by naiyQAQ** [comment]
这个好像是腾讯图片站的问题
qlogo.cn和qpic.cn的图片都会时不时出问题

**Comment by Icalinguaplusplus** [comment]
网络问题
