### ISSUE TITLE
[BUG]显示 "自定义插件出错"

### ISSUE THREAD

**Issue by NAOLIU** [Icalingua-plus-plus/Icalingua-plus-plus#616]
**Describe the bug / 描述**
不停显示自定义插件出错

**To Reproduce / 复现过程**
打开程序就会报错，重装了也一样

**Expected behavior / 预期的结果**
显示 "自定义插件出错"

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/55797625/224626830-2c1173a1-a095-4ab1-bcac-96a17d68bb69.png)

**System information / 系统信息**
 - OS: windows10

**Additional context / 附加信息**
无

**Comment by shenjackyuanjie** [comment]
简洁回答：关掉它就好了（上边栏里的 `选项`
