### ISSUE TITLE
[Error]无法使用部分接口登录

### ISSUE THREAD

**Issue by Yuzgaf33tref6** [Icalingua-plus-plus/Icalingua-plus-plus#617]
**Describe the bug / 描述**

> 无法使用Android Watch或者aPad、iPad登录，仅可使用MacOS和Android
> 使用随机设备ID也未能解决

--------------------------------------------------------------------
**Screenshots / 截图**

> ![image](https://user-images.githubusercontent.com/91740046/224654665-4ffd3d3e-568c-4f10-84f0-16b725e2ff57.png)
> ![image](https://user-images.githubusercontent.com/91740046/224654862-84d2dad4-36ca-403f-8005-7ea4fe3aa93a.png)
> ![image](https://user-images.githubusercontent.com/91740046/224655217-c4c6a445-69d5-467d-892b-bcc2872e975c.png)

--------------------------------------------------------------------
**System information / 系统信息**

> - 版本:	                        Windows 10 专业版
> - 版本号:	                        22H2
> - 安装日期:	‎                2022/‎3/‎12
> - 操作系统内部版本:	19045.2673
> - 体验:	                        Windows Feature Experience Pack 120.2212.3030.0
> 

--------------------------------------------------------------------

> 软件版本:                        2.9.2

--------------------------------------------------------------------
**Additional context / 附加信息**

> None

**Comment by jackyliu16** [comment]
使用版本：2.9.2 Appimage
在使用QR扫码进行登录的时候，手机端显示登陆成功，但是实际点击已扫码没有办法正常进入页面
```
{
  self_id: 2468491006,
  time: 1678725353,
  post_type: 'system',
  system_type: 'login',
  sub_type: 'qrcode',
  image: <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 87 00 00 00 87 01 00 00 00 00 14 9c 77 a7 00 00 00 09 70 48 59 73 00 00 0b 13 00 00 0b 13 01 ... 472 more bytes>
}
{
  self_id: 2468491006,
  time: 1678725372,
  post_type: 'system',
  system_type: 'login',
  sub_type: 'error',
  code: 16,
  message: '[登录失败]你的用户身份已失效，为保证帐号安全，请你重新登录。'
}
```

**Comment by dmlgzs** [comment]
此前的头部签名 API 已解决此问题
