### ISSUE TITLE
[Feature Request] 在自适应单面板模式下让消息提示的位置向下偏移

### ISSUE THREAD

**Issue by FBIKdot** [Icalingua-plus-plus/Icalingua-plus-plus#620]
**Is your feature request related to a problem? Please describe.**
消息提示在单面板模式下会遮挡返回按钮与群名, 这使得点击返回按钮有一点点障碍. 

**Describe the solution you'd like**
消息提示在单面板模式下距离窗口顶部向下偏移更远.

**Describe alternatives you've considered**
"消息提示"来自于element ui. 我参考了官方的[Message 消息提示](https://element-plus.org/zh-CN/component/message.html#message-%E9%85%8D%E7%BD%AE%E9%A1%B9)文档, 看起来可以通过声明`message`的`offset`属性来实现位置下偏. 
~~~js
this.$message({
    message: '不啦不啦不啦',
    offset: 55
});
~~~

**Additional context**
![消息提示在单面板模式下会遮挡返回按钮与群名](https://user-images.githubusercontent.com/83176414/226112565-de48a5a5-af32-4aba-a274-534cab1b90ef.png)

**Comment by Icalinguaplusplus** [comment]
打开 静默获取历史消息 隐藏吧

**Comment by FBIKdot** [comment]
啊这
好吧
