### ISSUE TITLE
[BUG]有时关闭后程序存在残留进程，导致无法重新开启，也无法杀死

### ISSUE THREAD

**Issue by i35010u** [Icalingua-plus-plus/Icalingua-plus-plus#623]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
在加载所有图片不成功后我退出Icalingua++并试图重新开启，不能成功启动，任务管理器中查看存在多个Icalingia++.exe进程，其中有两个进程PID分别为8184和5716，其他进程均可正常杀死但这两个不行，任务管理器中尝试结束显示Access denied.
以下为尝试在CMD中运行taskkill的输出
```
C:\Windows\System32>taskkill /PID 8184
SUCCESS: Sent termination signal to the process with PID 8184.

C:\Windows\System32>taskkill /PID 5716
ERROR: The process with PID 5716 could not be terminated.
Reason: This process can only be terminated forcefully (with /F option).

C:\Windows\System32>taskkill /PID 8184 /F
ERROR: The process with PID 8184 could not be terminated.
Reason: There is no running instance of the task.

C:\Windows\System32>taskkill /PID 5716 /F
ERROR: The process with PID 5716 could not be terminated.
Reason: There is no running instance of the task.

C:\Windows\System32>taskkill /PID 5716 /T
ERROR: The process with PID 5716 (child process of PID 1580) could not be terminated.
Reason: This process can only be terminated forcefully (with /F option).

C:\Windows\System32>taskkill /PID 5716 /T /F
ERROR: The process with PID 5716 (child process of PID 1580) could not be terminated.
Reason: There is no running instance of the task.

C:\Windows\System32>taskkill /PID 5716
ERROR: The process with PID 5716 could not be terminated.
Reason: This process can only be terminated forcefully (with /F option).
```
**To Reproduce / 复现过程**
不清楚如何复现此状态
**Expected behavior / 预期的结果**
Icalingua++关闭后的残留进程无法杀死，并且无法重新打开Icalingua++，伴有整个系统网络无法使用
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]
OS:Windows 11
Version:22621.1413
**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by shenjackyuanjie** [comment]
是如何关闭ica的？
是ctrl+q吗？

**Comment by i35010u** [comment]
> 是如何关闭ica的？ 是ctrl+q吗？

任务栏托盘图标右键关闭

**Comment by dmlgzs** [comment]
你的系统中有驱动问题（例如杀软）或者硬件问题导致内核中 IO 阻塞卡死，和软件无关
