### ISSUE TITLE
[BUG] bridge模式下无法发送图片

### ISSUE THREAD

**Issue by FairyScript** [Icalingua-plus-plus/Icalingua-plus-plus#626]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

使用bridge模式连接,其他人发送的图片可以正常查看,自己发送图片(无论群聊或私聊)右下角一直转圈,直到发送下一条消息后转圈消失.

**To Reproduce / 复现过程**

1. bridge模式正常登陆
2. 打开一个对话,发送图片
3. 右下角转圈

**Expected behavior / 预期的结果**

正常发出图片

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

![image](https://user-images.githubusercontent.com/7751581/228715223-3c075969-72fd-400a-b8ff-a0424f625695.png)

**System information / 系统信息**
 - OS: Windows 11 / Bridge: docker
 - Version  2.9.3 / 2.9.3

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

观察devtools,没有任何相关的网络请求
bridge处没有看到有关的错误信息

**Comment by ttimochan** [comment]
可以提供一下 NGINX 的日志么？或者反向代理的部分

**Comment by FairyScript** [comment]
补充一些信息:

我使用的反向代理是 traefik v2 配置了ssl.

但在经过代理/暴露端口直连的情况下,下述情况都没有变化.问题也没有改善.

在 log-level 为 debug 的情况下,traefik没有任何有关的错误信息输出.但在时间接近的时候出现了一条
`time="2023-03-30T08:32:37Z" level=debug msg="Error while setting TCP connection deadline: set tcp 192.168.xxx.xxx:PORT: use of closed network connection"`

该地址是后端数据库 pgsql的位置,尚不清楚与图片是否有关.

bridge 容器的 docker logs 中 没有任何与发送图片相关的信息出现.与之相对的,发送消息会携带有一条形如 `[2023-03-30T16:30:10.687] [INFO] [MacOS:QQ_ID] - send to: [Group: GROUP_ID/ message_id: PFeP2R8gWEYABOhiWRyz0GQlSJIB]` 的消息.发送图片时并没有类似的内容出现.

**Comment by FairyScript** [comment]
从另一客户端排查发现,问题可能出在客户端
卸载后重新安装问题解决.
