### ISSUE TITLE
[Feature Request] linux appimage 格式的如何多开

### ISSUE THREAD

**Issue by newyorkthink** [Icalingua-plus-plus/Icalingua-plus-plus#629]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shenjackyuanjie** [comment]
启动的时候加个 -config 参数然后自己再写一个配置文件就···行？

**Comment by newyorkthink** [comment]
蛤？

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus#:~:text=%E6%8C%87%E5%AE%9A%E9%85%8D%E7%BD%AE%3A,path%2Dyou%2Dwant
