### ISSUE TITLE
[BUG] 错误地将文本消息显示为表情，表情会超过气泡

### ISSUE THREAD

**Issue by UraraChiya** [Icalingua-plus-plus/Icalingua-plus-plus#630]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

将会把文字消息如“[流泪]请使用最新版手机QQ体验新功能”以表情显示，且表情会超过气泡尺寸

**To Reproduce / 复现过程**

自己或他人发送文字消息如“[流泪]请使用最新版手机QQ体验新功能”

**Expected behavior / 预期的结果**

仅显示文字消息而不显示表情，显示表情时不超过气泡尺寸

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

Icalingua++：
![Snipaste_2023-04-02_15-01-55](https://user-images.githubusercontent.com/47343409/229338003-d133bf1b-a877-47b3-96a5-49edb8f285e4.png)
Android QQ：
![QQ_Image_1680418980209](https://user-images.githubusercontent.com/47343409/229338014-bff216b8-8887-4f6f-be8f-7801d849d862.jpg)

**System information / 系统信息**
 - OS: Windows 11
 - Version 22621.1413

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
这个表情是 feature（
