### ISSUE TITLE
[BUG]清理会话按钮无效

### ISSUE THREAD

**Issue by FishCMD** [Icalingua-plus-plus/Icalingua-plus-plus#631]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
清理会话按钮无效

**Expected behavior / 预期的结果**
删除相应时间段的信息

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/54362633/229340361-c5b8245f-67ce-41be-924b-5a6017ac7810.png)

**System information / 系统信息**
 - OS: [Windows 10]
 - Version [22H2]

**Comment by Icalinguaplusplus** [comment]
清理的是会话列表不是聊天记录
