### ISSUE TITLE
[BUG] 戳一戳历史无法被拉取、无法撤回、撤回后仍然显示

### ISSUE THREAD

**Issue by TripleCamera** [Icalingua-plus-plus/Icalingua-plus-plus#633]
**Describe the bug / 描述**

1. 拉取历史消息时，里面没有戳一戳。
2. 戳一戳在 ica++ 上不能撤回。
3. 手机上撤回戳一戳后，ica++ 上没有显示撤回。

**To Reproduce / 复现过程**

1. 退出 ica++，在手机上发送戳一戳，然后启动 ica++，拉取历史消息。
2. 在 ica++ 上点击戳一戳，无法撤回。
3. 在手机上撤回戳一戳，ica++ 上没有显示撤回。

（在 ica++ 上双击头像即可戳一戳）

**Expected behavior / 预期的结果**

戳一戳历史可以被拉取、可以撤回、撤回后会隐藏或消失。

**Screenshots / 截图**

**System information / 系统信息**

 - OS: Windows 11
 - Version 2.9.3

**Additional context / 附加信息**

**Comment by Icalinguaplusplus** [comment]
暂时不会支持
