### ISSUE TITLE
[BUG]禁止登录

### ISSUE THREAD

**Issue by Chenyu550** [Icalingua-plus-plus/Icalingua-plus-plus#637]
**现在只能用Mac协议了，其他的全嘎了。好长时间了。还有办法修复吗**

**Comment by Chenyu550** [comment]
其它协议一律禁止登录

**Comment by aimerneige** [comment]
点击“无法登录”

**Comment by dmlgzs** [comment]
更新最新版 在常用环境下登录，如果还不行就 mac 登录成功后删除 token 再切 apad

**Comment by Chenyu550** [comment]
> 更新最新版 在常用环境下登录，如果还不行就 mac 登录成功后再切 apad

我狂点登录按钮、不断尝试，点了’三十多下后竟然登录上了🥲

**Comment by Chenyu550** [comment]
> 更新最新版 在常用环境下登录，如果还不行就 mac 登录成功后再切 apad

又不行了，今下午腾讯又提版本了，我的手机QQ也是被迫升级才能继续用的，现在又只剩Mac能用了

**Comment by bczhc** [comment]
> > 更新最新版 在常用环境下登录，如果还不行就 mac 登录成功后再切 apad
> 
> 又不行了，今下午腾讯又提版本了，我的手机QQ也是被迫升级才能继续用的，现在又只剩Mac能用了

同样。用着用着突然手机跟电脑都下线了，我还以为号被封了。手机上升级到了最新版才能用，Icalingua Mac登录还可用。

**Comment by dmlgzs** [comment]
> 又不行了，今下午腾讯又提版本了，我的手机QQ也是被迫升级才能继续用的，现在又只剩Mac能用了

这个版本呢？https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/actions/runs/4699808272

**Comment by Chenyu550** [comment]
> > 又不行了，今下午腾讯又提版本了，我的手机QQ也是被迫升级才能继续用的，现在又只剩Mac能用了
> 
> 这个版本呢？https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/actions/runs/4699808272

虽然不提示版本过低了，但是其它协议“禁止登录，建议升级至最新版本”的老毛病又来了。先Mac登录，再换协议就会卡在登录上

**Comment by dmlgzs** [comment]
> 虽然不提示版本过低了，但是其它协议“禁止登录，建议升级至最新版本”的老毛病又来了。先Mac登录，再换协议就会卡在登录上

这不是什么毛病 是因为你没在常用环境下登录需要验证t544和包签名 目前暂时不好解决
更换协议需要到 数据目录/data/qq号 目录里将 token 文件删除，才能继续登录

**Comment by Chenyu550** [comment]
> > 虽然不提示版本过低了，但是其它协议“禁止登录，建议升级至最新版本”的老毛病又来了。先Mac登录，再换协议就会卡在登录上
> 
> 这不是什么毛病 是因为你没在常用环境下登录需要验证t544和包签名 目前暂时不好解决 更换协议需要到 数据目录/data/qq号 目录里将 token 文件删除，才能继续登录

明白了

**Comment by dmlgzs** [comment]
最新版的 fix 方案应该没问题了

**Comment by Chenyu550** [comment]
> 最新版的 fix 方案应该没问题了

嗯，没问题了
