### ISSUE TITLE
[BUG]上传视频/文件失败

### ISSUE THREAD

**Issue by ghost** [Icalingua-plus-plus/Icalingua-plus-plus#638]
**Describe the bug / 描述**
上传视频/文件失败

**To Reproduce / 复现过程**
上传任意文件

**Expected behavior / 预期的结果**
上传成功

**Screenshots / 截图**
![QQ_Image_1681139628566](https://user-images.githubusercontent.com/55263000/230930276-3a25c95e-ce56-4ca2-a2d2-0ef0bdd06b66.jpg)

**System information / 系统信息**
 - OS: Windows 11
 - Version 22H2(22621.1485)

**Additional context / 附加信息**

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus/commit/8c8682826ca3847ccb11ac6e7722cb6b15fece1c
