### ISSUE TITLE
2.9.4版本消息发不出去

### ISSUE THREAD

**Issue by zmd56** [Icalingua-plus-plus/Icalingua-plus-plus#644]
今天更新后，出现消息发不出去的情况

**Comment by zmd56** [comment]
icalingua> [2023-04-17T13:18:29.690] [WARN] [aPad:428551] - 群消息被风控，将尝试使用分片发送。
[2023-04-17T13:18:34.694] [ERROR] [aPad:428551] - send failed: [Group: 823167016] 群消息可能发送失败，请检查消息内容。

**Comment by zmd56** [comment]
个人消息可以发送成功

**Comment by unknown10777** [comment]
1) 打开手机qq
2) 随便扣个1
3) 点击“您的帐号可能涉及业务违规，请点此处理”
4) 按操作解除限制

**Comment by Icalinguaplusplus** [comment]
新版本更换8933协议
