### ISSUE TITLE
[BUG]无法登录

### ISSUE THREAD

**Issue by hhhhibiki** [Icalingua-plus-plus/Icalingua-plus-plus#647]
![image](https://user-images.githubusercontent.com/49819177/234159260-dfad63a7-2131-41f0-b90e-57dfba651686.png)
提示过于频繁，但是我之前压根没登陆过

**Comment by hhhhibiki** [comment]
2.9.4版本

**Comment by shenjackyuanjie** [comment]
我觉得干脆整个 无法登录 情况合集
现在issue里好多都是无法登录
