### ISSUE TITLE
[BUG] 无法发送 pdf 文件

### ISSUE THREAD

**Issue by aimerneige** [Icalingua-plus-plus/Icalingua-plus-plus#649]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

当试图发送 pdf 文件作为附件时，ica会将其处理为图片而无法上传。

**To Reproduce / 复现过程**

尝试上传文件，选择 pdf 文件进行上传。

**Expected behavior / 预期的结果**

行为应与其他文件类似，可以直接上传文件。

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

![image](https://user-images.githubusercontent.com/51701792/234239797-0c0506f3-8e54-4b0b-bca9-d3b0cc3f5028.png)

**System information / 系统信息**
 - OS: [Fedora]
 - Version [2.9.4]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

这个 bug 已经存在多个版本了，是我使用方式不对吗？

**Comment by Icalinguaplusplus** [comment]
右键附件图标以文件形式发送

**Comment by aimerneige** [comment]
这个操作有点不符合直觉，可以考虑优化一下。

**Comment by bcegkmqs23** [comment]
不知为何我右键的效果等同左键
