### ISSUE TITLE
[BUG & Feature Request] 自动拉取历史消息 Bug

### ISSUE THREAD

**Issue by alex3236** [Icalingua-plus-plus/Icalingua-plus-plus#65]
**Describe the bug / 描述**
开启自动拉取历史消息后，即使群聊没有新消息且没有其他历史消息，也会提示“已拉取20条消息”

**To Reproduce / 复现过程**
开启自动拉取历史消息，进入群聊

**Expected behavior / 预期的结果**
群聊没有新消息时，无任何提示

**Additional context / 附加信息**

如果可以，我希望添加一些新功能。
- [ ] 无论自动还是手动，默认只拉取一部分云端消息。上滑到本地已有消息末端后，自动拉取更早的消息。
- [x] 添加一个开关，自动拉取历史消息后，无论是否拉取到新的消息，都不进行提示。

**Comment by xiaozhangup** [comment]
确实是有这个BUG

`无论自动还是手动，默认只拉取一部分云端消息。上滑到本地已有消息末端后，自动拉取更早的消息。`
这个功能一直有吧好像。
