### ISSUE TITLE
[BUG] 转发消息记录时若包含文件，文件不能被转发出去

### ISSUE THREAD

**Issue by EnderAvaritia** [Icalingua-plus-plus/Icalingua-plus-plus#651]
**Describe the bug / 描述**
转发消息记录时若包含文件，文件不能被转发出去

**To Reproduce / 复现过程**
![image](https://user-images.githubusercontent.com/84321282/234307748-927ce4db-a1f8-419a-9bda-302e39bf4bc7.png)
![image](https://user-images.githubusercontent.com/84321282/234307965-26d4abbe-a0d2-4ee3-83cf-3088d8543ed7.png)

**Expected behavior / 预期的结果**
转发时能转发文件

**System information / 系统信息**
 - OS: windows10
 - Version 21H2

**Comment by Wenti-D** [comment]
我在 #570 提过了（

**Comment by EnderAvaritia** [comment]
> 我在 #570 提过了（

啊……那我要不要撤了这个

**Comment by Icalinguaplusplus** [comment]
协议方面不会支持往外合并转发文件
