### ISSUE TITLE
[BUG]无法登录

### ISSUE THREAD

**Issue by WSXYT** [Icalingua-plus-plus/Icalingua-plus-plus#652]
**Describe the bug / 描述**
登录时出现：[安全提醒]当前网络不稳定,登录失败。推荐使用常用设备或通过手机号登录。

**To Reproduce / 复现过程**
登录
**Expected behavior / 预期的结果**
正常登录
**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/102407247/234477694-f9e02892-1220-4411-bbcd-1333c5177581.png)

**System information / 系统信息**
Windows11

**Comment by Chenyu550** [comment]
天哪，你这都落后100个版本了

**Comment by 839781960** [comment]
> 天哪，你这都落后100个版本了

不是的最新版本也是登录过于平凡

**Comment by hhhhibiki** [comment]
我也是这样...
