### ISSUE TITLE
[BUG]无法登录

### ISSUE THREAD

**Issue by odyy345-ui** [Icalingua-plus-plus/Icalingua-plus-plus#653]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

除FIX协议外其他协议均显示“[禁止登录]你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试”，但FIX协议会使安卓端掉登录。

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

使用其他协议可以正常登录。

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![图片](https://user-images.githubusercontent.com/98475698/235286970-6f4a22d0-3dfc-46a0-8669-7e57e31be963.png)

**System information / 系统信息**
 - OS: [e.g. Arch Linux]Arch Linux
 - Version [e.g. 2.1.4] 2.9.6

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by dmlgzs** [comment]
使用fix登录成功后退出软件再用8933上线即可
退出软件前不能用手机把协议挤下线
