### ISSUE TITLE
[Feature Request] 显示谁在什么时间撤回了消息

### ISSUE THREAD

**Issue by su226** [Icalingua-plus-plus/Icalingua-plus-plus#654]
**Is your feature request related to a problem? Please describe.**
目前被撤回的消息只显示 This message was deleted，不能区分是发消息的人自己撤回的还是管理员撤回的，并且也看不到是什么时候撤回的。

**Describe the solution you'd like**
1. 显示撤回消息的时间，可以在发送时间旁边显示，或者将鼠标指针悬浮到 This message was deleted 时上面显示
2. 显示 This message was deleted by 名字(QQ号)，如果是自己撤回的，可以判断性别为男/女/不公开显示 by himself/herself/themself，或者直接不显示 by xxx（私聊也可以不显示）

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/96ea5b987cbc34dc0bb7b50cf2c869dcf6288041
