### ISSUE TITLE
[Feature Request] 多账号支持

### ISSUE THREAD

**Issue by nullqwertyuiop** [Icalingua-plus-plus/Icalingua-plus-plus#660]
**Is your feature request related to a problem? Please describe.**
目前 icalingua++ 似乎不支持同时登录多个账号，如果需要切换账号则只能退出 icalingua++ 使用另一账号登录。

**Describe the solution you'd like**
实现多个 icalingua++ 实例登录不同账号，而且数据库配置可以保持一致。

**Describe alternatives you've considered**
使用已保存的登录凭证提供一个切换账号的功能。

**Additional context**
N/A

**Comment by lanthth** [comment]
我一直都是先开一个客户端登录上去，然后开一下steam后就可以在打开一个客户端登陆其他账号
system:pop os 22.04[linux/ubuntu]

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus#:~:text=%E6%8C%87%E5%AE%9A%E9%85%8D%E7%BD%AE%3A,path%2Dyou%2Dwant
