### ISSUE TITLE
[BUG] 按上键重新编辑消息

### ISSUE THREAD

**Issue by EnderAvaritia** [Icalingua-plus-plus/Icalingua-plus-plus#663]
**Describe the bug / 描述**
按上键不能重新编辑消息，而在2.9.8的时候可以。

**Expected behavior / 预期的结果**
按上键可以重新编辑消息。

**System information / 系统信息**
 - OS: Windows 10
 - Version 21H2

**Comment by shenjackyuanjie** [comment]
+1
