### ISSUE TITLE
[BUG] 无法登录，“你的用户身份已失效”

### ISSUE THREAD

**Issue by EdLovecraft** [Icalingua-plus-plus/Icalingua-plus-plus#664]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
选择任意协议登录都提示“你的用户身份已失效，为保证账号安全，请你重新登录”
**To Reproduce / 复现过程**
输入账号密码，选择任意登录协议登录
**Expected behavior / 预期的结果**
正常登录
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://user-images.githubusercontent.com/40231164/237012520-7d377f13-c60a-4450-ad48-30ccbe594f22.png)

**System information / 系统信息**
 - OS: Windows 10 Pro 22H2 19045.2787
 - Version 2.9.10

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
更换设备信息没有作用，依然是同样的提示

**Comment by hhhhibiki** [comment]
我也是这样

**Comment by TianLuoQin** [comment]
METOO

**Comment by Glyceryl6** [comment]
我以为是版本没更新的缘故，然而我更新到最新版本之后仍旧出现这种情况。

**Comment by ree-chee** [comment]
我也是这样

**Comment by NinZeige** [comment]
我也遇到相同问题,aur版本

**Comment by hanbao233xD** [comment]
一样

**Comment by wulawu-pk** [comment]
从2.9.3升上来就这样了，回退版本也不行

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus/commit/484a66c8c35b11c4abd3060e24d2bf9e67429806

**Comment by Icalinguaplusplus** [comment]
fixed in 2.9.11
