### ISSUE TITLE
[Feature Request] 开机自启动/静默启动

### ISSUE THREAD

**Issue by hanbao233xD** [Icalingua-plus-plus/Icalingua-plus-plus#669]
**Describe the solution you'd like**
添加启动项，随Windows启动

**Additional context**
貌似目前还没有自启的功能，也可能是我没找到（
支持静默启动就更好了awa 类似KOOK（启动软件但是不弹出主界面）

**Comment by Icalinguaplusplus** [comment]
请自行加快捷方式到开始菜单的 `启动` 文件夹
静默启动请看 **README**
