### ISSUE TITLE
[BUG]无法发送群消息

### ISSUE THREAD

**Issue by K0itoyuu** [Icalingua-plus-plus/Icalingua-plus-plus#672]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

iPad协议无法发送群消息，使用TIM/QQ都可以正常发送

**To Reproduce / 复现过程**

发送任何消息

**Expected behavior / 预期的结果**

正常发送群消息

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

![image](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/76237220/fe05e929-10bc-4381-86f7-4cb166bf9684)

**System information / 系统信息**
 - OS: [Windows 10]
 - Version [2.9.12]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
请看 2.9.6 的更新日志，不能发送消息是因为账号强制要求头部 sign，需使用带8933的协议
