### ISSUE TITLE
[BUG]视频无法正常播放并被错误的显示为音频

### ISSUE THREAD

**Issue by odyy345-ui** [Icalingua-plus-plus/Icalingua-plus-plus#673]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
如图，视频无法正常显示和播放，只能播放音频

**To Reproduce / 复现过程**
1.发送一个视频文件
2.在icalingua++上查看

**Expected behavior / 预期的结果**
视频可以正常被显示和播放

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![Screenshot_20230521_002912](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/98475698/9d35f6af-8c85-48ab-a812-a680f0ef093d)

**System information / 系统信息**
 - OS: [e.g. Arch Linux] Arch Linux
 - Version [e.g. 2.1.4] 2.9.12

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
注：系统在测试前已pacman -Syu
注2：右键单击“使用本地播放器播放”时可以使用本地播放器正常播放
注3：已确定视频编码受支持（测试时使用H.264编码）

**Comment by dmlgzs** [comment]
Electron 的问题

**Comment by odyy345-ui** [comment]
实测新版本已修复
