### ISSUE TITLE
[BUG]一直提示无网络或清除token

### ISSUE THREAD

**Issue by KongXiaMuGe** [Icalingua-plus-plus/Icalingua-plus-plus#675]
一直提示无网络或清除token，清除后问题依旧
2023.5.22晚装完可以使用，2023.5.23就不能了

 - OS: [Ubuntu 22.04.2 LTS]
 - Version [2.9.13]

**Comment by shenjackyuanjie** [comment]
![image](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/54507071/41229cfb-6c33-4f3c-ad7e-2abf0b49c03c)
相同问题
看起来是探索服务器失败，同时现有服务器无法访问

**Comment by Icalinguaplusplus** [comment]
切换方法已经无效了，请使用签名 api
