### ISSUE TITLE
[BUG] 聊天消息中 URL 紧邻表情时无法正确识别 URL 范围

### ISSUE THREAD

**Issue by JayYoung2021** [Icalingua-plus-plus/Icalingua-plus-plus#680]
**Describe the bug / 描述**

聊天消息中 URL 紧邻表情时无法正确识别 URL 范围

**To Reproduce / 复现过程**

发送一条内容为 `https://baidu.com/42[Face:  0]` 的消息，URL 高亮的范围为 `https://baidu.com/42[Face:`

**Expected behavior / 预期的结果**

URL 高亮的范围是 `https://baidu.com/42`

**Screenshots / 截图**

<img width="168" alt="屏幕截图 2023-05-27 132907" src="https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/60842691/6f1b5579-de1d-4799-b19a-2f406e84432e">

**System information / 系统信息**

 - OS: Windows 10
 
 - Version: 家庭版 22H2 19045.2965

**Additional context / 附加信息**

因为不太可能出现包含 `[Face: *]` 的 URL，所以可以在识别 URL 之前先识别此类字符串（即表情）

**Comment by aimerneige** [comment]
这个 issue 我之前提过

因为真的有可能会存在这样的 url

添加空格是好文明（
