### ISSUE TITLE
界面未适配gnome44

### ISSUE THREAD

**Issue by TDYQ-Liu** [Icalingua-plus-plus/Icalingua-plus-plus#683]
**Describe the bug / 描述**

界面未适配gnome44

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

使用 adwaita 主题

**Screenshots / 截图**
![Screenshot from 2023-06-05 18-21-03](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/71477981/ac136d64-4f2a-473f-8f6d-eda2e41ff850)

**System information / 系统信息**
 - OS: fedora38
 - Version 2.9.13

**Additional context / 附加信息**

**Comment by shenjackyuanjie** [comment]
这是electron的毛病吧？
试试2.10.3？ 更新到Electron22了

**Comment by TDYQ-Liu** [comment]
> 这是electron的毛病吧？ 试试2.10.3？ 更新到Electron22了

还是那样，算了就这样吧，我现在等ical就会被冻结（设置了api
