### ISSUE TITLE
无法发送消息

### ISSUE THREAD

**Issue by LaTristan** [Icalingua-plus-plus/Icalingua-plus-plus#684]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
能够接收消息但是无法发送任何消息，群消息直接显示无法发送，端到端消息显示发送了但是在手机上没有看到，推测发送失败

**To Reproduce / 复现过程**
使用iPad协议登录

**Expected behavior / 预期的结果**
正常发送和接收消息

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
<img width="131" alt="1" src="https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/50165836/7b39e662-d349-432e-b619-576c8bfe45f4">
<img width="244" alt="2" src="https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/50165836/d27190ab-e9b4-436a-9b2a-6326f394213b">

**System information / 系统信息**
 - OS: Windows 11
 - Version 22H2 05

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by DaBinQwQ** [comment]
我同样遇到了这个问题！

**Comment by shenjackyuanjie** [comment]
根据docker的log，看起来是“群消息被风控”
但是实际上并没有
在尝试分片发送之后依然失败

**Comment by EdLovecraft** [comment]
今天中午十二点左右我还能发消息，现在也不行了

**Comment by shenjackyuanjie** [comment]
我刚好反过来
之前不行，这会行了

**Comment by Eslzzyl** [comment]
遇到同样问题
同样使用iPad协议登陆，能够接收消息但是无法发送任何消息，群消息直接显示无法发送，端到端消息显示发送了但是在手机上没有看到
系统: Kubuntu 22.04
Icalingua++ version: 2.9.12

**Comment by DaBinQwQ** [comment]
> 我同样遇到了这个问题！

我昨天就遇到了这个问题，android pad协议，消息接收正常，群消息无法发送，私聊显示正常发送但对方无法收到。
系统：Windows server 2022数据中心版
Ica++版本：2.9.13

**Comment by wulawu-pk** [comment]
我可以正常发送群信息，但是私聊发出去对方看不到

**Comment by mcxgjkh** [comment]
同样遇到了此问题！无法正常发送群消息。
![image](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/94793068/db4b83cb-693e-40a3-b25b-78cce78ca34a)
但可以正常发送私聊信息。
![image](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/94793068/ddb18d28-f781-4de5-bc63-1a38bbacf293)
系统：ArchLinux & KaliLinux & Windows11专业版
icalingua++ version：2.9.13

**Comment by Icalinguaplusplus** [comment]
配置 API 即可解决
