### ISSUE TITLE
[BUG] 静默获取历史消息并不静默

### ISSUE THREAD

**Issue by EnderAvaritia** [Icalingua-plus-plus/Icalingua-plus-plus#685]
**Describe the bug / 描述**
静默获取历史消息并不静默
![Snipaste_2023-06-08_10-22-19](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/84321282/d45be671-5f1b-4570-9398-96ae82d76556)
这个是刻意的设计吗？群一多就直接占半面

**To Reproduce / 复现过程**
打开自动获取历史消息然后重启

**Expected behavior / 预期的结果**
这些提示框是否弹出能否可选

**Screenshots / 截图**
![Snipaste_2023-06-08_10-22-19](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/84321282/f19eba02-f2ec-4b0a-aea9-a65356321c80)

**System information / 系统信息**
版本	Windows 10 企业版
版本号	21H2
安装日期	‎2020/‎10/‎17
操作系统内部版本	19044.1706
体验	Windows Feature Experience Pack 120.2212.4170.0

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by orz12** [comment]
我提交了pr #688

**Comment by EnderAvaritia** [comment]
> 我提交了pr #688

谢谢大佬
