### ISSUE TITLE
[Feature Request]将高频使用的emoji放在前面

### ISSUE THREAD

**Issue by SteveWorkshop** [Icalingua-plus-plus/Icalingua-plus-plus#686]
发表情得从几百个表情里面一个一个挑，严重降低工（liao）作（mei）效率

**Comment by orz12** [comment]
emoji不是有个历史记录吗
![image](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/17450420/09c514c5-c871-4fe3-a626-2b90bcc8c8af)

**Comment by SteveWorkshop** [comment]
不是这个系统表情，是tx的表情。face，没有历史记录
好吧说emoji可能会造成误解
