### ISSUE TITLE
[Feature Request]希望开发者完善表情支持

### ISSUE THREAD

**Issue by Swizzzer** [Icalingua-plus-plus/Icalingua-plus-plus#69]
目前的版本下，对方发送的一些表情己方无法识别。比如狗头这一表情，自己发出去的可以看到，但是对方发过来的只能显示为“/汪汪”而不会被正常显示为狗头，如图所示
![2022-04-16_210413](https://user-images.githubusercontent.com/91253943/163676196-a912a4a5-64a3-47ba-8f41-61ebc8130b9c.png)
。

**Comment by Icalinguaplusplus** [comment]
似乎是登錄協議問題，經測試默認的 iPad 協議無法復現
