### ISSUE TITLE
[BUG]2023年6月23日2023年6月23日18:35:00起突然开始登录不上

### ISSUE THREAD

**Issue by mtr-static-official** [Icalingua-plus-plus/Icalingua-plus-plus#690]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
突然出现下线通知，随后无法登陆，提示

> 账号被限制使用内置的 QQ 版本登录，请等待更新，或使用 FIX 协议登录成功后再更换带 8933 的协议重试

使用FIX协议无效，出现相同提示内容。

**To Reproduce / 复现过程**

1. 运行icalingua
2. 使用aPad 8933协议登录
3. 使用FIX协议

**Expected behavior / 预期的结果**
均正常
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

![image](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/64729760/f4bfc740-a9a5-4929-8fcf-91e52b2ce21e)
![image](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/64729760/02a1875b-50e9-47b9-8113-00b3082d56cb)

**System information / 系统信息**
 - OS: Windows 22H2
 - Version 2.9.13

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Aperove** [comment]
俺也一样

**Comment by scientificworld** [comment]
+1，我也是45。看没人开issue还以为是我自己账号问题

~~不过我是昨天晚上就被下线了~~

**Comment by humonia-sys** [comment]
同样有这个问题...昨天晚上23点和手机qq一起被踢下线了,手机qq在更新后好了而ica不行(

**Comment by TDYQ-Liu** [comment]
我也是**(45)**

**Comment by toyotomi830** [comment]
> 同样有这个问题...昨天晚上23点和手机qq一起被踢下线了,手机qq在更新后好了而ica不行(

复议

**Comment by SherkeyXD** [comment]
> > 同样有这个问题...昨天晚上23点和手机qq一起被踢下线了,手机qq在更新后好了而ica不行(
> 
> 复议

同，tx可能又加强检测了

**Comment by builded** [comment]
已经无了
"https://t.me/s/abcthoughts/4929"

**Comment by hhhhibiki** [comment]
> 

哎，难受

**Comment by Icalinguaplusplus** [comment]
配置 API 即可解决
