### ISSUE TITLE
[BUG]2023年6月20号左右起私聊发送失败

### ISSUE THREAD

**Issue by Colt6uench** [Icalingua-plus-plus/Icalingua-plus-plus#691]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
私聊发消息失败，群聊正常
**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/128881846/4032f785-467a-4562-9de1-185ecf300cc9)
![WDFQRPPNL%RQRRL1 PNUY(M](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/128881846/5fccb081-509a-4eb7-ae31-565d39c7cf53)
![image](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/128881846/03f6d0f4-5153-4ea1-934f-2805ef2196e1)

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]
2.9.13
**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by wulawu-pk** [comment]
确实，我也发不了私聊了

**Comment by Colt6uench** [comment]
今天更新后依然发起私聊失败

**Comment by Icalinguaplusplus** [comment]
配置 API 即可解决
