### ISSUE TITLE
现在更新的这个头部api...

### ISSUE THREAD

**Issue by lanthth** [Icalingua-plus-plus/Icalingua-plus-plus#694]
**Describe the bug / 描述**
emmmm，这是个啥，没有这个发不了消息？现在只能看消息了？

**Comment by lanthth** [comment]
这个头部api怎么填（真不懂了

**Comment by lanthth** [comment]
ok了，同志们，刚刚看到了更新里面的API获取工具链接后我就可以登陆发消息了
1.https://github.com/fuqiuluo/unidbg-fetch-qsign 这个事api获取工具
2.把该工具下载下来，解压后进入工具目录
![图片](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/76894954/2c51dde3-85d1-4f99-a0ad-ae5edce402f0)

3.确定有安装java
![图片](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/76894954/329554d1-5c12-433a-a6b0-e6016b14ee4d)

4.下载QQ的安卓版本，然后提取安装包中的这两个东西，路径在图片里
![图片](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/76894954/0c2c3add-e78f-40be-941b-cda8293e9ed2)
![截图 2023-06-28 21-44-59](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/76894954/7b3b6b12-fda3-4603-88f4-cc601cd87ff7)

5.使用 bash bin/unidbg-fetch-qsign --host=0.0.0.0 --port=8080  --count=2 --library=『刚才提取的那两个文件的绝对路径』 --android_id=『手机的登陆设备ID，可以在手机版上面登陆设备中查看』
#示例 bash bin/unidbg-fetch-qsign --host=0.0.0.0 --port=8080  --count=2 --library=/home/lanthth/working/unidbg-fetch-qsign-1.0.5/ --android_id=J9210
![图片](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/76894954/6e1296a2-0538-466b-8f69-c99f9dbf9e8d)
可以像我这样偷懒把提取的文件放到工具的解压目录中

启动后不要关闭该窗口！
启动后不要关闭该窗口！
启动后不要关闭该窗口！
6.http://127.0.0.1:8080/sign?uin=[UIN]&qua=V1_AND_SQ_8.9.63_4188_HDBM_T&cmd=[CMD]&seq=[SEQ]&buffer=[BUFFER]
在signAPI里面直接填这个
END.
system [pop os 22.04]
![图片](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/76894954/8be7cd6f-87d0-4476-b6dc-66b4114439a4)
java version
![截图 2023-06-28 21-42-49](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/76894954/e24488b1-ee77-48d7-a98a-830d3d494a94)
icalingua version 2.9.19

**Comment by xiaohei2333** [comment]
裂开 搞了一早上没搞成，各种报错

**Comment by lanthth** [comment]
> 

具体一点，是什么报错什么平台，我看看我能不能解决

**Comment by ttimochan** [comment]
有预建的 Docker 版本，可以使用 docker-compose 快速部署

**Comment by paletteOvO** [comment]
docker-compose的問題也很多，建議直接用他的image，一行指令就好，顯得我前面折騰了半天很蠢

**Comment by ttimochan** [comment]
> docker-compose的問題也很多，建議直接用他的image，一行指令就好，顯得我前面折騰了半天很蠢

Yes，直接用 Docker Image，简单省事
