### ISSUE TITLE
[BUG]账号被限制适用内置 QQ 登录，请等待更新，或者用 TIM 协议登录

### ISSUE THREAD

**Issue by 2759942374** [Icalingua-plus-plus/Icalingua-plus-plus#696]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
![](https://cdn.luogu.com.cn/upload/image_hosting/l3pbquki.png)
**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]

**Additional context / 附加信息**
我不懂啊，为啥登不进去，TIM 协议是啥

**Comment by 2759942374** [comment]
https://cdn.luogu.com.cn/upload/image_hosting/l3pbquki.png

**Comment by lyrnya** [comment]
难受https://t.me/Icalinguapp_Updates/45
