### ISSUE TITLE
[BUG] v2.9.21 无法下载 PNG 格式的图片

### ISSUE THREAD

**Issue by 56789a1987** [Icalingua-plus-plus/Icalingua-plus-plus#697]
**Describe the bug / 描述**
聊天中 PNG 格式的图片，右键下载或另存为均没有反应，JPG/GIF 等可以正常下载。
可能与 #679 有关。

**To Reproduce / 复现过程**
下载聊天中任意 PNG 格式的图片

**Expected behavior / 预期的结果**
正常下载图片

**Screenshots / 截图**
点击下载后出现报错
![Screenshot_20230703_173653](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/47248675/8faf289a-f1f3-4ebd-918f-15cd9917b02a)

**System information / 系统信息**
 - OS: Arch Linux
 - Version 2.9.21

**Comment by su226** [comment]
应该是 [这个 commit](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/1ac01136a826222f5780af6e33cab6a29886acc0) 带来的问题
