### ISSUE TITLE
[Feature Request] Mac 版支持

### ISSUE THREAD

**Issue by lixiao189** [Icalingua-plus-plus/Icalingua-plus-plus#7]
能添加对 Mac 的支持吗，mac 上的 QQ 万年不更新，后台 CPU 占用率高，想用这个当官方 QQ 的替代品

**Comment by Icalinguaplusplus** [comment]
感謝建議，已增加 macOS 簡易版構建腳本。
由於 GitHub Actions 的限製，暫時無 arm64 構建，可自行 clone 代碼使用 Yarn 構建。

**Comment by lixiao189** [comment]
> 感謝建議，已增加 macOS 簡易版構建腳本。
> 由於 GitHub Actions 的限製，暫時無 arm64 構建，可自行 clone 代碼使用 Yarn 構建。

感谢🙏
