### ISSUE TITLE
[Feature Request] 希望能够像Telegram那样，左侧列表在靠近头像后直接隐藏掉文字

### ISSUE THREAD

**Issue by MemoryShadow** [Icalingua-plus-plus/Icalingua-plus-plus#70]
希望能够像Telegram那样，左侧列表在靠近头像后直接隐藏掉文字

示例图片:

![image](https://user-images.githubusercontent.com/31596045/163682787-9901cd36-e924-46c3-9d7b-0a55fb995956.png)

**Comment by ForkKILLET** [comment]
我试着做一下

**Comment by MemoryShadow** [comment]
非常感谢，主要是最近没有时间来研究这个框架，不然就自己提PR啦
