### ISSUE TITLE
[BUG]我在2.9.21版本突然无法发送消息

### ISSUE THREAD

**Issue by molly114514** [Icalingua-plus-plus/Icalingua-plus-plus#716]
几天前，我使用2.9.21还能够发送任何消息
而今天（8.5）从10：30我登陆后无法发送群消息
不论群消息正常与否，均无法发送（我在任何群均未被禁言，某些群为强制性全体禁言）
而个人消息可以正常发送
![image](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/141468946/722d5c33-cf48-4306-b84f-122a6bcd6489)

**Comment by dmlgzs** [comment]
请配置 qsign 服务后登录并发送消息
