### ISSUE TITLE
[BUG]无论地址填什么都只会连接到127.0.0.1:80

### ISSUE THREAD

**Issue by Chenyu550** [Icalingua-plus-plus/Icalingua-plus-plus#730]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
签名服务器无论地址填什么都只会连接到127.0.0.1:80
**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
左上和右下
![image](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/114039435/f064c6a2-6689-43f0-82b7-196018b6b3fd)

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by 56789a1987** [comment]
地址加上 http://

**Comment by Chenyu550** [comment]
> 地址加上 http://

可以了，感谢
