### ISSUE TITLE
[BUG]發送消息後對方無法正常接收

### ISSUE THREAD

**Issue by sojuo** [Icalingua-plus-plus/Icalingua-plus-plus#732]
在Windows10上使用[Icalingua++2.19.1 X64版](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/releases/tag/v2.10.1)（头部签名 AP用docker部署[core1.18](https://hub.docker.com/layers/xzhouqd/qsign/core-1.1.8/images/sha256-95f97715636630da03c48c15ed0e59f881d90d3a5af528fac7fa2907ab07e698?context=explore)版本，協議選的Anfroid Pad8.9.70）於一群聊內發送一張帶有圖片的消息，自己的Icalingua++客戶端及手機官方QQAndroid應用程序上也可正常顯示，但是群友卻無法正常接收消息

這是Icalingua++客戶端上顯示的內容：
![Icalingua++_LUFfnnXt4J](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/109811457/eb4e2c49-534a-478e-8ac7-e67f4dcdbb07)

這是QQ官方Android應用程序上顯示的內容:
![1693668099646](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/109811457/0d710369-162c-40c8-b458-361bdaed83f6)

這是群友那邊顯示的內容:
![QQ_Image_DEC02D936B511EAAD1A09397926252F5](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/109811457/70b7db6e-8ab4-4267-beed-b4ea0f581390)

**Comment by lianzhoulu** [comment]
提一嘴，協議選的8970
![图片](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/109811457/9cea0635-591f-4099-8492-ed0c4907fd10)
