### ISSUE TITLE
[BUG]点击发送消息后换群，消息会发送到新选中的群里

### ISSUE THREAD

**Issue by MC-luoluo** [Icalingua-plus-plus/Icalingua-plus-plus#733]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
点击发送消息后换群，消息会发送到新选中的群里

**To Reproduce / 复现过程**
输入一段消息后，点击发送消息，在消息发出之前换群，消息有概率会发送到新选中的群里

**Expected behavior / 预期的结果**
消息应该发送到点击发送时的群内

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [Windows]
 - Version [2.10.1]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by shenjackyuanjie** [comment]
尝试一下新版本？
我反正没复现过

**Comment by Icalinguaplusplus** [comment]
无法复现

**Comment by MC-luoluo** [comment]
可能是之前旧电脑的问题……现在我也不能复现了
