### ISSUE TITLE
[BUG]上传文件进度显示错误

### ISSUE THREAD

**Issue by MC-luoluo** [Icalingua-plus-plus/Icalingua-plus-plus#735]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
上传文件时的进度(百分比)在9.99%以上有一段会卡住不能正确显示,上传到90%以上后又能正确显示

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**
上传文件时显示的进度应该一直都是真实进度

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [Windows 10]
 - Version [2.10.2]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
新版本没有这个问题
