### ISSUE TITLE
点击回复消息跳转到消息来源

### ISSUE THREAD

**Issue by Icalinguaplusplus** [Icalingua-plus-plus/Icalingua-plus-plus#74]

**Comment by bcegkmqs23** [comment]
[目前的实现](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/a1832e96a631c727285a9609c6cbb33909a68d94)有一个不好的地方，就是如果我想复制消息内容，也会触发跳转，而这可能不是我想要的。可能还是搞个传统的按钮好些。

**Comment by Icalinguaplusplus** [comment]
> [目前的实现](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/commit/a1832e96a631c727285a9609c6cbb33909a68d94)有一个不好的地方，就是如果我想复制消息内容，也会触发跳转，而这可能不是我想要的。可能还是搞个传统的按钮好些。

237e8728430461a5b2d8894dac9a70a87e3d3c6e
