### ISSUE TITLE
账号被风控需要头部签名，请根据 README 配置头部签名 API 地址

### ISSUE THREAD

**Issue by wsxcom** [Icalingua-plus-plus/Icalingua-plus-plus#743]
這到底是什麼意思？　有人能跟我說嗎？　要怎麼解決？　有人教教我嗎？

**Comment by shenjackyuanjie** [comment]
你看readme啊
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus#%E5%A4%B4%E9%83%A8%E7%AD%BE%E5%90%8D-api
这个部分

**Comment by Funny-ppt** [comment]
> 你看readme啊 https://github.com/Icalingua-plus-plus/Icalingua-plus-plus#%E5%A4%B4%E9%83%A8%E7%AD%BE%E5%90%8D-api 这个部分

我部署完qsign之后，网页访问证明确实可以用，但是lcalingua++提示不支持的协议版本，请问这个问题如何解决？

**Comment by shenjackyuanjie** [comment]
> > 你看readme啊 https://github.com/Icalingua-plus-plus/Icalingua-plus-plus#%E5%A4%B4%E9%83%A8%E7%AD%BE%E5%90%8D-api 这个部分
> 
> 我部署完qsign之后，网页访问证明确实可以用，但是lcalingua++提示不支持的协议版本，请问这个问题如何解决？

你自己设置的qsign的协议和ica登录协议不一样

**Comment by shenjackyuanjie** [comment]
@Icalinguaplusplus 我觉得应该可以统一 close 一波 这一类
“需要api” “登陆不上去” 的 issue

在 issue 区 pin 一个统一回复就行

**Comment by aimerneige** [comment]
发 issue 请按照模板来，提问请去 Discussions

建议不符合模板的 issue 一律 close
