### ISSUE TITLE
[Feature Request] 希望优先使用xdg-open提供的图片查看器

### ISSUE THREAD

**Issue by wuliaotc** [Icalingua-plus-plus/Icalingua-plus-plus#745]
我的操作系统是arch linux,桌面环境是 **sway**。正使用okular 作为文档查看器，imv 作为图片查看器。
希望使用本地设置（xdg-open）的默认图片查看器来查看图片，这样我在窗口管理器下体验会更好。

**Comment by wuliaotc** [comment]
我看到这个issues里有提到，代码中有一个内置的viewer列表。我想把xdg-open在viewer_list中的顺序调到前面，可能会很有效。
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/issues/524

**Comment by clansty** [comment]
本来是优先用 xdg-mime 查询打开方式的。由于我们会直接把 http 的图片链接传递给查看器，所以如果使用 xdg-open 这种通过文件类型推断打开什么软件的工具可能会打开一个网页浏览器之类的东西，而不是图片查看器
