### ISSUE TITLE
[BUG]部分消息“重新獲取該消息歷史內容”似乎無用？

### ISSUE THREAD

**Issue by sojuo** [Icalingua-plus-plus/Icalingua-plus-plus#749]
之前長時間不上線了，進了一個羣看這一週群友又發了啥消息，發現有一張圖不能正常顯示
![图片](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/109811457/1a136e07-08b0-4746-97c8-035c9f457bbc)
於是右鍵選擇“重新獲取該消息歷史內容”，但是依然無法查看圖片，次現象似乎只出現在Icalingua++客戶端中，用安卓官方客戶端可以正常查看消息。

**Comment by dmlgzs** [comment]
这个是 qqnt 的图片，很早就已经在 dev 修复，请等待新的 release 发布
