### ISSUE TITLE
[BUG]匿名功能无法正常运行（但理论上仍可匿名）。

### ISSUE THREAD

**Issue by wpc2005** [Icalingua-plus-plus/Icalingua-plus-plus#753]
**Describe the bug / 描述**
勾选“匿名发送群消息“后无论在是否开启匿名的群聊中聊天都会报错”匿名失败，终止发送“。

**Expected behavior / 预期的结果**
在手机QQ上，可以通过点击之前自己发送的匿名头像，再点击“更换匿名名称”切换到匿名且可正常发言（但无法切换匿名名称），所以理论上仍可以匿名。

**System information / 系统信息**
 - OS: Win11 x64
 - Version 2.10.6

**Additional context / 附加信息**
顺便说一句，这个可能是前两天某腾的更新，造成了旧版TIM按匿名提示“抱歉，正在维护中”的同时造成的。

**Comment by Icalinguaplusplus** [comment]
匿名功能已经被 qq 砍了，不能获取到匿名所需数据了，无法再使用

**Comment by wpc2005** [comment]
> 匿名功能已经被 qq 砍了，不能获取到匿名所需数据了，无法再使用

但截至今日，我本地QQ（最新版）仍然可以按这个issue说的步骤发匿名消息的。
