### ISSUE TITLE
[Feature Request] 建议移除自带的字体

### ISSUE THREAD

**Issue by chiyuki0325** [Icalingua-plus-plus/Icalingua-plus-plus#76]
自带字体后 Icalingua++ 不会跟随系统字体，所以建议移除。

**Comment by chiyuki0325** [comment]
![图片](https://user-images.githubusercontent.com/73830635/163813054-9b53f448-6c8b-47aa-9674-4052728a56b9.png)

**Comment by Icalinguaplusplus** [comment]
原版似乎有自定義字體，`~/.config/icalingua/font.ttf` 會被自動加載
