### ISSUE TITLE
请求如何获取API Address 和 API Key

### ISSUE THREAD

**Issue by MCheping8108** [Icalingua-plus-plus/Icalingua-plus-plus#767]
我看过文档，但是我实在是看不懂，是否出个更简单的教程？

![image](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/assets/102772286/db8a5fde-1ce1-4fc5-9460-8076a78e73f6)

**Comment by shenjackyuanjie** [comment]
暂时可能给不出更明确的教程了（毕竟腾讯这边你懂得，qsign都删库了）

**Comment by Icalinguaplusplus** [comment]
8.9.7x之前可以用以前的 unidbg-fetch-qsign，也可以在交流群讨论

**Comment by zapata-ok** [comment]
> 8.9.7x之前可以用以前的 unidbg-fetch-qsign，也可以在交流群讨论

请求加入讨论群
