### ISSUE TITLE
有考虑开发安卓版本吗

### ISSUE THREAD

**Issue by QSlotus** [Icalingua-plus-plus/Icalingua-plus-plus#781]
如题

**Comment by aimerneige** [comment]
duplicate #357

**Comment by dffxd-suntra** [comment]
最简单的一集，可以直接用termux配置啊

**Comment by dffxd-suntra** [comment]
> 最简单的一集，可以直接用termux配置啊

这是更切实际的解决方式：https://github.com/capacitor-community/electron  
但这有一个坏处，就是需要的android版本较高，老机器使用不了  
优点是配置简单，不需要更改框架
