### ISSUE TITLE
[Feature Request]希望可以升级node和electron的版本

### ISSUE THREAD

**Issue by zxp19821005** [Icalingua-plus-plus/Icalingua-plus-plus#782]
如题。
目前项目所使用的node版本为16，而目前的最新稳定版本已经是20了；
electron目前版本为22，而当前的主线版本为30.
是否存在安全性问题未知，但是建议使用主线版本。

**Comment by moyanj** [comment]
electron30他不支持win7，可能是兼容性的考虑吧

**Comment by Icalinguaplusplus** [comment]
可以自行下载并使用新版本 electron 进行构建，自动构建版本出于兼容性考虑暂时不会升级。
