### ISSUE TITLE
[BUG]讨论组的消息无法查看

### ISSUE THREAD

**Issue by yimisunrise** [Icalingua-plus-plus/Icalingua-plus-plus#79]
**Describe the bug / 描述**
讨论组的消息可以弹出消息提示，但是无法看到对应讨论组的消息。在联系人中也无法搜索到讨论组。

**To Reproduce / 复现过程**
创建一个讨论组，然后在讨论组中发送消息。

**Expected behavior / 预期的结果**
可以接收并展示讨论组的消息内容。

**Screenshots / 截图**
无

**System information / 系统信息**
OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 5.13.0-40-generic
DE: KDE 5.68.0 / Plasma 5.18.8
WM: KWin
GTK Theme: Breeze [GTK2/3]

**Additional context / 附加信息**
无

**Comment by Icalinguaplusplus** [comment]
沒有考慮支持討論組，另外 QQ 官方已將討論組淘汰。
