### ISSUE TITLE
[BUG] LastMessage 字段会返回原始 buffer

### ISSUE THREAD

**Issue by shenjackyuanjie** [Icalingua-plus-plus/Icalingua-plus-plus#793]
![image](https://github.com/user-attachments/assets/45b564ef-0dbf-4ed7-841a-828e090e7916)

![image](https://github.com/user-attachments/assets/afaaa37b-6920-4986-8715-f41fc2f4956c)

如图所示

**Comment by shenjackyuanjie** [comment]
![image](https://github.com/user-attachments/assets/67007829-cf90-4dd9-8e7e-834004a0c855)

`roomId` 字段怎么会是 `null` 啊啊啊啊啊

**Comment by Icalinguaplusplus** [comment]
https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus/commit/c2e84f59f469fcd24f33169d6294103c02aea01a
