### ISSUE TITLE
[Feature Request]内置的截屏功能

### ISSUE THREAD

**Issue by just-a-pony** [Icalingua-plus-plus/Icalingua-plus-plus#80]
rt，目前如果要发截屏的话，必须要依赖系统的截屏功能或者其他的截屏软件，截图后发送文件或者粘贴图片。
如果可以增加个和原版qq类似的截图功能会方便很多

**Comment by Mashirl** [comment]
直接Win+Shift+S截图，截完Ctrl+V复制进去发就完事了。

**Comment by ManiaciaChao** [comment]
截屏没那么好做的，要考虑许多平台。最简单的方式是用 electron 的 [desktopCapturer API](https://www.electronjs.org/docs/latest/api/desktop-capturer)，但运行在 xwayland 下面的实例是拿不到 wayland 窗口内容的。

我的建议和楼上一样：用系统自带的截图或者你顺手的其他截图工具（比如 snipaste 和 flameshot）进行截图，然后直接粘贴到聊天框。

专门写个截图功能的 ROI 太低了。

**Comment by aimerneige** [comment]
icalingua 是一个 “会话前端框架”
