### ISSUE TITLE
[BUG] 启动闪白屏

### ISSUE THREAD

**Issue by greenhand520** [Icalingua-plus-plus/Icalingua-plus-plus#88]
**描述** 启动闪白屏

**复现过程** 如图：
旧版和新版都有启动闪白屏然后才显示主界面的问题。更新到2.6.2后发现默认用系统自带的electron18.0.1-1启动后不仅闪白屏还无法加载主界面一直卡在白屏，就换回electron17.3.1-1启动了。
![Peek 2022-05-01 16-40](https://user-images.githubusercontent.com/32732204/166138579-281bdd41-8e16-4f50-a2d7-fbd4439fae42.gif)

**系统信息**
 - OS: Manajro 21.2.6
 - Gnome 41.5 
 - 窗口系统 X11 (原本用wayland也是闪白屏)
 - Linux Kernel: 5.15.32-1-MANJARO

**Comment by kasuha07** [comment]
same

**Comment by Hou-Xiaoxuan** [comment]
在刚刚安装的全新系统上遇到了一样的问题。

**Comment by alex3236** [comment]
同问

**Comment by awerty-noob** [comment]
electron18.2恢复正常了，把electron升级下即可
