### ISSUE TITLE
[BUG]打开群聊影片就挂了

### ISSUE THREAD

**Issue by Rosabis** [Icalingua-plus-plus/Icalingua-plus-plus#9]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

**To Reproduce / 复现过程**
1.打开群聊里面的视频
**Expected behavior / 预期的结果**
正常打开视频
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![图片](https://user-images.githubusercontent.com/32984303/156960929-bbf5af80-4b3c-4e0f-bd05-17fdd5d05c79.png)

**System information / 系统信息**
 - OS: [e.g. Arch Linux]Windows
 - Version [e.g. 2.1.4]7

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Icalinguaplusplus** [comment]
我的 Windows10 無法復現，請下載 `ffmpeg` 並將其添加至環境變量中後測試

**Comment by Rosabis** [comment]
> 我的 Windows10 無法復現，請下載 `ffmpeg` 並將其添加至環境變量中後測試

已添加，現在乾脆無法播放聊天訊息裡面的影片了

**Comment by Icalinguaplusplus** [comment]
Windows10 沒有問題，但 Windows7 測試復現了，應該是 Windows7 與所編譯的 ffmpeg 的兼容性問題，最近比較忙，後期會進行排查。
另外前面說的添加其實是沒用的（，Windows 構建默認使用的是軟件內置的 `ffmpeg.dll` ，可嘗試將其替換成第三方構建。
無法播放是因為QQ給的緩存地址失效了，後期也會嘗試解決。

**Comment by Icalinguaplusplus** [comment]
[Electron 13.6.7](https://www.electronjs.org/releases/stable?version=13#13.6.7) 修復了這個問題，下個版本會更換最新版 Electron

**Comment by Icalinguaplusplus** [comment]
很抱歉由於一些原因需要刪除本 issue，如果遇到問題請重新開一個 issue
