### ISSUE TITLE
群课堂和语音通话

### ISSUE THREAD

**Issue by guangda123** [Icalingua-plus-plus/Icalingua-plus-plus#90]
软件的开发者和贡献者你们好，我非常期待你们推出群课堂的语音通话功能，虽然难度或许比较大，但要是开发出来那是最好的

**Comment by xiaozhangup** [comment]
oicq不支持的话 icalingua++也没法做到的吧

**Comment by aimerneige** [comment]
oicq 没有支持相关协议，icalingua++ 是一个 **"会话前端框架"** 而不是 QQ 客户端。

可以考虑向 oicq 提 issue。
