### ISSUE TITLE
[Feature Request] 添加考虑添加注入自定义 css 的接口实现主题功能（夜间模式主题优化）

### ISSUE THREAD

**Issue by aimerneige** [Icalingua-plus-plus/Icalingua-plus-plus#93]
**Is your feature request related to a problem? Please describe.**

icalingua 删除之前有一个 issue 在讨论**优化夜间模式的主题**，与其优化不如直接开一个可以注入自定义 css 的接口，这样社区更加容易制作和优化主题。

**Describe the solution you'd like**

提供一个注入自定义 css 的接口以实现主题切换。

**Describe alternatives you've considered**

无

**Additional context**

无

**Comment by Icalinguaplusplus** [comment]
這個原版似乎就已經有了（？
`~/.config/icalingua/style.css` 會被自動加載

**Comment by mark9804** [comment]
> `~/.config/icalingua/style.css` 會被自動加載

~~请问在 macOS 下，这个自定义 CSS 路径会从哪里读取？~~

~~我尝试了一下 `~/.config/icalingua/style.css`，没有看到效果~~'

找到了，在 `/Users/{username}/Library/Application Support/icalingua`

**Comment by ilyfairy** [comment]
请问Windows下,这个style.css在哪里

**Comment by MoXuanSun** [comment]
> 请问Windows下,这个style.css在哪里

windows下在users/你的用户名/AppData/Roaming/icalingua/下创建一个style.css文件，在里面写之后保存再重新加载即可
