### ISSUE TITLE
[BUG] 图片加载，上传非常慢

### ISSUE THREAD

**Issue by b0123456789** [Icalingua-plus-plus/Icalingua-plus-plus#96]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by b0123456789** [comment]
fedora 35,36
gnome 42
最新版本

**Comment by Icalinguaplusplus** [comment]
建議先檢查自身網絡問題

**Comment by b0123456789** [comment]
用 wine tim(qq) 是没有问题的，现在正常了，明天再看看。

**Comment by b0123456789** [comment]
应该是代理问题，不过wine tim(qq) 是没有问题，是不是发送消息是不是有多条线路的
