### ISSUE TITLE
希望添加向好友发送文件的功能

### ISSUE THREAD

**Issue by Icecoke-ops** [Icalingua-plus-plus/Icalingua-plus-plus#97]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ManiaciaChao** [comment]
https://github.com/takayama-lily/oicq/issues/230 上游还不支持这个功能 :(

**Comment by ToseLogic** [comment]
这个怕不太可行:(

**Comment by Icecoke-ops** [comment]
好的，谢谢

**Comment by prcups** [comment]
上游貌似已经更新了这个功能，前端什么时候跟进呢
